/*
Cisco Secure Access Reports

Testing UtilityAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package reports

import (
	"context"
	"testing"

	openapiclient "github.com/CiscoDevNet/go-ciscosecureaccess/reports"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_reports_UtilityAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test UtilityAPIService GetCategories", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.UtilityAPI.GetCategories(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UtilityAPIService GetIdentities", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.UtilityAPI.GetIdentities(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UtilityAPIService GetIdentity", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var identityid int64

		resp, httpRes, err := apiClient.UtilityAPI.GetIdentity(context.Background(), identityid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UtilityAPIService GetThreatName", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var threatnameid string

		resp, httpRes, err := apiClient.UtilityAPI.GetThreatName(context.Background(), threatnameid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UtilityAPIService GetThreatNames", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.UtilityAPI.GetThreatNames(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UtilityAPIService GetThreatType", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var threattypeid string

		resp, httpRes, err := apiClient.UtilityAPI.GetThreatType(context.Background(), threattypeid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UtilityAPIService GetThreatTypes", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.UtilityAPI.GetThreatTypes(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UtilityAPIService PostIdentities", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.UtilityAPI.PostIdentities(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
