// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Network Tunnel Groups and Regions API

Testing NetworkTunnelGroupsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package main

import (
	"context"
	"fmt"
	"os"

	"github.com/CiscoDevNet/go-ciscosecureaccess/client"
	"github.com/CiscoDevNet/go-ciscosecureaccess/privateapps"
)

func main() {

	// List existing rules
	auth := context.Background()
	factory := client.SSEClientFactory{KeyId: os.Getenv("API_KEY_ID"), KeySecret: os.Getenv("API_KEY_SECRET")}
	apiClient := factory.GetPrivateAppsClient(auth)
	resp, r, err := apiClient.PrivateResourcesAPI.ListPrivateResources(auth).Execute()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error when calling `PrivateResourcesAPI.ListPrivateResources``: %v\n", err)
		fmt.Fprintf(os.Stderr, "Full HTTP response: %v\n", r)
	}
	// response from `ListPrivateResources`: PrivateResourceList
	fmt.Fprintf(os.Stdout, "Response from `PrivateResourcesAPI.ListPrivateResources`: %v\n", resp)

	// Create a new private resource
	var accessTypes = []privateapps.AccessTypesRequestInner{{NetworkBasedAccess: privateapps.NewNetworkBasedAccess("network")}}
	protocol := privateapps.ANY
	ports := "443"
	protocolInner := []privateapps.ResourceAddressesInnerProtocolPortsInner{{Protocol: &protocol, Ports: &ports}}
	addresses := []privateapps.ResourceAddressesInner{*privateapps.NewResourceAddressesInner([]string{"172.6.0.0/32"}, protocolInner)}
	privateResourceRequest := *privateapps.NewPrivateResourceRequest("gotest-pa", accessTypes, addresses)
	createResp, r, err := apiClient.PrivateResourcesAPI.AddPrivateResource(auth).PrivateResourceRequest(privateResourceRequest).Execute()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error when calling `PrivateResourcesAPI.AddPrivateResource``: %v\n", err)
		fmt.Fprintf(os.Stderr, "Full HTTP response: %v\n", r)
	}
	// response from `AddPrivateResource`: PrivateResourceResponse
	fmt.Fprintf(os.Stdout, "Response from `PrivateResourcesAPI.AddPrivateResource`: %v\n", createResp)

	// get new private resource
	getResp, r, err := apiClient.PrivateResourcesAPI.GetPrivateResource(context.Background(), *createResp.ResourceId).Execute()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error when calling `PrivateResourcesAPI.GetPrivateResource``: %v\n", err)
		fmt.Fprintf(os.Stderr, "Full HTTP response: %v\n", r)
	}
	// response from `GetPrivateResource`: PrivateResourceResponse
	fmt.Fprintf(os.Stdout, "Response from `PrivateResourcesAPI.GetPrivateResource`: %v\n", getResp)

	// update private resource
	addresses = []privateapps.ResourceAddressesInner{*privateapps.NewResourceAddressesInner([]string{"172.16.0.0/32"}, protocolInner)}
	privateResourceRequest.SetResourceAddresses(addresses)

	updateResp, r, err := apiClient.PrivateResourcesAPI.PutPrivateResource(context.Background(), *createResp.ResourceId).PrivateResourceRequest(privateResourceRequest).Execute()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error when calling `PrivateResourcesAPI.PutPrivateResource``: %v\n", err)
		fmt.Fprintf(os.Stderr, "Full HTTP response: %v\n", r)
	}
	// response from `PutPrivateResource`: PrivateResourceResponse
	fmt.Fprintf(os.Stdout, "Response from `PrivateResourcesAPI.PutPrivateResource`: %v\n", updateResp)

	// delete private resource
	delResp, r, err := apiClient.PrivateResourcesAPI.DeletePrivateResource(context.Background(), *createResp.ResourceId).Execute()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error when calling `PrivateResourcesAPI.DeletePrivateResource``: %v\n", err)
		fmt.Fprintf(os.Stderr, "Full HTTP response: %v\n", r)
	}
	// response from `DeletePrivateResource`: string
	fmt.Fprintf(os.Stdout, "Response from `PrivateResourcesAPI.DeletePrivateResource`: %v\n", delResp)

}
