// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Network Tunnel Groups and Regions API

Manage the Secure Access Network Tunnel Groups.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ntg

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// NetworkTunnelGroupsRegionsAPIService NetworkTunnelGroupsRegionsAPI service
type NetworkTunnelGroupsRegionsAPIService service

type ApiListNetworkTunnelGroupRegionsRequest struct {
	ctx context.Context
	ApiService *NetworkTunnelGroupsRegionsAPIService
	filters *FiltersRegionsObject
}

// Filter the regions by one or more properties: &#x60;peerIP&#x60; or &#x60;latitude&#x60; and &#x60;longitude&#x60;.  * **peerIP** - List the regions in ascending order based on the distance of the regions to the location of the given peer IP.   You can only set a public IP for &#x60;peerIP&#x60;. If &#x60;latitude&#x60; and &#x60;longitude&#x60; are provided, &#x60;peerIP&#x60; is ignored. * **latitude** and **longitude** - List the regions in ascending order based on the distance of the regions from the provided coordinates.   When included with a request, set both &#x60;latitude&#x60; and &#x60;longitude&#x60;.  Specify the filters in the JSON format.  Examples:  &#x60;&#x60;&#x60; {   \&quot;peerIP\&quot;: \&quot;25.123.22.10\&quot; } &#x60;&#x60;&#x60;  &#x60;&#x60;&#x60; {   \&quot;latitude\&quot;: \&quot;39.0299604\&quot;,   \&quot;longitude\&quot;: \&quot;39.0299604\&quot; } &#x60;&#x60;&#x60;
func (r ApiListNetworkTunnelGroupRegionsRequest) Filters(filters FiltersRegionsObject) ApiListNetworkTunnelGroupRegionsRequest {
	r.filters = &filters
	return r
}

func (r ApiListNetworkTunnelGroupRegionsRequest) Execute() (*RegionList, *http.Response, error) {
	return r.ApiService.ListNetworkTunnelGroupRegionsExecute(r)
}

/*
ListNetworkTunnelGroupRegions List Regions for Network Tunnel Groups

List the available regions for the Network Tunnel Groups.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiListNetworkTunnelGroupRegionsRequest
*/
func (a *NetworkTunnelGroupsRegionsAPIService) ListNetworkTunnelGroupRegions(ctx context.Context) ApiListNetworkTunnelGroupRegionsRequest {
	return ApiListNetworkTunnelGroupRegionsRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return RegionList
func (a *NetworkTunnelGroupsRegionsAPIService) ListNetworkTunnelGroupRegionsExecute(r ApiListNetworkTunnelGroupRegionsRequest) (*RegionList, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *RegionList
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NetworkTunnelGroupsRegionsAPIService.ListNetworkTunnelGroupRegions")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/regions"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.filters != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "filters", r.filters, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v Error400RegionsError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v Error401
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v Error403
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v Error404
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v Error500
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
