// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Network Tunnel Groups and Regions API

Manage the Secure Access Network Tunnel Groups.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ntg

import (
	"encoding/json"
)

// checks if the Error400BulkStates type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Error400BulkStates{}

// Error400BulkStates struct for Error400BulkStates
type Error400BulkStates struct {
	// Error message explaining the reason for failure.
	Error *string `json:"error,omitempty"`
	// The ID of the request.
	RequestId *string `json:"requestId,omitempty"`
	ValidationErrors *Error400BulkStatesValidationErrors `json:"validationErrors,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Error400BulkStates Error400BulkStates

// NewError400BulkStates instantiates a new Error400BulkStates object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewError400BulkStates() *Error400BulkStates {
	this := Error400BulkStates{}
	return &this
}

// NewError400BulkStatesWithDefaults instantiates a new Error400BulkStates object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewError400BulkStatesWithDefaults() *Error400BulkStates {
	this := Error400BulkStates{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *Error400BulkStates) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Error400BulkStates) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *Error400BulkStates) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *Error400BulkStates) SetError(v string) {
	o.Error = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *Error400BulkStates) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Error400BulkStates) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *Error400BulkStates) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *Error400BulkStates) SetRequestId(v string) {
	o.RequestId = &v
}

// GetValidationErrors returns the ValidationErrors field value if set, zero value otherwise.
func (o *Error400BulkStates) GetValidationErrors() Error400BulkStatesValidationErrors {
	if o == nil || IsNil(o.ValidationErrors) {
		var ret Error400BulkStatesValidationErrors
		return ret
	}
	return *o.ValidationErrors
}

// GetValidationErrorsOk returns a tuple with the ValidationErrors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Error400BulkStates) GetValidationErrorsOk() (*Error400BulkStatesValidationErrors, bool) {
	if o == nil || IsNil(o.ValidationErrors) {
		return nil, false
	}
	return o.ValidationErrors, true
}

// HasValidationErrors returns a boolean if a field has been set.
func (o *Error400BulkStates) HasValidationErrors() bool {
	if o != nil && !IsNil(o.ValidationErrors) {
		return true
	}

	return false
}

// SetValidationErrors gets a reference to the given Error400BulkStatesValidationErrors and assigns it to the ValidationErrors field.
func (o *Error400BulkStates) SetValidationErrors(v Error400BulkStatesValidationErrors) {
	o.ValidationErrors = &v
}

func (o Error400BulkStates) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Error400BulkStates) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if !IsNil(o.ValidationErrors) {
		toSerialize["validationErrors"] = o.ValidationErrors
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Error400BulkStates) UnmarshalJSON(data []byte) (err error) {
	varError400BulkStates := _Error400BulkStates{}

	err = json.Unmarshal(data, &varError400BulkStates)

	if err != nil {
		return err
	}

	*o = Error400BulkStates(varError400BulkStates)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "error")
		delete(additionalProperties, "requestId")
		delete(additionalProperties, "validationErrors")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableError400BulkStates struct {
	value *Error400BulkStates
	isSet bool
}

func (v NullableError400BulkStates) Get() *Error400BulkStates {
	return v.value
}

func (v *NullableError400BulkStates) Set(val *Error400BulkStates) {
	v.value = val
	v.isSet = true
}

func (v NullableError400BulkStates) IsSet() bool {
	return v.isSet
}

func (v *NullableError400BulkStates) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableError400BulkStates(val *Error400BulkStates) *NullableError400BulkStates {
	return &NullableError400BulkStates{value: val, isSet: true}
}

func (v NullableError400BulkStates) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableError400BulkStates) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


