/*
Cisco Secure Access Network Tunnel Groups and Regions API

Manage the Secure Access Network Tunnel Groups.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ntg

import (
	"encoding/json"
)

// checks if the HubsWithStateInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HubsWithStateInner{}

// HubsWithStateInner The properties of the Hub.
type HubsWithStateInner struct {
	// The ID of the Hub.
	Id *int64 `json:"id,omitempty"`
	// Specifies whether the Hub is a primary data center.
	IsPrimary *bool `json:"isPrimary,omitempty"`
	Datacenter *HubsWithStateInnerDatacenter `json:"datacenter,omitempty"`
	Status *HubState `json:"status,omitempty"`
	// The list of the states for the Network Tunnels. The maximum number of items in the list of tunnel states is 10.
	TunnelsStatus []TunnelState `json:"tunnelsStatus,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _HubsWithStateInner HubsWithStateInner

// NewHubsWithStateInner instantiates a new HubsWithStateInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHubsWithStateInner() *HubsWithStateInner {
	this := HubsWithStateInner{}
	return &this
}

// NewHubsWithStateInnerWithDefaults instantiates a new HubsWithStateInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHubsWithStateInnerWithDefaults() *HubsWithStateInner {
	this := HubsWithStateInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *HubsWithStateInner) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HubsWithStateInner) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *HubsWithStateInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *HubsWithStateInner) SetId(v int64) {
	o.Id = &v
}

// GetIsPrimary returns the IsPrimary field value if set, zero value otherwise.
func (o *HubsWithStateInner) GetIsPrimary() bool {
	if o == nil || IsNil(o.IsPrimary) {
		var ret bool
		return ret
	}
	return *o.IsPrimary
}

// GetIsPrimaryOk returns a tuple with the IsPrimary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HubsWithStateInner) GetIsPrimaryOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPrimary) {
		return nil, false
	}
	return o.IsPrimary, true
}

// HasIsPrimary returns a boolean if a field has been set.
func (o *HubsWithStateInner) HasIsPrimary() bool {
	if o != nil && !IsNil(o.IsPrimary) {
		return true
	}

	return false
}

// SetIsPrimary gets a reference to the given bool and assigns it to the IsPrimary field.
func (o *HubsWithStateInner) SetIsPrimary(v bool) {
	o.IsPrimary = &v
}

// GetDatacenter returns the Datacenter field value if set, zero value otherwise.
func (o *HubsWithStateInner) GetDatacenter() HubsWithStateInnerDatacenter {
	if o == nil || IsNil(o.Datacenter) {
		var ret HubsWithStateInnerDatacenter
		return ret
	}
	return *o.Datacenter
}

// GetDatacenterOk returns a tuple with the Datacenter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HubsWithStateInner) GetDatacenterOk() (*HubsWithStateInnerDatacenter, bool) {
	if o == nil || IsNil(o.Datacenter) {
		return nil, false
	}
	return o.Datacenter, true
}

// HasDatacenter returns a boolean if a field has been set.
func (o *HubsWithStateInner) HasDatacenter() bool {
	if o != nil && !IsNil(o.Datacenter) {
		return true
	}

	return false
}

// SetDatacenter gets a reference to the given HubsWithStateInnerDatacenter and assigns it to the Datacenter field.
func (o *HubsWithStateInner) SetDatacenter(v HubsWithStateInnerDatacenter) {
	o.Datacenter = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *HubsWithStateInner) GetStatus() HubState {
	if o == nil || IsNil(o.Status) {
		var ret HubState
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HubsWithStateInner) GetStatusOk() (*HubState, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *HubsWithStateInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given HubState and assigns it to the Status field.
func (o *HubsWithStateInner) SetStatus(v HubState) {
	o.Status = &v
}

// GetTunnelsStatus returns the TunnelsStatus field value if set, zero value otherwise.
func (o *HubsWithStateInner) GetTunnelsStatus() []TunnelState {
	if o == nil || IsNil(o.TunnelsStatus) {
		var ret []TunnelState
		return ret
	}
	return o.TunnelsStatus
}

// GetTunnelsStatusOk returns a tuple with the TunnelsStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HubsWithStateInner) GetTunnelsStatusOk() ([]TunnelState, bool) {
	if o == nil || IsNil(o.TunnelsStatus) {
		return nil, false
	}
	return o.TunnelsStatus, true
}

// HasTunnelsStatus returns a boolean if a field has been set.
func (o *HubsWithStateInner) HasTunnelsStatus() bool {
	if o != nil && !IsNil(o.TunnelsStatus) {
		return true
	}

	return false
}

// SetTunnelsStatus gets a reference to the given []TunnelState and assigns it to the TunnelsStatus field.
func (o *HubsWithStateInner) SetTunnelsStatus(v []TunnelState) {
	o.TunnelsStatus = v
}

func (o HubsWithStateInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HubsWithStateInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IsPrimary) {
		toSerialize["isPrimary"] = o.IsPrimary
	}
	if !IsNil(o.Datacenter) {
		toSerialize["datacenter"] = o.Datacenter
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.TunnelsStatus) {
		toSerialize["tunnelsStatus"] = o.TunnelsStatus
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HubsWithStateInner) UnmarshalJSON(data []byte) (err error) {
	varHubsWithStateInner := _HubsWithStateInner{}

	err = json.Unmarshal(data, &varHubsWithStateInner)

	if err != nil {
		return err
	}

	*o = HubsWithStateInner(varHubsWithStateInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "isPrimary")
		delete(additionalProperties, "datacenter")
		delete(additionalProperties, "status")
		delete(additionalProperties, "tunnelsStatus")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHubsWithStateInner struct {
	value *HubsWithStateInner
	isSet bool
}

func (v NullableHubsWithStateInner) Get() *HubsWithStateInner {
	return v.value
}

func (v *NullableHubsWithStateInner) Set(val *HubsWithStateInner) {
	v.value = val
	v.isSet = true
}

func (v NullableHubsWithStateInner) IsSet() bool {
	return v.isSet
}

func (v *NullableHubsWithStateInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHubsWithStateInner(val *HubsWithStateInner) *NullableHubsWithStateInner {
	return &NullableHubsWithStateInner{value: val, isSet: true}
}

func (v NullableHubsWithStateInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHubsWithStateInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


