/*
Cisco Secure Access Network Tunnel Groups and Regions API

Manage the Secure Access Network Tunnel Groups.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ntg

import (
	"encoding/json"
	"fmt"
)

// checks if the RoutingResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoutingResponse{}

// RoutingResponse The routing information for the network tunnel.  If the routing type is `nat`, then the `data` field is empty. If the routing type is `bgp`, then `data` includes the `asNumber` field. If the routing type is `static`, then `data` includes the `networkCIDRs` field.
type RoutingResponse struct {
	// The type of the route.
	Type string `json:"type"`
	Data RoutingResponseData `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _RoutingResponse RoutingResponse

// NewRoutingResponse instantiates a new RoutingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutingResponse(type_ string, data RoutingResponseData) *RoutingResponse {
	this := RoutingResponse{}
	this.Type = type_
	this.Data = data
	return &this
}

// NewRoutingResponseWithDefaults instantiates a new RoutingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutingResponseWithDefaults() *RoutingResponse {
	this := RoutingResponse{}
	return &this
}

// GetType returns the Type field value
func (o *RoutingResponse) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RoutingResponse) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RoutingResponse) SetType(v string) {
	o.Type = v
}

// GetData returns the Data field value
func (o *RoutingResponse) GetData() RoutingResponseData {
	if o == nil {
		var ret RoutingResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RoutingResponse) GetDataOk() (*RoutingResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RoutingResponse) SetData(v RoutingResponseData) {
	o.Data = v
}

func (o RoutingResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoutingResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RoutingResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRoutingResponse := _RoutingResponse{}

	err = json.Unmarshal(data, &varRoutingResponse)

	if err != nil {
		return err
	}

	*o = RoutingResponse(varRoutingResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRoutingResponse struct {
	value *RoutingResponse
	isSet bool
}

func (v NullableRoutingResponse) Get() *RoutingResponse {
	return v.value
}

func (v *NullableRoutingResponse) Set(val *RoutingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutingResponse(val *RoutingResponse) *NullableRoutingResponse {
	return &NullableRoutingResponse{value: val, isSet: true}
}

func (v NullableRoutingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


