// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Network Tunnel Groups and Regions API

Manage the Secure Access Network Tunnel Groups.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ntg

import (
	"encoding/json"
)

// checks if the Bgp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Bgp{}

// Bgp struct for Bgp
type Bgp struct {
	// The BGP autonomous system (AS) number.
	AsNumber *string `json:"asNumber,omitempty"`
	// The list of BGP peer IP addresses.
	PeerIPs []string `json:"peerIPs,omitempty"`
	// The range of BGP peer addresses.
	PeerRange *string `json:"peerRange,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Bgp Bgp

// NewBgp instantiates a new Bgp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBgp() *Bgp {
	this := Bgp{}
	return &this
}

// NewBgpWithDefaults instantiates a new Bgp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBgpWithDefaults() *Bgp {
	this := Bgp{}
	return &this
}

// GetAsNumber returns the AsNumber field value if set, zero value otherwise.
func (o *Bgp) GetAsNumber() string {
	if o == nil || IsNil(o.AsNumber) {
		var ret string
		return ret
	}
	return *o.AsNumber
}

// GetAsNumberOk returns a tuple with the AsNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bgp) GetAsNumberOk() (*string, bool) {
	if o == nil || IsNil(o.AsNumber) {
		return nil, false
	}
	return o.AsNumber, true
}

// HasAsNumber returns a boolean if a field has been set.
func (o *Bgp) HasAsNumber() bool {
	if o != nil && !IsNil(o.AsNumber) {
		return true
	}

	return false
}

// SetAsNumber gets a reference to the given string and assigns it to the AsNumber field.
func (o *Bgp) SetAsNumber(v string) {
	o.AsNumber = &v
}

// GetPeerIPs returns the PeerIPs field value if set, zero value otherwise.
func (o *Bgp) GetPeerIPs() []string {
	if o == nil || IsNil(o.PeerIPs) {
		var ret []string
		return ret
	}
	return o.PeerIPs
}

// GetPeerIPsOk returns a tuple with the PeerIPs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bgp) GetPeerIPsOk() ([]string, bool) {
	if o == nil || IsNil(o.PeerIPs) {
		return nil, false
	}
	return o.PeerIPs, true
}

// HasPeerIPs returns a boolean if a field has been set.
func (o *Bgp) HasPeerIPs() bool {
	if o != nil && !IsNil(o.PeerIPs) {
		return true
	}

	return false
}

// SetPeerIPs gets a reference to the given []string and assigns it to the PeerIPs field.
func (o *Bgp) SetPeerIPs(v []string) {
	o.PeerIPs = v
}

// GetPeerRange returns the PeerRange field value if set, zero value otherwise.
func (o *Bgp) GetPeerRange() string {
	if o == nil || IsNil(o.PeerRange) {
		var ret string
		return ret
	}
	return *o.PeerRange
}

// GetPeerRangeOk returns a tuple with the PeerRange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bgp) GetPeerRangeOk() (*string, bool) {
	if o == nil || IsNil(o.PeerRange) {
		return nil, false
	}
	return o.PeerRange, true
}

// HasPeerRange returns a boolean if a field has been set.
func (o *Bgp) HasPeerRange() bool {
	if o != nil && !IsNil(o.PeerRange) {
		return true
	}

	return false
}

// SetPeerRange gets a reference to the given string and assigns it to the PeerRange field.
func (o *Bgp) SetPeerRange(v string) {
	o.PeerRange = &v
}

func (o Bgp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Bgp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AsNumber) {
		toSerialize["asNumber"] = o.AsNumber
	}
	if !IsNil(o.PeerIPs) {
		toSerialize["peerIPs"] = o.PeerIPs
	}
	if !IsNil(o.PeerRange) {
		toSerialize["peerRange"] = o.PeerRange
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Bgp) UnmarshalJSON(data []byte) (err error) {
	varBgp := _Bgp{}

	err = json.Unmarshal(data, &varBgp)

	if err != nil {
		return err
	}

	*o = Bgp(varBgp)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "asNumber")
		delete(additionalProperties, "peerIPs")
		delete(additionalProperties, "peerRange")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBgp struct {
	value *Bgp
	isSet bool
}

func (v NullableBgp) Get() *Bgp {
	return v.value
}

func (v *NullableBgp) Set(val *Bgp) {
	v.value = val
	v.isSet = true
}

func (v NullableBgp) IsSet() bool {
	return v.isSet
}

func (v *NullableBgp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBgp(val *Bgp) *NullableBgp {
	return &NullableBgp{value: val, isSet: true}
}

func (v NullableBgp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBgp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


