/*
Cisco Secure Access Network Tunnel Groups and Regions API

Manage the Secure Access Network Tunnel Groups.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ntg

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// Error400ListError - struct for Error400ListError
type Error400ListError struct {
	Error400ListOneOf *Error400ListOneOf
}

// Error400ListOneOfAsError400ListError is a convenience function that returns Error400ListOneOf wrapped in Error400ListError
func Error400ListOneOfAsError400ListError(v *Error400ListOneOf) Error400ListError {
	return Error400ListError{
		Error400ListOneOf: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *Error400ListError) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Error400ListOneOf
	err = newStrictDecoder(data).Decode(&dst.Error400ListOneOf)
	if err == nil {
		jsonError400ListOneOf, _ := json.Marshal(dst.Error400ListOneOf)
		if string(jsonError400ListOneOf) == "{}" { // empty struct
			dst.Error400ListOneOf = nil
		} else {
			if err = validator.Validate(dst.Error400ListOneOf); err != nil {
				dst.Error400ListOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.Error400ListOneOf = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Error400ListOneOf = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Error400ListError)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(Error400ListError)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Error400ListError) MarshalJSON() ([]byte, error) {
	if src.Error400ListOneOf != nil {
		return json.Marshal(&src.Error400ListOneOf)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Error400ListError) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Error400ListOneOf != nil {
		return obj.Error400ListOneOf
	}

	// all schemas are nil
	return nil
}

type NullableError400ListError struct {
	value *Error400ListError
	isSet bool
}

func (v NullableError400ListError) Get() *Error400ListError {
	return v.value
}

func (v *NullableError400ListError) Set(val *Error400ListError) {
	v.value = val
	v.isSet = true
}

func (v NullableError400ListError) IsSet() bool {
	return v.isSet
}

func (v *NullableError400ListError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableError400ListError(val *Error400ListError) *NullableError400ListError {
	return &NullableError400ListError{value: val, isSet: true}
}

func (v NullableError400ListError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableError400ListError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


