// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Network Tunnel Groups and Regions API

Manage the Secure Access Network Tunnel Groups.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ntg

import (
	"encoding/json"
	"time"
)

// checks if the TunnelState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TunnelState{}

// TunnelState The status information of the established Network Tunnel.
type TunnelState struct {
	// The date and time (UTC time with milliseconds) when the state event record was generated.
	Time *time.Time `json:"time,omitempty"`
	// The high-level status of the tunnel: * UP - The tunnel is active. * DOWN - The tunnel is inactive. * FAILED - The tunnel is in a failed state. * UNKNOWN - The current status is unknown and pending updated information.
	Status *string `json:"status,omitempty"`
	// The domain name of the data center.
	Dc *string `json:"dc,omitempty"`
	// The name of the data center.
	DcName *string `json:"dcName,omitempty"`
	// The city and country, or regional location of the data center.
	DcDesc *string `json:"dcDesc,omitempty"`
	// IKE SA State: * CREATED * CONNECTING * ESTABLISHED * PASSIVE * REKEYING * REKEYED * DELETING * DESTROYING
	IkeState *string `json:"ikeState,omitempty"`
	// IPsec state: * CREATED * ROUTED * INSTALLING * INSTALLED * UPDATING * REKEYING * REKEYED * RETRYING * DELETING * DELETED * DESTROYING
	IpsecState *string `json:"ipsecState,omitempty"`
	// The IKE ID of the remote peer.
	PeerId *string `json:"peerId,omitempty"`
	// The IP address of the remote peer.
	PeerIp *string `json:"peerIp,omitempty"`
	// The port of the remote peer.
	PeerPort *string `json:"peerPort,omitempty"`
	// The public IP address assigned to an endpoint device (for example: ISR, Viptela).
	LocalIp *string `json:"localIp,omitempty"`
	// The port on the device.
	LocalPort *string `json:"localPort,omitempty"`
	Ike *TunnelIKEState `json:"ike,omitempty"`
	Ipsec *TunnelIPSecState `json:"ipsec,omitempty"`
	Data *TunnelDataState `json:"data,omitempty"`
	RoutingStats *TunnelRoutingStats `json:"routingStats,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TunnelState TunnelState

// NewTunnelState instantiates a new TunnelState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTunnelState() *TunnelState {
	this := TunnelState{}
	return &this
}

// NewTunnelStateWithDefaults instantiates a new TunnelState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTunnelStateWithDefaults() *TunnelState {
	this := TunnelState{}
	return &this
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *TunnelState) GetTime() time.Time {
	if o == nil || IsNil(o.Time) {
		var ret time.Time
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TunnelState) GetTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *TunnelState) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given time.Time and assigns it to the Time field.
func (o *TunnelState) SetTime(v time.Time) {
	o.Time = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TunnelState) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TunnelState) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TunnelState) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *TunnelState) SetStatus(v string) {
	o.Status = &v
}

// GetDc returns the Dc field value if set, zero value otherwise.
func (o *TunnelState) GetDc() string {
	if o == nil || IsNil(o.Dc) {
		var ret string
		return ret
	}
	return *o.Dc
}

// GetDcOk returns a tuple with the Dc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TunnelState) GetDcOk() (*string, bool) {
	if o == nil || IsNil(o.Dc) {
		return nil, false
	}
	return o.Dc, true
}

// HasDc returns a boolean if a field has been set.
func (o *TunnelState) HasDc() bool {
	if o != nil && !IsNil(o.Dc) {
		return true
	}

	return false
}

// SetDc gets a reference to the given string and assigns it to the Dc field.
func (o *TunnelState) SetDc(v string) {
	o.Dc = &v
}

// GetDcName returns the DcName field value if set, zero value otherwise.
func (o *TunnelState) GetDcName() string {
	if o == nil || IsNil(o.DcName) {
		var ret string
		return ret
	}
	return *o.DcName
}

// GetDcNameOk returns a tuple with the DcName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TunnelState) GetDcNameOk() (*string, bool) {
	if o == nil || IsNil(o.DcName) {
		return nil, false
	}
	return o.DcName, true
}

// HasDcName returns a boolean if a field has been set.
func (o *TunnelState) HasDcName() bool {
	if o != nil && !IsNil(o.DcName) {
		return true
	}

	return false
}

// SetDcName gets a reference to the given string and assigns it to the DcName field.
func (o *TunnelState) SetDcName(v string) {
	o.DcName = &v
}

// GetDcDesc returns the DcDesc field value if set, zero value otherwise.
func (o *TunnelState) GetDcDesc() string {
	if o == nil || IsNil(o.DcDesc) {
		var ret string
		return ret
	}
	return *o.DcDesc
}

// GetDcDescOk returns a tuple with the DcDesc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TunnelState) GetDcDescOk() (*string, bool) {
	if o == nil || IsNil(o.DcDesc) {
		return nil, false
	}
	return o.DcDesc, true
}

// HasDcDesc returns a boolean if a field has been set.
func (o *TunnelState) HasDcDesc() bool {
	if o != nil && !IsNil(o.DcDesc) {
		return true
	}

	return false
}

// SetDcDesc gets a reference to the given string and assigns it to the DcDesc field.
func (o *TunnelState) SetDcDesc(v string) {
	o.DcDesc = &v
}

// GetIkeState returns the IkeState field value if set, zero value otherwise.
func (o *TunnelState) GetIkeState() string {
	if o == nil || IsNil(o.IkeState) {
		var ret string
		return ret
	}
	return *o.IkeState
}

// GetIkeStateOk returns a tuple with the IkeState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TunnelState) GetIkeStateOk() (*string, bool) {
	if o == nil || IsNil(o.IkeState) {
		return nil, false
	}
	return o.IkeState, true
}

// HasIkeState returns a boolean if a field has been set.
func (o *TunnelState) HasIkeState() bool {
	if o != nil && !IsNil(o.IkeState) {
		return true
	}

	return false
}

// SetIkeState gets a reference to the given string and assigns it to the IkeState field.
func (o *TunnelState) SetIkeState(v string) {
	o.IkeState = &v
}

// GetIpsecState returns the IpsecState field value if set, zero value otherwise.
func (o *TunnelState) GetIpsecState() string {
	if o == nil || IsNil(o.IpsecState) {
		var ret string
		return ret
	}
	return *o.IpsecState
}

// GetIpsecStateOk returns a tuple with the IpsecState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TunnelState) GetIpsecStateOk() (*string, bool) {
	if o == nil || IsNil(o.IpsecState) {
		return nil, false
	}
	return o.IpsecState, true
}

// HasIpsecState returns a boolean if a field has been set.
func (o *TunnelState) HasIpsecState() bool {
	if o != nil && !IsNil(o.IpsecState) {
		return true
	}

	return false
}

// SetIpsecState gets a reference to the given string and assigns it to the IpsecState field.
func (o *TunnelState) SetIpsecState(v string) {
	o.IpsecState = &v
}

// GetPeerId returns the PeerId field value if set, zero value otherwise.
func (o *TunnelState) GetPeerId() string {
	if o == nil || IsNil(o.PeerId) {
		var ret string
		return ret
	}
	return *o.PeerId
}

// GetPeerIdOk returns a tuple with the PeerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TunnelState) GetPeerIdOk() (*string, bool) {
	if o == nil || IsNil(o.PeerId) {
		return nil, false
	}
	return o.PeerId, true
}

// HasPeerId returns a boolean if a field has been set.
func (o *TunnelState) HasPeerId() bool {
	if o != nil && !IsNil(o.PeerId) {
		return true
	}

	return false
}

// SetPeerId gets a reference to the given string and assigns it to the PeerId field.
func (o *TunnelState) SetPeerId(v string) {
	o.PeerId = &v
}

// GetPeerIp returns the PeerIp field value if set, zero value otherwise.
func (o *TunnelState) GetPeerIp() string {
	if o == nil || IsNil(o.PeerIp) {
		var ret string
		return ret
	}
	return *o.PeerIp
}

// GetPeerIpOk returns a tuple with the PeerIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TunnelState) GetPeerIpOk() (*string, bool) {
	if o == nil || IsNil(o.PeerIp) {
		return nil, false
	}
	return o.PeerIp, true
}

// HasPeerIp returns a boolean if a field has been set.
func (o *TunnelState) HasPeerIp() bool {
	if o != nil && !IsNil(o.PeerIp) {
		return true
	}

	return false
}

// SetPeerIp gets a reference to the given string and assigns it to the PeerIp field.
func (o *TunnelState) SetPeerIp(v string) {
	o.PeerIp = &v
}

// GetPeerPort returns the PeerPort field value if set, zero value otherwise.
func (o *TunnelState) GetPeerPort() string {
	if o == nil || IsNil(o.PeerPort) {
		var ret string
		return ret
	}
	return *o.PeerPort
}

// GetPeerPortOk returns a tuple with the PeerPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TunnelState) GetPeerPortOk() (*string, bool) {
	if o == nil || IsNil(o.PeerPort) {
		return nil, false
	}
	return o.PeerPort, true
}

// HasPeerPort returns a boolean if a field has been set.
func (o *TunnelState) HasPeerPort() bool {
	if o != nil && !IsNil(o.PeerPort) {
		return true
	}

	return false
}

// SetPeerPort gets a reference to the given string and assigns it to the PeerPort field.
func (o *TunnelState) SetPeerPort(v string) {
	o.PeerPort = &v
}

// GetLocalIp returns the LocalIp field value if set, zero value otherwise.
func (o *TunnelState) GetLocalIp() string {
	if o == nil || IsNil(o.LocalIp) {
		var ret string
		return ret
	}
	return *o.LocalIp
}

// GetLocalIpOk returns a tuple with the LocalIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TunnelState) GetLocalIpOk() (*string, bool) {
	if o == nil || IsNil(o.LocalIp) {
		return nil, false
	}
	return o.LocalIp, true
}

// HasLocalIp returns a boolean if a field has been set.
func (o *TunnelState) HasLocalIp() bool {
	if o != nil && !IsNil(o.LocalIp) {
		return true
	}

	return false
}

// SetLocalIp gets a reference to the given string and assigns it to the LocalIp field.
func (o *TunnelState) SetLocalIp(v string) {
	o.LocalIp = &v
}

// GetLocalPort returns the LocalPort field value if set, zero value otherwise.
func (o *TunnelState) GetLocalPort() string {
	if o == nil || IsNil(o.LocalPort) {
		var ret string
		return ret
	}
	return *o.LocalPort
}

// GetLocalPortOk returns a tuple with the LocalPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TunnelState) GetLocalPortOk() (*string, bool) {
	if o == nil || IsNil(o.LocalPort) {
		return nil, false
	}
	return o.LocalPort, true
}

// HasLocalPort returns a boolean if a field has been set.
func (o *TunnelState) HasLocalPort() bool {
	if o != nil && !IsNil(o.LocalPort) {
		return true
	}

	return false
}

// SetLocalPort gets a reference to the given string and assigns it to the LocalPort field.
func (o *TunnelState) SetLocalPort(v string) {
	o.LocalPort = &v
}

// GetIke returns the Ike field value if set, zero value otherwise.
func (o *TunnelState) GetIke() TunnelIKEState {
	if o == nil || IsNil(o.Ike) {
		var ret TunnelIKEState
		return ret
	}
	return *o.Ike
}

// GetIkeOk returns a tuple with the Ike field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TunnelState) GetIkeOk() (*TunnelIKEState, bool) {
	if o == nil || IsNil(o.Ike) {
		return nil, false
	}
	return o.Ike, true
}

// HasIke returns a boolean if a field has been set.
func (o *TunnelState) HasIke() bool {
	if o != nil && !IsNil(o.Ike) {
		return true
	}

	return false
}

// SetIke gets a reference to the given TunnelIKEState and assigns it to the Ike field.
func (o *TunnelState) SetIke(v TunnelIKEState) {
	o.Ike = &v
}

// GetIpsec returns the Ipsec field value if set, zero value otherwise.
func (o *TunnelState) GetIpsec() TunnelIPSecState {
	if o == nil || IsNil(o.Ipsec) {
		var ret TunnelIPSecState
		return ret
	}
	return *o.Ipsec
}

// GetIpsecOk returns a tuple with the Ipsec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TunnelState) GetIpsecOk() (*TunnelIPSecState, bool) {
	if o == nil || IsNil(o.Ipsec) {
		return nil, false
	}
	return o.Ipsec, true
}

// HasIpsec returns a boolean if a field has been set.
func (o *TunnelState) HasIpsec() bool {
	if o != nil && !IsNil(o.Ipsec) {
		return true
	}

	return false
}

// SetIpsec gets a reference to the given TunnelIPSecState and assigns it to the Ipsec field.
func (o *TunnelState) SetIpsec(v TunnelIPSecState) {
	o.Ipsec = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *TunnelState) GetData() TunnelDataState {
	if o == nil || IsNil(o.Data) {
		var ret TunnelDataState
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TunnelState) GetDataOk() (*TunnelDataState, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *TunnelState) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given TunnelDataState and assigns it to the Data field.
func (o *TunnelState) SetData(v TunnelDataState) {
	o.Data = &v
}

// GetRoutingStats returns the RoutingStats field value if set, zero value otherwise.
func (o *TunnelState) GetRoutingStats() TunnelRoutingStats {
	if o == nil || IsNil(o.RoutingStats) {
		var ret TunnelRoutingStats
		return ret
	}
	return *o.RoutingStats
}

// GetRoutingStatsOk returns a tuple with the RoutingStats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TunnelState) GetRoutingStatsOk() (*TunnelRoutingStats, bool) {
	if o == nil || IsNil(o.RoutingStats) {
		return nil, false
	}
	return o.RoutingStats, true
}

// HasRoutingStats returns a boolean if a field has been set.
func (o *TunnelState) HasRoutingStats() bool {
	if o != nil && !IsNil(o.RoutingStats) {
		return true
	}

	return false
}

// SetRoutingStats gets a reference to the given TunnelRoutingStats and assigns it to the RoutingStats field.
func (o *TunnelState) SetRoutingStats(v TunnelRoutingStats) {
	o.RoutingStats = &v
}

func (o TunnelState) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TunnelState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Dc) {
		toSerialize["dc"] = o.Dc
	}
	if !IsNil(o.DcName) {
		toSerialize["dcName"] = o.DcName
	}
	if !IsNil(o.DcDesc) {
		toSerialize["dcDesc"] = o.DcDesc
	}
	if !IsNil(o.IkeState) {
		toSerialize["ikeState"] = o.IkeState
	}
	if !IsNil(o.IpsecState) {
		toSerialize["ipsecState"] = o.IpsecState
	}
	if !IsNil(o.PeerId) {
		toSerialize["peerId"] = o.PeerId
	}
	if !IsNil(o.PeerIp) {
		toSerialize["peerIp"] = o.PeerIp
	}
	if !IsNil(o.PeerPort) {
		toSerialize["peerPort"] = o.PeerPort
	}
	if !IsNil(o.LocalIp) {
		toSerialize["localIp"] = o.LocalIp
	}
	if !IsNil(o.LocalPort) {
		toSerialize["localPort"] = o.LocalPort
	}
	if !IsNil(o.Ike) {
		toSerialize["ike"] = o.Ike
	}
	if !IsNil(o.Ipsec) {
		toSerialize["ipsec"] = o.Ipsec
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.RoutingStats) {
		toSerialize["routingStats"] = o.RoutingStats
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TunnelState) UnmarshalJSON(data []byte) (err error) {
	varTunnelState := _TunnelState{}

	err = json.Unmarshal(data, &varTunnelState)

	if err != nil {
		return err
	}

	*o = TunnelState(varTunnelState)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "time")
		delete(additionalProperties, "status")
		delete(additionalProperties, "dc")
		delete(additionalProperties, "dcName")
		delete(additionalProperties, "dcDesc")
		delete(additionalProperties, "ikeState")
		delete(additionalProperties, "ipsecState")
		delete(additionalProperties, "peerId")
		delete(additionalProperties, "peerIp")
		delete(additionalProperties, "peerPort")
		delete(additionalProperties, "localIp")
		delete(additionalProperties, "localPort")
		delete(additionalProperties, "ike")
		delete(additionalProperties, "ipsec")
		delete(additionalProperties, "data")
		delete(additionalProperties, "routingStats")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTunnelState struct {
	value *TunnelState
	isSet bool
}

func (v NullableTunnelState) Get() *TunnelState {
	return v.value
}

func (v *NullableTunnelState) Set(val *TunnelState) {
	v.value = val
	v.isSet = true
}

func (v NullableTunnelState) IsSet() bool {
	return v.isSet
}

func (v *NullableTunnelState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTunnelState(val *TunnelState) *NullableTunnelState {
	return &NullableTunnelState{value: val, isSet: true}
}

func (v NullableTunnelState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTunnelState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


