// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Network Tunnel Groups and Regions API

Manage the Secure Access Network Tunnel Groups.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ntg

import (
	"encoding/json"
	"time"
)

// checks if the HubStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HubStatus{}

// HubStatus The properties of a Hub for the Network Tunnel Group.
type HubStatus struct {
	// The status of the hub.
	Status *string `json:"status,omitempty"`
	// The date and time (timestamp) when the hub status was last reported.
	Time *time.Time `json:"time,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _HubStatus HubStatus

// NewHubStatus instantiates a new HubStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHubStatus() *HubStatus {
	this := HubStatus{}
	return &this
}

// NewHubStatusWithDefaults instantiates a new HubStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHubStatusWithDefaults() *HubStatus {
	this := HubStatus{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *HubStatus) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HubStatus) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *HubStatus) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *HubStatus) SetStatus(v string) {
	o.Status = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *HubStatus) GetTime() time.Time {
	if o == nil || IsNil(o.Time) {
		var ret time.Time
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HubStatus) GetTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *HubStatus) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given time.Time and assigns it to the Time field.
func (o *HubStatus) SetTime(v time.Time) {
	o.Time = &v
}

func (o HubStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HubStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HubStatus) UnmarshalJSON(data []byte) (err error) {
	varHubStatus := _HubStatus{}

	err = json.Unmarshal(data, &varHubStatus)

	if err != nil {
		return err
	}

	*o = HubStatus(varHubStatus)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "time")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHubStatus struct {
	value *HubStatus
	isSet bool
}

func (v NullableHubStatus) Get() *HubStatus {
	return v.value
}

func (v *NullableHubStatus) Set(val *HubStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableHubStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableHubStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHubStatus(val *HubStatus) *NullableHubStatus {
	return &NullableHubStatus{value: val, isSet: true}
}

func (v NullableHubStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHubStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


