openapi: 3.0.1
info:
  contact:
    name: Cloud Security Developer Community
  description: "Create and manage the access rules, rule settings, and application\
    \ lists."
  title: "Cisco Secure Access Rules, Rule Settings, and Application Lists APIs"
  version: 1.0.0
servers:
- url: "https://api.sse.cisco.com/{basePath}"
  variables:
    basePath:
      default: policies/v2
security:
- oauthFlow: []
tags:
- description: The API endpoints that manage the access rules for the organization.
  name: Access Rules
- description: The API endpoints that manage the rule settings and defaults on the
    access rules.
  name: Rule Settings and Defaults
- description: The API endpoints that manage the internet application lists for the
    organization.
  name: Application Lists
- name: Secure Access
paths:
  /applicationLists:
    get:
      description: Get the application lists and the number of application lists for
        the organization.
      operationId: getApplicationLists
      security:
      - oauthFlow:
        - policies.applicationlists:read
      summary: Get Application Lists
      tags:
      - Application Lists
    post:
      description: Create an application list for the organization.
      operationId: createApplicationList
      security:
      - oauthFlow:
        - policies.applicationlists:write
      summary: Create Application List
      tags:
      - Application Lists
  /applicationLists/{applicationListId}:
    delete:
      description: Delete the application list from the organization.
      operationId: deleteApplicationList
      security:
      - oauthFlow:
        - policies.applicationlists:write
      summary: Delete Application List
      tags:
      - Application Lists
    get:
      description: Get the properties of an application list.
      operationId: getApplicationList
      security:
      - oauthFlow:
        - policies.applicationlists:read
      summary: Get Application List
      tags:
      - Application Lists
    put:
      description: Update the properties on the application list.
      operationId: putApplicationList
      security:
      - oauthFlow:
        - policies.applicationlists:write
      summary: Update Application List
      tags:
      - Application Lists
  /applications/usage:
    get:
      description: Get the list of application information for the application lists.
      operationId: updateUsageApplications
      security:
      - oauthFlow:
        - policies.applicationlists:read
      summary: Get Usage of Applications
      tags:
      - Application Lists
  /settings:
    get:
      description: Get the global policy settings and rule defaults for the organization.
      operationId: getPolicySettings
      security:
      - oauthFlow:
        - policies.settings:read
      summary: Get Rule Defaults and Global Policy Settings
      tags:
      - Rule Settings and Defaults
    put:
      description: Update the rule defaults and global policy settings.
      operationId: putPolicySettings
      security:
      - oauthFlow:
        - policies.settings:write
      summary: Update Rule Defaults and Global Policy Settings
      tags:
      - Rule Settings and Defaults
  /settings/{settingName}:
    get:
      description: Get the policy setting identified by the setting name.
      operationId: getPolicySetting
      security:
      - oauthFlow:
        - policies.settings:read
      summary: Get Policy Setting
      tags:
      - Rule Settings and Defaults
    put:
      description: Update the policy setting.
      operationId: putPolicySetting
      security:
      - oauthFlow:
        - policies.settings:write
      summary: Update Policy Setting
      tags:
      - Rule Settings and Defaults
  /settingTypes:
    get:
      description: List the policy setting types.
      operationId: getPolicySettingTypes
      security:
      - oauthFlow:
        - policies.settings:read
      summary: List Policy Setting Types
      tags:
      - Rule Settings and Defaults
  /settingTypes/{settingName}:
    get:
      description: Get the type of the policy setting.
      operationId: getSettingTypesByName
      security:
      - oauthFlow:
        - policies.settings:read
      summary: Get Policy Setting Type
      tags:
      - Rule Settings and Defaults
  /rules:
    get:
      description: List the rules in the policy for the organization.
      operationId: listRules
      security:
      - oauthFlow:
        - policies.rules:read
      summary: List Rules
      tags:
      - Access Rules
    post:
      description: Create a rule on the policy for the organization.
      operationId: addRule
      security:
      - oauthFlow:
        - policies.rules:write
      summary: Create Rule
      tags:
      - Access Rules
    put:
      description: Enable or disable the rules on the policy.
      operationId: putRules
      security:
      - oauthFlow:
        - policies.rules:write
      summary: Enable Rules
      tags:
      - Access Rules
  /rules/{ruleId}:
    delete:
      description: Delete a rule on the policy for the organization.
      operationId: deleteRule
      security:
      - oauthFlow:
        - policies.rules:write
      summary: Delete Rule
      tags:
      - Access Rules
    get:
      description: Get the details about the rule.
      operationId: getRule
      security:
      - oauthFlow:
        - policies.rules:read
      summary: Get Rule
      tags:
      - Access Rules
    put:
      description: Update the properties on the rule.
      operationId: putRule
      security:
      - oauthFlow:
        - policies.rules:write
      summary: Update Rule
      tags:
      - Access Rules
  /geolocations:
    get:
      description: |-
        List the regional information for the continents and countries.
        You can use the country code to create a block on the traffic defined in an internet access rule.
      operationId: getRegionalLocations
      security:
      - oauthFlow:
        - policies.rules:read
      summary: List GeoLocations
      tags:
      - Access Rules
components:
  securitySchemes:
    oauthFlow:
      description: client credential flow
      flows:
        clientCredentials:
          scopes:
            policies.applicationlists:write: Write policies application lists
            policies.applicationlists:read: Read policies application lists
            policies.settings:write: Write policies global rule settings
            policies.settings:read: Read policies global rule settings
            policies.rules:read: Read policies access rules
            policies.rules:write: Write policies access rules
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
