/*
Cisco Secure Access Networks API

Manage the networks registered in your organization.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package networks

import (
	"encoding/json"
)

// checks if the UpdateNetwork403Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateNetwork403Response{}

// UpdateNetwork403Response struct for UpdateNetwork403Response
type UpdateNetwork403Response struct {
	// HTTP status code
	StatusCode *int64 `json:"statusCode,omitempty"`
	// Shorthand error message
	Error *string `json:"error,omitempty"`
	// Detailed error message
	Message *string `json:"message,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateNetwork403Response UpdateNetwork403Response

// NewUpdateNetwork403Response instantiates a new UpdateNetwork403Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateNetwork403Response() *UpdateNetwork403Response {
	this := UpdateNetwork403Response{}
	return &this
}

// NewUpdateNetwork403ResponseWithDefaults instantiates a new UpdateNetwork403Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNetwork403ResponseWithDefaults() *UpdateNetwork403Response {
	this := UpdateNetwork403Response{}
	return &this
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *UpdateNetwork403Response) GetStatusCode() int64 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int64
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetwork403Response) GetStatusCodeOk() (*int64, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *UpdateNetwork403Response) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int64 and assigns it to the StatusCode field.
func (o *UpdateNetwork403Response) SetStatusCode(v int64) {
	o.StatusCode = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *UpdateNetwork403Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetwork403Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *UpdateNetwork403Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *UpdateNetwork403Response) SetError(v string) {
	o.Error = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UpdateNetwork403Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetwork403Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UpdateNetwork403Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UpdateNetwork403Response) SetMessage(v string) {
	o.Message = &v
}

func (o UpdateNetwork403Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateNetwork403Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StatusCode) {
		toSerialize["statusCode"] = o.StatusCode
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateNetwork403Response) UnmarshalJSON(data []byte) (err error) {
	varUpdateNetwork403Response := _UpdateNetwork403Response{}

	err = json.Unmarshal(data, &varUpdateNetwork403Response)

	if err != nil {
		return err
	}

	*o = UpdateNetwork403Response(varUpdateNetwork403Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "statusCode")
		delete(additionalProperties, "error")
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateNetwork403Response struct {
	value *UpdateNetwork403Response
	isSet bool
}

func (v NullableUpdateNetwork403Response) Get() *UpdateNetwork403Response {
	return v.value
}

func (v *NullableUpdateNetwork403Response) Set(val *UpdateNetwork403Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNetwork403Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNetwork403Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNetwork403Response(val *UpdateNetwork403Response) *NullableUpdateNetwork403Response {
	return &NullableUpdateNetwork403Response{value: val, isSet: true}
}

func (v NullableUpdateNetwork403Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNetwork403Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


