// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Resource Connector Groups and Resource Connectors API

Manage the properties of the Resource Connector Groups and Resource Connectors in the organization. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resconn

import (
	"encoding/json"
)

// checks if the GetConnectorGroup400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetConnectorGroup400Response{}

// GetConnectorGroup400Response struct for GetConnectorGroup400Response
type GetConnectorGroup400Response struct {
	// Error message explaining the reason for failure.
	Error *string `json:"error,omitempty"`
	// The ID of the request.
	RequestId *string `json:"requestId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetConnectorGroup400Response GetConnectorGroup400Response

// NewGetConnectorGroup400Response instantiates a new GetConnectorGroup400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetConnectorGroup400Response() *GetConnectorGroup400Response {
	this := GetConnectorGroup400Response{}
	return &this
}

// NewGetConnectorGroup400ResponseWithDefaults instantiates a new GetConnectorGroup400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetConnectorGroup400ResponseWithDefaults() *GetConnectorGroup400Response {
	this := GetConnectorGroup400Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GetConnectorGroup400Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectorGroup400Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GetConnectorGroup400Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *GetConnectorGroup400Response) SetError(v string) {
	o.Error = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *GetConnectorGroup400Response) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectorGroup400Response) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *GetConnectorGroup400Response) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *GetConnectorGroup400Response) SetRequestId(v string) {
	o.RequestId = &v
}

func (o GetConnectorGroup400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetConnectorGroup400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetConnectorGroup400Response) UnmarshalJSON(data []byte) (err error) {
	varGetConnectorGroup400Response := _GetConnectorGroup400Response{}

	err = json.Unmarshal(data, &varGetConnectorGroup400Response)

	if err != nil {
		return err
	}

	*o = GetConnectorGroup400Response(varGetConnectorGroup400Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "error")
		delete(additionalProperties, "requestId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetConnectorGroup400Response struct {
	value *GetConnectorGroup400Response
	isSet bool
}

func (v NullableGetConnectorGroup400Response) Get() *GetConnectorGroup400Response {
	return v.value
}

func (v *NullableGetConnectorGroup400Response) Set(val *GetConnectorGroup400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetConnectorGroup400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetConnectorGroup400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetConnectorGroup400Response(val *GetConnectorGroup400Response) *NullableGetConnectorGroup400Response {
	return &NullableGetConnectorGroup400Response{value: val, isSet: true}
}

func (v NullableGetConnectorGroup400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetConnectorGroup400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


