// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Resource Connector Groups and Resource Connectors API

Manage the properties of the Resource Connector Groups and Resource Connectors in the organization. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resconn

import (
	"encoding/json"
)

// checks if the CreateConnectorGroup409Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateConnectorGroup409Response{}

// CreateConnectorGroup409Response struct for CreateConnectorGroup409Response
type CreateConnectorGroup409Response struct {
	// Error message explaining the reason for failure.
	Error *string `json:"error,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateConnectorGroup409Response CreateConnectorGroup409Response

// NewCreateConnectorGroup409Response instantiates a new CreateConnectorGroup409Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateConnectorGroup409Response() *CreateConnectorGroup409Response {
	this := CreateConnectorGroup409Response{}
	return &this
}

// NewCreateConnectorGroup409ResponseWithDefaults instantiates a new CreateConnectorGroup409Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateConnectorGroup409ResponseWithDefaults() *CreateConnectorGroup409Response {
	this := CreateConnectorGroup409Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *CreateConnectorGroup409Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateConnectorGroup409Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *CreateConnectorGroup409Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *CreateConnectorGroup409Response) SetError(v string) {
	o.Error = &v
}

func (o CreateConnectorGroup409Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateConnectorGroup409Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateConnectorGroup409Response) UnmarshalJSON(data []byte) (err error) {
	varCreateConnectorGroup409Response := _CreateConnectorGroup409Response{}

	err = json.Unmarshal(data, &varCreateConnectorGroup409Response)

	if err != nil {
		return err
	}

	*o = CreateConnectorGroup409Response(varCreateConnectorGroup409Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "error")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateConnectorGroup409Response struct {
	value *CreateConnectorGroup409Response
	isSet bool
}

func (v NullableCreateConnectorGroup409Response) Get() *CreateConnectorGroup409Response {
	return v.value
}

func (v *NullableCreateConnectorGroup409Response) Set(val *CreateConnectorGroup409Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateConnectorGroup409Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateConnectorGroup409Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateConnectorGroup409Response(val *CreateConnectorGroup409Response) *NullableCreateConnectorGroup409Response {
	return &NullableCreateConnectorGroup409Response{value: val, isSet: true}
}

func (v NullableCreateConnectorGroup409Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateConnectorGroup409Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


