/*
Cisco Secure Access Destination Lists API

Create and manage destination lists and network destinations.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package destinationlists

import (
	"encoding/json"
)

// checks if the ServerError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerError{}

// ServerError Internal Server Error
type ServerError struct {
	// HTTP status code
	StatusCode *int64 `json:"statusCode,omitempty"`
	// The server can not process the request.
	Error *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
	TxId *string `json:"txId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ServerError ServerError

// NewServerError instantiates a new ServerError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerError() *ServerError {
	this := ServerError{}
	return &this
}

// NewServerErrorWithDefaults instantiates a new ServerError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerErrorWithDefaults() *ServerError {
	this := ServerError{}
	return &this
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *ServerError) GetStatusCode() int64 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int64
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerError) GetStatusCodeOk() (*int64, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *ServerError) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int64 and assigns it to the StatusCode field.
func (o *ServerError) SetStatusCode(v int64) {
	o.StatusCode = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ServerError) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerError) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ServerError) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *ServerError) SetError(v string) {
	o.Error = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ServerError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ServerError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ServerError) SetMessage(v string) {
	o.Message = &v
}

// GetTxId returns the TxId field value if set, zero value otherwise.
func (o *ServerError) GetTxId() string {
	if o == nil || IsNil(o.TxId) {
		var ret string
		return ret
	}
	return *o.TxId
}

// GetTxIdOk returns a tuple with the TxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerError) GetTxIdOk() (*string, bool) {
	if o == nil || IsNil(o.TxId) {
		return nil, false
	}
	return o.TxId, true
}

// HasTxId returns a boolean if a field has been set.
func (o *ServerError) HasTxId() bool {
	if o != nil && !IsNil(o.TxId) {
		return true
	}

	return false
}

// SetTxId gets a reference to the given string and assigns it to the TxId field.
func (o *ServerError) SetTxId(v string) {
	o.TxId = &v
}

func (o ServerError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StatusCode) {
		toSerialize["statusCode"] = o.StatusCode
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.TxId) {
		toSerialize["txId"] = o.TxId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServerError) UnmarshalJSON(data []byte) (err error) {
	varServerError := _ServerError{}

	err = json.Unmarshal(data, &varServerError)

	if err != nil {
		return err
	}

	*o = ServerError(varServerError)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "statusCode")
		delete(additionalProperties, "error")
		delete(additionalProperties, "message")
		delete(additionalProperties, "txId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServerError struct {
	value *ServerError
	isSet bool
}

func (v NullableServerError) Get() *ServerError {
	return v.value
}

func (v *NullableServerError) Set(val *ServerError) {
	v.value = val
	v.isSet = true
}

func (v NullableServerError) IsSet() bool {
	return v.isSet
}

func (v *NullableServerError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerError(val *ServerError) *NullableServerError {
	return &NullableServerError{value: val, isSet: true}
}

func (v NullableServerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


