/*
Cisco Secure Access Destination Lists API

Create and manage destination lists and destinations.

API version: 2.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package destinationlists

import (
	"encoding/json"
	"fmt"
)

// checks if the DestinationListPatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DestinationListPatch{}

// DestinationListPatch Update the name of the destination list.
type DestinationListPatch struct {
	// The name of the destination list.
	Name string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _DestinationListPatch DestinationListPatch

// NewDestinationListPatch instantiates a new DestinationListPatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDestinationListPatch(name string) *DestinationListPatch {
	this := DestinationListPatch{}
	this.Name = name
	return &this
}

// NewDestinationListPatchWithDefaults instantiates a new DestinationListPatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDestinationListPatchWithDefaults() *DestinationListPatch {
	this := DestinationListPatch{}
	return &this
}

// GetName returns the Name field value
func (o *DestinationListPatch) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DestinationListPatch) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DestinationListPatch) SetName(v string) {
	o.Name = v
}

func (o DestinationListPatch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DestinationListPatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DestinationListPatch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDestinationListPatch := _DestinationListPatch{}

	err = json.Unmarshal(data, &varDestinationListPatch)

	if err != nil {
		return err
	}

	*o = DestinationListPatch(varDestinationListPatch)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDestinationListPatch struct {
	value *DestinationListPatch
	isSet bool
}

func (v NullableDestinationListPatch) Get() *DestinationListPatch {
	return v.value
}

func (v *NullableDestinationListPatch) Set(val *DestinationListPatch) {
	v.value = val
	v.isSet = true
}

func (v NullableDestinationListPatch) IsSet() bool {
	return v.isSet
}

func (v *NullableDestinationListPatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDestinationListPatch(val *DestinationListPatch) *NullableDestinationListPatch {
	return &NullableDestinationListPatch{value: val, isSet: true}
}

func (v NullableDestinationListPatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDestinationListPatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


