// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Destination Lists API

Create and manage destination lists and network destinations.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package destinationlists

import (
	"encoding/json"
	"fmt"
)

// checks if the DestinationListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DestinationListResponse{}

// DestinationListResponse The status and properties of the destination lists.
type DestinationListResponse struct {
	Status Status `json:"status"`
	Data DestinationListObject `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _DestinationListResponse DestinationListResponse

// NewDestinationListResponse instantiates a new DestinationListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDestinationListResponse(status Status, data DestinationListObject) *DestinationListResponse {
	this := DestinationListResponse{}
	this.Status = status
	this.Data = data
	return &this
}

// NewDestinationListResponseWithDefaults instantiates a new DestinationListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDestinationListResponseWithDefaults() *DestinationListResponse {
	this := DestinationListResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *DestinationListResponse) GetStatus() Status {
	if o == nil {
		var ret Status
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *DestinationListResponse) GetStatusOk() (*Status, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *DestinationListResponse) SetStatus(v Status) {
	o.Status = v
}

// GetData returns the Data field value
func (o *DestinationListResponse) GetData() DestinationListObject {
	if o == nil {
		var ret DestinationListObject
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DestinationListResponse) GetDataOk() (*DestinationListObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DestinationListResponse) SetData(v DestinationListObject) {
	o.Data = v
}

func (o DestinationListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DestinationListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DestinationListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDestinationListResponse := _DestinationListResponse{}

	err = json.Unmarshal(data, &varDestinationListResponse)

	if err != nil {
		return err
	}

	*o = DestinationListResponse(varDestinationListResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDestinationListResponse struct {
	value *DestinationListResponse
	isSet bool
}

func (v NullableDestinationListResponse) Get() *DestinationListResponse {
	return v.value
}

func (v *NullableDestinationListResponse) Set(val *DestinationListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDestinationListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDestinationListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDestinationListResponse(val *DestinationListResponse) *NullableDestinationListResponse {
	return &NullableDestinationListResponse{value: val, isSet: true}
}

func (v NullableDestinationListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDestinationListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


