// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Destination Lists

Testing DestinationListsAPI

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"

	"github.com/CiscoDevNet/go-ciscosecureaccess/client"
	"github.com/CiscoDevNet/go-ciscosecureaccess/destinationlists"
)

func main() {

	// List existing destionation lists
	auth := context.Background()
	factory := client.SSEClientFactory{KeyId: os.Getenv("API_KEY_ID"), KeySecret: os.Getenv("API_KEY_SECRET")}
	apiClient := factory.GetDestinationListsClient(auth)
	_, httpRes, err := apiClient.DestinationListsAPI.GetDestinationLists(auth).Execute()
	if err != nil {

		fmt.Fprintf(os.Stdout, "HTTP Response: %v\n", httpRes)
		fmt.Fprintf(os.Stdout, "Err: %s\n", err)
	}

	// Create a new destionation lists
	//destination := destinationlists.DestinationObject{Comment: "foo", Type: "domain", Destination: "localhost.com" }
	destination_comment := "foo"
	destination_type := destinationlists.DOMAIN
	destination_address := "localhost.com"
	create_inner := destinationlists.DestinationListCreateDestinationsInner{Comment: &destination_comment, Type: &destination_type, Destination: &destination_address}
	var list_bundle_type destinationlists.BundleTypeId = 2
	create_request := destinationlists.DestinationListCreate{Access: "none", IsGlobal: false, Name: "clientTest", BundleTypeId: &list_bundle_type, Destinations: []destinationlists.DestinationListCreateDestinationsInner{create_inner}}
	create_resp, httpRes, err := apiClient.DestinationListsAPI.CreateDestinationList(context.Background()).DestinationListCreate(create_request).Execute()
	if err != nil {
		fmt.Fprintf(os.Stdout, "HTTP Response: %v\n", httpRes)
		fmt.Fprintf(os.Stdout, "Err: %s\n", err)
	}
	destination_string, _ := create_resp.Data.MarshalJSON()
	fmt.Fprintf(os.Stdout, "Created list: %s", destination_string)

	newDestResp, httpRes, err := apiClient.DestinationsAPI.GetDestinations(auth, create_resp.Data.Id).Execute()
	update_dests, _ := json.Marshal(newDestResp.Data)
	fmt.Fprintf(os.Stdout, "Created destinations: %s\n", update_dests)
	// Update new destionation lists

	payload := destinationlists.DestinationListPatch{Name: "bar"}
	_, httpRes, err = apiClient.DestinationListsAPI.UpdateDestinationLists(context.Background(), create_resp.Data.Id).DestinationListPatch(payload).Execute()
	if err != nil {
		fmt.Fprintf(os.Stdout, "HTTP Response: %v\n", httpRes)
		fmt.Fprintf(os.Stdout, "Err: %s\n", err)
	}

	destinationCreateObject := []destinationlists.DestinationCreateObject{*destinationlists.NewDestinationCreateObject("cisco.com")}
	_, httpRes, err = apiClient.DestinationsAPI.CreateDestinations(context.Background(), create_resp.Data.Id).DestinationCreateObject(destinationCreateObject).Execute()
	if err != nil {
		fmt.Fprintf(os.Stdout, "HTTP Response: %v\n", httpRes)
		fmt.Fprintf(os.Stdout, "Err: %s\n", err)
	}

	// Get destination
	readResp, httpRes, err := apiClient.DestinationListsAPI.GetDestinationList(auth, create_resp.Data.Id).Execute()
	if err != nil {
		fmt.Fprintf(os.Stdout, "HTTP Response: %v\n", httpRes)
		fmt.Fprintf(os.Stdout, "Err: %s\n", err)
	}
	update_string, _ := readResp.Data.MarshalJSON()
	fmt.Fprintf(os.Stdout, "Updated list: %s\n", update_string)

	destResp, httpRes, err := apiClient.DestinationsAPI.GetDestinations(auth, create_resp.Data.Id).Execute()
	if err != nil {
		fmt.Fprintf(os.Stdout, "HTTP Response: %v\n", httpRes)
		fmt.Fprintf(os.Stdout, "Err: %s\n", err)
	}
	for _, d := range destResp.Data {
		fmt.Fprintf(os.Stdout, "Dest: %+v", d.Destination)
	}
	//update_dests, _ = json.Marshal(destResp.Data)
	//fmt.Fprintf(os.Stdout, "Updated destinations: %+v\n", destResp.Data)

	// Delete new destionation lists
	_, httpRes, err = apiClient.DestinationListsAPI.DeleteDestinationList(auth, create_resp.Data.Id).Execute()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error when calling `AccessPoliciesAPI.DeleteSSERule``: %v\n", err)
		fmt.Fprintf(os.Stderr, "Full HTTP response: %v\n", httpRes)
	}
}
