openapi: 3.0.1
info:
  contact:
    name: Cloud Security Developer Community
  description: Manage the Private Resources and Resource Groups in the organization.
  title: Cisco Secure Access Private Resources and Resource Groups API
  version: 1.0.0
servers:
- url: "https://api.sse.cisco.com/{basePath}"
  variables:
    basePath:
      default: policies/v2
security:
- oauthFlow: []
tags:
- description: The Secure Access Private Resource Groups
  name: Resource Groups
- description: The Secure Access Private Resources
  name: Private Resources
paths:
  /privateResourceGroups:
    get:
      description: List the Private Resource Groups for the organization.
      operationId: listResourceGroups
      security:
      - oauthFlow:
        - policies.privateresourcegroups:read
      summary: List Resource Groups
      tags:
      - Resource Groups
    post:
      description: |-
        Create a Private Resource Group for the organization.
        You can create a maximum of 1000 Private Resource Groups.
      operationId: addPrivateResourceGroup
      security:
      - oauthFlow:
        - policies.privateresourcegroups:write
      summary: Create Resource Group
      tags:
      - Resource Groups
  /privateResourceGroups/{id}:
    delete:
      description: |-
        Delete the Private Resource Group from the organization.
        Before deleting the Private Resource Group, Secure Access removes the Private Resources
        from the Private Resource Group.
      operationId: deletePrivateResourceGroup
      security:
      - oauthFlow:
        - policies.privateresourcegroups:write
      summary: Delete Resource Group
      tags:
      - Resource Groups
    get:
      description: Get the details about a Private Resource Group.
      operationId: getPrivateResourceGroup
      security:
      - oauthFlow:
        - policies.privateresourcegroups:read
      summary: Get Resource Group
      tags:
      - Resource Groups
    put:
      description: Update the `name` and `description` properties on the Private Resource
        Group.
      operationId: putPrivateResourceGroup
      security:
      - oauthFlow:
        - policies.privateresourcegroups:write
      summary: Update Resource Group
      tags:
      - Resource Groups
  /privateResources:
    get:
      description: List the Private Resources for the organization.
      operationId: listPrivateResources
      security:
      - oauthFlow:
        - policies.privateresources:read
      summary: List Private Resources
      tags:
      - Private Resources
    post:
      description: |-
        Create a Private Resource for the organization. You can add at most 1000 Private Resources to an organization.
        When you add a Private Resource that is enabled for Zero Trust Access, the private applications are automatically
        managed by the Zero Trust Access service.
      operationId: addPrivateResource
      security:
      - oauthFlow:
        - policies.privateresources:write
      summary: Create Private Resource
      tags:
      - Private Resources
  /privateResources/{id}:
    delete:
      description: |-
        Delete a Private Resource. Remove the Private Resource from any Private Resource Groups before deleting the resource.
        If the Private Resource is the only resource in your organization's Private Resource Groups,
        then Secure Access also removes the Private Resource Groups.
      operationId: deletePrivateResource
      security:
      - oauthFlow:
        - policies.privateresources:write
      summary: Delete Private Resource
      tags:
      - Private Resources
    get:
      description: Get the details about a Private Resource.
      operationId: getPrivateResource
      security:
      - oauthFlow:
        - policies.privateresources:read
      summary: Get Private Resource
      tags:
      - Private Resources
    put:
      description: |-
        Update the properties on a Private Resource.
        You can set the following Private Resource properties: `name`, `description`, `resourceAddresses`, `dnsServerId`, `certificateId`,
        `protocol`, `sni`, and `sslVerificationEnabled`.
      operationId: putPrivateResource
      security:
      - oauthFlow:
        - policies.privateresources:write
      summary: Update Private Resource
      tags:
      - Private Resources
components:
  securitySchemes:
    oauthFlow:
      description: The client credential flow.
      flows:
        clientCredentials:
          scopes:
            policies.privateresourcegroups:read: Read the Private Resource Groups
              resources
            policies.privateresourcegroups:write: Write the Private Resource Groups
              resources
            policies.privateresources:read: Read the Private Resources resources
            policies.privateresources:write: Write the Private Resources resources
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
