/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// OrganizationRequestsByTimerangeAndCategoryAPIService OrganizationRequestsByTimerangeAndCategoryAPI service
type OrganizationRequestsByTimerangeAndCategoryAPIService service

type ApiGetRequestsByTimerangeAndCategoryRequest struct {
	ctx context.Context
	ApiService *OrganizationRequestsByTimerangeAndCategoryAPIService
	from *string
	to *string
	limit *int64
	offset *int64
	domains *string
	urls *string
	categories *string
	policycategories *string
	ip *string
	identityids *string
	identitytypes *string
	applicationid *string
	verdict *string
	securityoverridden *bool
	bundleid *int64
	threats *string
	threattypes *string
	ampdisposition *string
	antivirusthreats *string
	timerange *string
	datalosspreventionstate *string
	filternoisydomains *bool
	timezone *string
}

// A timestamp or relative time string (for example: &#39;-1days&#39;). Filter for data that appears after this time.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) From(from string) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.from = &from
	return r
}

// A timestamp or relative time string (for example: &#39;now&#39;). Filter for data that appears before this time.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) To(to string) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.to = &to
	return r
}

// The maximum number of records to return from the collection.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Limit(limit int64) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.limit = &limit
	return r
}

// A number that represents an index in the collection.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Offset(offset int64) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.offset = &offset
	return r
}

// A domain name or comma-delimited list of domain name.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Domains(domains string) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.domains = &domains
	return r
}

// A URL or comma-delimited list of URL.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Urls(urls string) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.urls = &urls
	return r
}

// A category ID or comma-delimited list of category ID.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Categories(categories string) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.categories = &categories
	return r
}

// A category ID or comma-delimited list of category ID. Filter the request by the categories that trigger a policy.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Policycategories(policycategories string) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.policycategories = &policycategories
	return r
}

// An IP address.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Ip(ip string) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.ip = &ip
	return r
}

// An identity ID or comma-delimited list of identity IDs.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Identityids(identityids string) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.identityids = &identityids
	return r
}

// An identity type or comma-delimited list of identity types.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Identitytypes(identitytypes string) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.identitytypes = &identitytypes
	return r
}

// The ID of the application.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Applicationid(applicationid string) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.applicationid = &applicationid
	return r
}

// A string or comma-delimited string that describes whether the traffic can reach the destination.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Verdict(verdict string) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.verdict = &verdict
	return r
}

// Specify whether to filter on requests that override security.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Securityoverridden(securityoverridden bool) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.securityoverridden = &securityoverridden
	return r
}

// A proxy bundle ID.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Bundleid(bundleid int64) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.bundleid = &bundleid
	return r
}

// A threat name or comma-delimited list of threat names.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Threats(threats string) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.threats = &threats
	return r
}

// A threat type or comma-delimited list of threat types.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Threattypes(threattypes string) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.threattypes = &threattypes
	return r
}

// An AMP disposition string or a comma-delimited list of AMP disposition strings.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Ampdisposition(ampdisposition string) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.ampdisposition = &ampdisposition
	return r
}

// A threat name or comma-delimited list of threat names.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Antivirusthreats(antivirusthreats string) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.antivirusthreats = &antivirusthreats
	return r
}

// A string that represents a range of time. If the header is not set, the header value defaults to &#x60;hour&#x60;.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Timerange(timerange string) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.timerange = &timerange
	return r
}

// A string that describes the status of a destination. Filter for requests that are blocked by the DLP layer security.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Datalosspreventionstate(datalosspreventionstate string) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.datalosspreventionstate = &datalosspreventionstate
	return r
}

// Filter out domains that generate a lot of insignificant traffic (noise).
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Filternoisydomains(filternoisydomains bool) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.filternoisydomains = &filternoisydomains
	return r
}

// Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash (&#39;/&#39;), for example: timezone&#x3D;&#39;ASIA%2fCALCUTTA&#39;.
func (r ApiGetRequestsByTimerangeAndCategoryRequest) Timezone(timezone string) ApiGetRequestsByTimerangeAndCategoryRequest {
	r.timezone = &timezone
	return r
}

func (r ApiGetRequestsByTimerangeAndCategoryRequest) Execute() (*GetRequestsByHourAndCategory200Response, *http.Response, error) {
	return r.ApiService.GetRequestsByTimerangeAndCategoryExecute(r)
}

/*
GetRequestsByTimerangeAndCategory Get Requests by Timerange and Category (All)

List the activity volume within the timeframe by category.

**Access Scope:** Reports > Granular Events > Read-Only

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetRequestsByTimerangeAndCategoryRequest
*/
func (a *OrganizationRequestsByTimerangeAndCategoryAPIService) GetRequestsByTimerangeAndCategory(ctx context.Context) ApiGetRequestsByTimerangeAndCategoryRequest {
	return ApiGetRequestsByTimerangeAndCategoryRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return GetRequestsByHourAndCategory200Response
func (a *OrganizationRequestsByTimerangeAndCategoryAPIService) GetRequestsByTimerangeAndCategoryExecute(r ApiGetRequestsByTimerangeAndCategoryRequest) (*GetRequestsByHourAndCategory200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetRequestsByHourAndCategory200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OrganizationRequestsByTimerangeAndCategoryAPIService.GetRequestsByTimerangeAndCategory")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/reports/v2/categories-by-timerange"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.from == nil {
		return localVarReturnValue, nil, reportError("from is required and must be specified")
	}
	if r.to == nil {
		return localVarReturnValue, nil, reportError("to is required and must be specified")
	}
	if r.limit == nil {
		return localVarReturnValue, nil, reportError("limit is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "from", r.from, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "to", r.to, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	} else {
		var defaultValue int64 = 0
		r.offset = &defaultValue
	}
	if r.domains != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "domains", r.domains, "form", "")
	}
	if r.urls != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "urls", r.urls, "form", "")
	}
	if r.categories != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "categories", r.categories, "form", "")
	}
	if r.policycategories != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "policycategories", r.policycategories, "form", "")
	}
	if r.ip != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "ip", r.ip, "form", "")
	}
	if r.identityids != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "identityids", r.identityids, "form", "")
	}
	if r.identitytypes != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "identitytypes", r.identitytypes, "form", "")
	}
	if r.applicationid != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "applicationid", r.applicationid, "form", "")
	}
	if r.verdict != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "verdict", r.verdict, "form", "")
	}
	if r.securityoverridden != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "securityoverridden", r.securityoverridden, "form", "")
	}
	if r.bundleid != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "bundleid", r.bundleid, "form", "")
	}
	if r.threats != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "threats", r.threats, "form", "")
	}
	if r.threattypes != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "threattypes", r.threattypes, "form", "")
	}
	if r.ampdisposition != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "ampdisposition", r.ampdisposition, "form", "")
	}
	if r.antivirusthreats != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "antivirusthreats", r.antivirusthreats, "form", "")
	}
	if r.datalosspreventionstate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "datalosspreventionstate", r.datalosspreventionstate, "form", "")
	}
	if r.filternoisydomains != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "filternoisydomains", r.filternoisydomains, "form", "")
	}
	if r.timezone != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "timezone", r.timezone, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.timerange != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "timerange", r.timerange, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v GetActivities400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v GetActivities401Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v GetActivities403Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v GetActivities404Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v GetActivities500Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetRequestsByTimerangeAndCategoryTypeRequest struct {
	ctx context.Context
	ApiService *OrganizationRequestsByTimerangeAndCategoryAPIService
	type_ string
	from *string
	to *string
	limit *int64
	offset *int64
	domains *string
	urls *string
	categories *string
	policycategories *string
	ip *string
	identityids *string
	identitytypes *string
	applicationid *string
	verdict *string
	securityoverridden *bool
	bundleid *int64
	threats *string
	threattypes *string
	ampdisposition *string
	antivirusthreats *string
	timerange *string
	datalosspreventionstate *string
	filternoisydomains *bool
	timezone *string
}

// A timestamp or relative time string (for example: &#39;-1days&#39;). Filter for data that appears after this time.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) From(from string) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.from = &from
	return r
}

// A timestamp or relative time string (for example: &#39;now&#39;). Filter for data that appears before this time.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) To(to string) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.to = &to
	return r
}

// The maximum number of records to return from the collection.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Limit(limit int64) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.limit = &limit
	return r
}

// A number that represents an index in the collection.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Offset(offset int64) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.offset = &offset
	return r
}

// A domain name or comma-delimited list of domain name.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Domains(domains string) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.domains = &domains
	return r
}

// A URL or comma-delimited list of URL.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Urls(urls string) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.urls = &urls
	return r
}

// A category ID or comma-delimited list of category ID.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Categories(categories string) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.categories = &categories
	return r
}

// A category ID or comma-delimited list of category ID. Filter the request by the categories that trigger a policy.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Policycategories(policycategories string) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.policycategories = &policycategories
	return r
}

// An IP address.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Ip(ip string) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.ip = &ip
	return r
}

// An identity ID or comma-delimited list of identity IDs.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Identityids(identityids string) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.identityids = &identityids
	return r
}

// An identity type or comma-delimited list of identity types.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Identitytypes(identitytypes string) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.identitytypes = &identitytypes
	return r
}

// The ID of the application.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Applicationid(applicationid string) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.applicationid = &applicationid
	return r
}

// A string or comma-delimited string that describes whether the traffic can reach the destination.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Verdict(verdict string) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.verdict = &verdict
	return r
}

// Specify whether to filter on requests that override security.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Securityoverridden(securityoverridden bool) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.securityoverridden = &securityoverridden
	return r
}

// A proxy bundle ID.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Bundleid(bundleid int64) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.bundleid = &bundleid
	return r
}

// A threat name or comma-delimited list of threat names.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Threats(threats string) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.threats = &threats
	return r
}

// A threat type or comma-delimited list of threat types.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Threattypes(threattypes string) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.threattypes = &threattypes
	return r
}

// An AMP disposition string or a comma-delimited list of AMP disposition strings.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Ampdisposition(ampdisposition string) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.ampdisposition = &ampdisposition
	return r
}

// A threat name or comma-delimited list of threat names.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Antivirusthreats(antivirusthreats string) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.antivirusthreats = &antivirusthreats
	return r
}

// A string that represents a range of time. If the header is not set, the header value defaults to &#x60;hour&#x60;.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Timerange(timerange string) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.timerange = &timerange
	return r
}

// A string that describes the status of a destination. Filter for requests that are blocked by the DLP layer security.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Datalosspreventionstate(datalosspreventionstate string) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.datalosspreventionstate = &datalosspreventionstate
	return r
}

// Filter out domains that generate a lot of insignificant traffic (noise).
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Filternoisydomains(filternoisydomains bool) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.filternoisydomains = &filternoisydomains
	return r
}

// Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash (&#39;/&#39;), for example: timezone&#x3D;&#39;ASIA%2fCALCUTTA&#39;.
func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Timezone(timezone string) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	r.timezone = &timezone
	return r
}

func (r ApiGetRequestsByTimerangeAndCategoryTypeRequest) Execute() (*GetRequestsByHourAndCategory200Response, *http.Response, error) {
	return r.ApiService.GetRequestsByTimerangeAndCategoryTypeExecute(r)
}

/*
GetRequestsByTimerangeAndCategoryType Get Requests by Timerange and Category

List the activity volume within the timeframe by category.

**Access Scope:** Reports > Granular Events > Read-Only

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param type_ Specify the type of traffic.
 @return ApiGetRequestsByTimerangeAndCategoryTypeRequest
*/
func (a *OrganizationRequestsByTimerangeAndCategoryAPIService) GetRequestsByTimerangeAndCategoryType(ctx context.Context, type_ string) ApiGetRequestsByTimerangeAndCategoryTypeRequest {
	return ApiGetRequestsByTimerangeAndCategoryTypeRequest{
		ApiService: a,
		ctx: ctx,
		type_: type_,
	}
}

// Execute executes the request
//  @return GetRequestsByHourAndCategory200Response
func (a *OrganizationRequestsByTimerangeAndCategoryAPIService) GetRequestsByTimerangeAndCategoryTypeExecute(r ApiGetRequestsByTimerangeAndCategoryTypeRequest) (*GetRequestsByHourAndCategory200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetRequestsByHourAndCategory200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OrganizationRequestsByTimerangeAndCategoryAPIService.GetRequestsByTimerangeAndCategoryType")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/reports/v2/categories-by-timerange/{type}"
	localVarPath = strings.Replace(localVarPath, "{"+"type"+"}", url.PathEscape(parameterValueToString(r.type_, "type_")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.from == nil {
		return localVarReturnValue, nil, reportError("from is required and must be specified")
	}
	if r.to == nil {
		return localVarReturnValue, nil, reportError("to is required and must be specified")
	}
	if r.limit == nil {
		return localVarReturnValue, nil, reportError("limit is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "from", r.from, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "to", r.to, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	} else {
		var defaultValue int64 = 0
		r.offset = &defaultValue
	}
	if r.domains != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "domains", r.domains, "form", "")
	}
	if r.urls != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "urls", r.urls, "form", "")
	}
	if r.categories != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "categories", r.categories, "form", "")
	}
	if r.policycategories != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "policycategories", r.policycategories, "form", "")
	}
	if r.ip != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "ip", r.ip, "form", "")
	}
	if r.identityids != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "identityids", r.identityids, "form", "")
	}
	if r.identitytypes != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "identitytypes", r.identitytypes, "form", "")
	}
	if r.applicationid != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "applicationid", r.applicationid, "form", "")
	}
	if r.verdict != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "verdict", r.verdict, "form", "")
	}
	if r.securityoverridden != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "securityoverridden", r.securityoverridden, "form", "")
	}
	if r.bundleid != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "bundleid", r.bundleid, "form", "")
	}
	if r.threats != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "threats", r.threats, "form", "")
	}
	if r.threattypes != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "threattypes", r.threattypes, "form", "")
	}
	if r.ampdisposition != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "ampdisposition", r.ampdisposition, "form", "")
	}
	if r.antivirusthreats != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "antivirusthreats", r.antivirusthreats, "form", "")
	}
	if r.datalosspreventionstate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "datalosspreventionstate", r.datalosspreventionstate, "form", "")
	}
	if r.filternoisydomains != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "filternoisydomains", r.filternoisydomains, "form", "")
	}
	if r.timezone != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "timezone", r.timezone, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.timerange != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "timerange", r.timerange, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v GetActivities400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v GetActivities401Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v GetActivities403Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v GetActivities404Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v GetActivities500Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
