/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
)

// checks if the ApplicationAttributeCategory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationAttributeCategory{}

// ApplicationAttributeCategory The application's attribute category.
type ApplicationAttributeCategory struct {
	// The ID of the attribute category.
	Id *string `json:"id,omitempty"`
	// The name of the attribute category.
	Name *string `json:"name,omitempty"`
	Attributes []ApplicationAttribute `json:"attributes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ApplicationAttributeCategory ApplicationAttributeCategory

// NewApplicationAttributeCategory instantiates a new ApplicationAttributeCategory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationAttributeCategory() *ApplicationAttributeCategory {
	this := ApplicationAttributeCategory{}
	return &this
}

// NewApplicationAttributeCategoryWithDefaults instantiates a new ApplicationAttributeCategory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationAttributeCategoryWithDefaults() *ApplicationAttributeCategory {
	this := ApplicationAttributeCategory{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApplicationAttributeCategory) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationAttributeCategory) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApplicationAttributeCategory) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApplicationAttributeCategory) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApplicationAttributeCategory) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationAttributeCategory) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApplicationAttributeCategory) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApplicationAttributeCategory) SetName(v string) {
	o.Name = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *ApplicationAttributeCategory) GetAttributes() []ApplicationAttribute {
	if o == nil || IsNil(o.Attributes) {
		var ret []ApplicationAttribute
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationAttributeCategory) GetAttributesOk() ([]ApplicationAttribute, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *ApplicationAttributeCategory) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given []ApplicationAttribute and assigns it to the Attributes field.
func (o *ApplicationAttributeCategory) SetAttributes(v []ApplicationAttribute) {
	o.Attributes = v
}

func (o ApplicationAttributeCategory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationAttributeCategory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApplicationAttributeCategory) UnmarshalJSON(data []byte) (err error) {
	varApplicationAttributeCategory := _ApplicationAttributeCategory{}

	err = json.Unmarshal(data, &varApplicationAttributeCategory)

	if err != nil {
		return err
	}

	*o = ApplicationAttributeCategory(varApplicationAttributeCategory)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "attributes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApplicationAttributeCategory struct {
	value *ApplicationAttributeCategory
	isSet bool
}

func (v NullableApplicationAttributeCategory) Get() *ApplicationAttributeCategory {
	return v.value
}

func (v *NullableApplicationAttributeCategory) Set(val *ApplicationAttributeCategory) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationAttributeCategory) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationAttributeCategory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationAttributeCategory(val *ApplicationAttributeCategory) *NullableApplicationAttributeCategory {
	return &NullableApplicationAttributeCategory{value: val, isSet: true}
}

func (v NullableApplicationAttributeCategory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationAttributeCategory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


