/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
	"fmt"
)

// checks if the GetActivityIntrusion200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetActivityIntrusion200Response{}

// GetActivityIntrusion200Response struct for GetActivityIntrusion200Response
type GetActivityIntrusion200Response struct {
	Data []ActivityIntrusion `json:"data"`
	// The properties of the metadata.
	Meta map[string]interface{} `json:"meta"`
	AdditionalProperties map[string]interface{}
}

type _GetActivityIntrusion200Response GetActivityIntrusion200Response

// NewGetActivityIntrusion200Response instantiates a new GetActivityIntrusion200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetActivityIntrusion200Response(data []ActivityIntrusion, meta map[string]interface{}) *GetActivityIntrusion200Response {
	this := GetActivityIntrusion200Response{}
	this.Data = data
	this.Meta = meta
	return &this
}

// NewGetActivityIntrusion200ResponseWithDefaults instantiates a new GetActivityIntrusion200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetActivityIntrusion200ResponseWithDefaults() *GetActivityIntrusion200Response {
	this := GetActivityIntrusion200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetActivityIntrusion200Response) GetData() []ActivityIntrusion {
	if o == nil {
		var ret []ActivityIntrusion
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetActivityIntrusion200Response) GetDataOk() ([]ActivityIntrusion, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetActivityIntrusion200Response) SetData(v []ActivityIntrusion) {
	o.Data = v
}

// GetMeta returns the Meta field value
func (o *GetActivityIntrusion200Response) GetMeta() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *GetActivityIntrusion200Response) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Meta, true
}

// SetMeta sets field value
func (o *GetActivityIntrusion200Response) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

func (o GetActivityIntrusion200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetActivityIntrusion200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["meta"] = o.Meta

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetActivityIntrusion200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"meta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetActivityIntrusion200Response := _GetActivityIntrusion200Response{}

	err = json.Unmarshal(data, &varGetActivityIntrusion200Response)

	if err != nil {
		return err
	}

	*o = GetActivityIntrusion200Response(varGetActivityIntrusion200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "meta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetActivityIntrusion200Response struct {
	value *GetActivityIntrusion200Response
	isSet bool
}

func (v NullableGetActivityIntrusion200Response) Get() *GetActivityIntrusion200Response {
	return v.value
}

func (v *NullableGetActivityIntrusion200Response) Set(val *GetActivityIntrusion200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetActivityIntrusion200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetActivityIntrusion200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetActivityIntrusion200Response(val *GetActivityIntrusion200Response) *NullableGetActivityIntrusion200Response {
	return &NullableGetActivityIntrusion200Response{value: val, isSet: true}
}

func (v NullableGetActivityIntrusion200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetActivityIntrusion200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


