/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
	"fmt"
)

// checks if the GetUsageMetrics200ResponseBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUsageMetrics200ResponseBody{}

// GetUsageMetrics200ResponseBody struct for GetUsageMetrics200ResponseBody
type GetUsageMetrics200ResponseBody struct {
	Usages []Usage `json:"usages"`
	AdditionalProperties map[string]interface{}
}

type _GetUsageMetrics200ResponseBody GetUsageMetrics200ResponseBody

// NewGetUsageMetrics200ResponseBody instantiates a new GetUsageMetrics200ResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUsageMetrics200ResponseBody(usages []Usage) *GetUsageMetrics200ResponseBody {
	this := GetUsageMetrics200ResponseBody{}
	this.Usages = usages
	return &this
}

// NewGetUsageMetrics200ResponseBodyWithDefaults instantiates a new GetUsageMetrics200ResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUsageMetrics200ResponseBodyWithDefaults() *GetUsageMetrics200ResponseBody {
	this := GetUsageMetrics200ResponseBody{}
	return &this
}

// GetUsages returns the Usages field value
func (o *GetUsageMetrics200ResponseBody) GetUsages() []Usage {
	if o == nil {
		var ret []Usage
		return ret
	}

	return o.Usages
}

// GetUsagesOk returns a tuple with the Usages field value
// and a boolean to check if the value has been set.
func (o *GetUsageMetrics200ResponseBody) GetUsagesOk() ([]Usage, bool) {
	if o == nil {
		return nil, false
	}
	return o.Usages, true
}

// SetUsages sets field value
func (o *GetUsageMetrics200ResponseBody) SetUsages(v []Usage) {
	o.Usages = v
}

func (o GetUsageMetrics200ResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUsageMetrics200ResponseBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["usages"] = o.Usages

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetUsageMetrics200ResponseBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"usages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetUsageMetrics200ResponseBody := _GetUsageMetrics200ResponseBody{}

	err = json.Unmarshal(data, &varGetUsageMetrics200ResponseBody)

	if err != nil {
		return err
	}

	*o = GetUsageMetrics200ResponseBody(varGetUsageMetrics200ResponseBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "usages")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetUsageMetrics200ResponseBody struct {
	value *GetUsageMetrics200ResponseBody
	isSet bool
}

func (v NullableGetUsageMetrics200ResponseBody) Get() *GetUsageMetrics200ResponseBody {
	return v.value
}

func (v *NullableGetUsageMetrics200ResponseBody) Set(val *GetUsageMetrics200ResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUsageMetrics200ResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUsageMetrics200ResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUsageMetrics200ResponseBody(val *GetUsageMetrics200ResponseBody) *NullableGetUsageMetrics200ResponseBody {
	return &NullableGetUsageMetrics200ResponseBody{value: val, isSet: true}
}

func (v NullableGetUsageMetrics200ResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUsageMetrics200ResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


