// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
)

// checks if the ApplicationCategories type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationCategories{}

// ApplicationCategories The information about the applications.
type ApplicationCategories struct {
	// The ID of the application category.
	Id *int64 `json:"id,omitempty"`
	// The name of the application category.
	Name *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ApplicationCategories ApplicationCategories

// NewApplicationCategories instantiates a new ApplicationCategories object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationCategories() *ApplicationCategories {
	this := ApplicationCategories{}
	return &this
}

// NewApplicationCategoriesWithDefaults instantiates a new ApplicationCategories object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationCategoriesWithDefaults() *ApplicationCategories {
	this := ApplicationCategories{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApplicationCategories) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationCategories) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApplicationCategories) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ApplicationCategories) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApplicationCategories) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationCategories) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApplicationCategories) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApplicationCategories) SetName(v string) {
	o.Name = &v
}

func (o ApplicationCategories) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationCategories) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApplicationCategories) UnmarshalJSON(data []byte) (err error) {
	varApplicationCategories := _ApplicationCategories{}

	err = json.Unmarshal(data, &varApplicationCategories)

	if err != nil {
		return err
	}

	*o = ApplicationCategories(varApplicationCategories)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApplicationCategories struct {
	value *ApplicationCategories
	isSet bool
}

func (v NullableApplicationCategories) Get() *ApplicationCategories {
	return v.value
}

func (v *NullableApplicationCategories) Set(val *ApplicationCategories) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationCategories) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationCategories) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationCategories(val *ApplicationCategories) *NullableApplicationCategories {
	return &NullableApplicationCategories{value: val, isSet: true}
}

func (v NullableApplicationCategories) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationCategories) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


