/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
)

// checks if the PostIdentitiesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostIdentitiesRequest{}

// PostIdentitiesRequest Provide an array of identity ID.
type PostIdentitiesRequest struct {
	// A list of identity ID.
	Identityids []int64 `json:"identityids,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PostIdentitiesRequest PostIdentitiesRequest

// NewPostIdentitiesRequest instantiates a new PostIdentitiesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostIdentitiesRequest() *PostIdentitiesRequest {
	this := PostIdentitiesRequest{}
	return &this
}

// NewPostIdentitiesRequestWithDefaults instantiates a new PostIdentitiesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostIdentitiesRequestWithDefaults() *PostIdentitiesRequest {
	this := PostIdentitiesRequest{}
	return &this
}

// GetIdentityids returns the Identityids field value if set, zero value otherwise.
func (o *PostIdentitiesRequest) GetIdentityids() []int64 {
	if o == nil || IsNil(o.Identityids) {
		var ret []int64
		return ret
	}
	return o.Identityids
}

// GetIdentityidsOk returns a tuple with the Identityids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostIdentitiesRequest) GetIdentityidsOk() ([]int64, bool) {
	if o == nil || IsNil(o.Identityids) {
		return nil, false
	}
	return o.Identityids, true
}

// HasIdentityids returns a boolean if a field has been set.
func (o *PostIdentitiesRequest) HasIdentityids() bool {
	if o != nil && !IsNil(o.Identityids) {
		return true
	}

	return false
}

// SetIdentityids gets a reference to the given []int64 and assigns it to the Identityids field.
func (o *PostIdentitiesRequest) SetIdentityids(v []int64) {
	o.Identityids = v
}

func (o PostIdentitiesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostIdentitiesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Identityids) {
		toSerialize["identityids"] = o.Identityids
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PostIdentitiesRequest) UnmarshalJSON(data []byte) (err error) {
	varPostIdentitiesRequest := _PostIdentitiesRequest{}

	err = json.Unmarshal(data, &varPostIdentitiesRequest)

	if err != nil {
		return err
	}

	*o = PostIdentitiesRequest(varPostIdentitiesRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "identityids")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePostIdentitiesRequest struct {
	value *PostIdentitiesRequest
	isSet bool
}

func (v NullablePostIdentitiesRequest) Get() *PostIdentitiesRequest {
	return v.value
}

func (v *NullablePostIdentitiesRequest) Set(val *PostIdentitiesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostIdentitiesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostIdentitiesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostIdentitiesRequest(val *PostIdentitiesRequest) *NullablePostIdentitiesRequest {
	return &NullablePostIdentitiesRequest{value: val, isSet: true}
}

func (v NullablePostIdentitiesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostIdentitiesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


