// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
	"fmt"
)

// checks if the RemoteAccess type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoteAccess{}

// RemoteAccess The properties of the remote access event.
type RemoteAccess struct {
	// The OS version of the host.
	Osversion string `json:"osversion"`
	// The internal IP address of the host.
	Internalip string `json:"internalip"`
	// The time and date when the host connected, expressed in seconds.
	Connecttimestamp int64 `json:"connecttimestamp"`
	// The reason the event occurred for the remote access endpoint.
	Reason string `json:"reason"`
	// A list of messages that describe the remote access error.
	Failedreasons []string `json:"failedreasons"`
	// The type of event associated with the remote connection.
	Connectionevent string `json:"connectionevent"`
	// The version of the AnyConnect Roaming Security module.
	Anyconnectversion string `json:"anyconnectversion"`
	// The public IP address of the host
	Publicip string `json:"publicip"`
	// The VPN profile
	Vpnprofile string `json:"vpnprofile"`
	// The session type of the remote connection.
	Sessiontype string `json:"sessiontype"`
	// The timestamp represented in seconds.
	Timestamp int64 `json:"timestamp"`
	Identities []RemoteAccessIdentitiesInner `json:"identities"`
	AdditionalProperties map[string]interface{}
}

type _RemoteAccess RemoteAccess

// NewRemoteAccess instantiates a new RemoteAccess object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoteAccess(osversion string, internalip string, connecttimestamp int64, reason string, failedreasons []string, connectionevent string, anyconnectversion string, publicip string, vpnprofile string, sessiontype string, timestamp int64, identities []RemoteAccessIdentitiesInner) *RemoteAccess {
	this := RemoteAccess{}
	this.Osversion = osversion
	this.Internalip = internalip
	this.Connecttimestamp = connecttimestamp
	this.Reason = reason
	this.Failedreasons = failedreasons
	this.Connectionevent = connectionevent
	this.Anyconnectversion = anyconnectversion
	this.Publicip = publicip
	this.Vpnprofile = vpnprofile
	this.Sessiontype = sessiontype
	this.Timestamp = timestamp
	this.Identities = identities
	return &this
}

// NewRemoteAccessWithDefaults instantiates a new RemoteAccess object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoteAccessWithDefaults() *RemoteAccess {
	this := RemoteAccess{}
	return &this
}

// GetOsversion returns the Osversion field value
func (o *RemoteAccess) GetOsversion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Osversion
}

// GetOsversionOk returns a tuple with the Osversion field value
// and a boolean to check if the value has been set.
func (o *RemoteAccess) GetOsversionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Osversion, true
}

// SetOsversion sets field value
func (o *RemoteAccess) SetOsversion(v string) {
	o.Osversion = v
}

// GetInternalip returns the Internalip field value
func (o *RemoteAccess) GetInternalip() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Internalip
}

// GetInternalipOk returns a tuple with the Internalip field value
// and a boolean to check if the value has been set.
func (o *RemoteAccess) GetInternalipOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Internalip, true
}

// SetInternalip sets field value
func (o *RemoteAccess) SetInternalip(v string) {
	o.Internalip = v
}

// GetConnecttimestamp returns the Connecttimestamp field value
func (o *RemoteAccess) GetConnecttimestamp() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Connecttimestamp
}

// GetConnecttimestampOk returns a tuple with the Connecttimestamp field value
// and a boolean to check if the value has been set.
func (o *RemoteAccess) GetConnecttimestampOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Connecttimestamp, true
}

// SetConnecttimestamp sets field value
func (o *RemoteAccess) SetConnecttimestamp(v int64) {
	o.Connecttimestamp = v
}

// GetReason returns the Reason field value
func (o *RemoteAccess) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *RemoteAccess) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *RemoteAccess) SetReason(v string) {
	o.Reason = v
}

// GetFailedreasons returns the Failedreasons field value
func (o *RemoteAccess) GetFailedreasons() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Failedreasons
}

// GetFailedreasonsOk returns a tuple with the Failedreasons field value
// and a boolean to check if the value has been set.
func (o *RemoteAccess) GetFailedreasonsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Failedreasons, true
}

// SetFailedreasons sets field value
func (o *RemoteAccess) SetFailedreasons(v []string) {
	o.Failedreasons = v
}

// GetConnectionevent returns the Connectionevent field value
func (o *RemoteAccess) GetConnectionevent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Connectionevent
}

// GetConnectioneventOk returns a tuple with the Connectionevent field value
// and a boolean to check if the value has been set.
func (o *RemoteAccess) GetConnectioneventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Connectionevent, true
}

// SetConnectionevent sets field value
func (o *RemoteAccess) SetConnectionevent(v string) {
	o.Connectionevent = v
}

// GetAnyconnectversion returns the Anyconnectversion field value
func (o *RemoteAccess) GetAnyconnectversion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Anyconnectversion
}

// GetAnyconnectversionOk returns a tuple with the Anyconnectversion field value
// and a boolean to check if the value has been set.
func (o *RemoteAccess) GetAnyconnectversionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Anyconnectversion, true
}

// SetAnyconnectversion sets field value
func (o *RemoteAccess) SetAnyconnectversion(v string) {
	o.Anyconnectversion = v
}

// GetPublicip returns the Publicip field value
func (o *RemoteAccess) GetPublicip() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Publicip
}

// GetPublicipOk returns a tuple with the Publicip field value
// and a boolean to check if the value has been set.
func (o *RemoteAccess) GetPublicipOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Publicip, true
}

// SetPublicip sets field value
func (o *RemoteAccess) SetPublicip(v string) {
	o.Publicip = v
}

// GetVpnprofile returns the Vpnprofile field value
func (o *RemoteAccess) GetVpnprofile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Vpnprofile
}

// GetVpnprofileOk returns a tuple with the Vpnprofile field value
// and a boolean to check if the value has been set.
func (o *RemoteAccess) GetVpnprofileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vpnprofile, true
}

// SetVpnprofile sets field value
func (o *RemoteAccess) SetVpnprofile(v string) {
	o.Vpnprofile = v
}

// GetSessiontype returns the Sessiontype field value
func (o *RemoteAccess) GetSessiontype() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sessiontype
}

// GetSessiontypeOk returns a tuple with the Sessiontype field value
// and a boolean to check if the value has been set.
func (o *RemoteAccess) GetSessiontypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sessiontype, true
}

// SetSessiontype sets field value
func (o *RemoteAccess) SetSessiontype(v string) {
	o.Sessiontype = v
}

// GetTimestamp returns the Timestamp field value
func (o *RemoteAccess) GetTimestamp() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *RemoteAccess) GetTimestampOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *RemoteAccess) SetTimestamp(v int64) {
	o.Timestamp = v
}

// GetIdentities returns the Identities field value
func (o *RemoteAccess) GetIdentities() []RemoteAccessIdentitiesInner {
	if o == nil {
		var ret []RemoteAccessIdentitiesInner
		return ret
	}

	return o.Identities
}

// GetIdentitiesOk returns a tuple with the Identities field value
// and a boolean to check if the value has been set.
func (o *RemoteAccess) GetIdentitiesOk() ([]RemoteAccessIdentitiesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Identities, true
}

// SetIdentities sets field value
func (o *RemoteAccess) SetIdentities(v []RemoteAccessIdentitiesInner) {
	o.Identities = v
}

func (o RemoteAccess) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoteAccess) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["osversion"] = o.Osversion
	toSerialize["internalip"] = o.Internalip
	toSerialize["connecttimestamp"] = o.Connecttimestamp
	toSerialize["reason"] = o.Reason
	toSerialize["failedreasons"] = o.Failedreasons
	toSerialize["connectionevent"] = o.Connectionevent
	toSerialize["anyconnectversion"] = o.Anyconnectversion
	toSerialize["publicip"] = o.Publicip
	toSerialize["vpnprofile"] = o.Vpnprofile
	toSerialize["sessiontype"] = o.Sessiontype
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["identities"] = o.Identities

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RemoteAccess) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"osversion",
		"internalip",
		"connecttimestamp",
		"reason",
		"failedreasons",
		"connectionevent",
		"anyconnectversion",
		"publicip",
		"vpnprofile",
		"sessiontype",
		"timestamp",
		"identities",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemoteAccess := _RemoteAccess{}

	err = json.Unmarshal(data, &varRemoteAccess)

	if err != nil {
		return err
	}

	*o = RemoteAccess(varRemoteAccess)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "osversion")
		delete(additionalProperties, "internalip")
		delete(additionalProperties, "connecttimestamp")
		delete(additionalProperties, "reason")
		delete(additionalProperties, "failedreasons")
		delete(additionalProperties, "connectionevent")
		delete(additionalProperties, "anyconnectversion")
		delete(additionalProperties, "publicip")
		delete(additionalProperties, "vpnprofile")
		delete(additionalProperties, "sessiontype")
		delete(additionalProperties, "timestamp")
		delete(additionalProperties, "identities")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRemoteAccess struct {
	value *RemoteAccess
	isSet bool
}

func (v NullableRemoteAccess) Get() *RemoteAccess {
	return v.value
}

func (v *NullableRemoteAccess) Set(val *RemoteAccess) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoteAccess) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoteAccess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoteAccess(val *RemoteAccess) *NullableRemoteAccess {
	return &NullableRemoteAccess{value: val, isSet: true}
}

func (v NullableRemoteAccess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoteAccess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


