// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
	"fmt"
)

// checks if the AntivirusThreats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AntivirusThreats{}

// AntivirusThreats The information about the antivirus threats.
type AntivirusThreats struct {
	// The list of potentially unwanted applications.
	Puas []map[string]interface{} `json:"puas"`
	// The list of viruses.
	Viruses []string `json:"viruses"`
	// The list of other antivirus threats.
	Others []map[string]interface{} `json:"others"`
	AdditionalProperties map[string]interface{}
}

type _AntivirusThreats AntivirusThreats

// NewAntivirusThreats instantiates a new AntivirusThreats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAntivirusThreats(puas []map[string]interface{}, viruses []string, others []map[string]interface{}) *AntivirusThreats {
	this := AntivirusThreats{}
	this.Puas = puas
	this.Viruses = viruses
	this.Others = others
	return &this
}

// NewAntivirusThreatsWithDefaults instantiates a new AntivirusThreats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAntivirusThreatsWithDefaults() *AntivirusThreats {
	this := AntivirusThreats{}
	return &this
}

// GetPuas returns the Puas field value
func (o *AntivirusThreats) GetPuas() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.Puas
}

// GetPuasOk returns a tuple with the Puas field value
// and a boolean to check if the value has been set.
func (o *AntivirusThreats) GetPuasOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Puas, true
}

// SetPuas sets field value
func (o *AntivirusThreats) SetPuas(v []map[string]interface{}) {
	o.Puas = v
}

// GetViruses returns the Viruses field value
func (o *AntivirusThreats) GetViruses() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Viruses
}

// GetVirusesOk returns a tuple with the Viruses field value
// and a boolean to check if the value has been set.
func (o *AntivirusThreats) GetVirusesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Viruses, true
}

// SetViruses sets field value
func (o *AntivirusThreats) SetViruses(v []string) {
	o.Viruses = v
}

// GetOthers returns the Others field value
func (o *AntivirusThreats) GetOthers() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.Others
}

// GetOthersOk returns a tuple with the Others field value
// and a boolean to check if the value has been set.
func (o *AntivirusThreats) GetOthersOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Others, true
}

// SetOthers sets field value
func (o *AntivirusThreats) SetOthers(v []map[string]interface{}) {
	o.Others = v
}

func (o AntivirusThreats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AntivirusThreats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["puas"] = o.Puas
	toSerialize["viruses"] = o.Viruses
	toSerialize["others"] = o.Others

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AntivirusThreats) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"puas",
		"viruses",
		"others",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAntivirusThreats := _AntivirusThreats{}

	err = json.Unmarshal(data, &varAntivirusThreats)

	if err != nil {
		return err
	}

	*o = AntivirusThreats(varAntivirusThreats)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "puas")
		delete(additionalProperties, "viruses")
		delete(additionalProperties, "others")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAntivirusThreats struct {
	value *AntivirusThreats
	isSet bool
}

func (v NullableAntivirusThreats) Get() *AntivirusThreats {
	return v.value
}

func (v *NullableAntivirusThreats) Set(val *AntivirusThreats) {
	v.value = val
	v.isSet = true
}

func (v NullableAntivirusThreats) IsSet() bool {
	return v.isSet
}

func (v *NullableAntivirusThreats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAntivirusThreats(val *AntivirusThreats) *NullableAntivirusThreats {
	return &NullableAntivirusThreats{value: val, isSet: true}
}

func (v NullableAntivirusThreats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAntivirusThreats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


