// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
	"fmt"
)

// checks if the TotalRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TotalRequest{}

// TotalRequest The total number of requests.
type TotalRequest struct {
	// The total number of API requests.
	Count int64 `json:"count"`
	AdditionalProperties map[string]interface{}
}

type _TotalRequest TotalRequest

// NewTotalRequest instantiates a new TotalRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTotalRequest(count int64) *TotalRequest {
	this := TotalRequest{}
	this.Count = count
	return &this
}

// NewTotalRequestWithDefaults instantiates a new TotalRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTotalRequestWithDefaults() *TotalRequest {
	this := TotalRequest{}
	return &this
}

// GetCount returns the Count field value
func (o *TotalRequest) GetCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *TotalRequest) GetCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *TotalRequest) SetCount(v int64) {
	o.Count = v
}

func (o TotalRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TotalRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TotalRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTotalRequest := _TotalRequest{}

	err = json.Unmarshal(data, &varTotalRequest)

	if err != nil {
		return err
	}

	*o = TotalRequest(varTotalRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "count")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTotalRequest struct {
	value *TotalRequest
	isSet bool
}

func (v NullableTotalRequest) Get() *TotalRequest {
	return v.value
}

func (v *NullableTotalRequest) Set(val *TotalRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTotalRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTotalRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTotalRequest(val *TotalRequest) *NullableTotalRequest {
	return &NullableTotalRequest{value: val, isSet: true}
}

func (v NullableTotalRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTotalRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


