/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
	"fmt"
)

// checks if the SummaryData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SummaryData{}

// SummaryData The total number of requsts and the counts of the failed and successful requests.
type SummaryData struct {
	// The number of successful API requests.
	SuccessfulRequests int64 `json:"successfulRequests"`
	// The number of failed API requests.
	FailedRequests int64 `json:"failedRequests"`
	// The total number of API requests.
	Total int64 `json:"total"`
	AdditionalProperties map[string]interface{}
}

type _SummaryData SummaryData

// NewSummaryData instantiates a new SummaryData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSummaryData(successfulRequests int64, failedRequests int64, total int64) *SummaryData {
	this := SummaryData{}
	this.SuccessfulRequests = successfulRequests
	this.FailedRequests = failedRequests
	this.Total = total
	return &this
}

// NewSummaryDataWithDefaults instantiates a new SummaryData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSummaryDataWithDefaults() *SummaryData {
	this := SummaryData{}
	return &this
}

// GetSuccessfulRequests returns the SuccessfulRequests field value
func (o *SummaryData) GetSuccessfulRequests() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SuccessfulRequests
}

// GetSuccessfulRequestsOk returns a tuple with the SuccessfulRequests field value
// and a boolean to check if the value has been set.
func (o *SummaryData) GetSuccessfulRequestsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SuccessfulRequests, true
}

// SetSuccessfulRequests sets field value
func (o *SummaryData) SetSuccessfulRequests(v int64) {
	o.SuccessfulRequests = v
}

// GetFailedRequests returns the FailedRequests field value
func (o *SummaryData) GetFailedRequests() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.FailedRequests
}

// GetFailedRequestsOk returns a tuple with the FailedRequests field value
// and a boolean to check if the value has been set.
func (o *SummaryData) GetFailedRequestsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailedRequests, true
}

// SetFailedRequests sets field value
func (o *SummaryData) SetFailedRequests(v int64) {
	o.FailedRequests = v
}

// GetTotal returns the Total field value
func (o *SummaryData) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *SummaryData) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *SummaryData) SetTotal(v int64) {
	o.Total = v
}

func (o SummaryData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SummaryData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["successfulRequests"] = o.SuccessfulRequests
	toSerialize["failedRequests"] = o.FailedRequests
	toSerialize["total"] = o.Total

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SummaryData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"successfulRequests",
		"failedRequests",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSummaryData := _SummaryData{}

	err = json.Unmarshal(data, &varSummaryData)

	if err != nil {
		return err
	}

	*o = SummaryData(varSummaryData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "successfulRequests")
		delete(additionalProperties, "failedRequests")
		delete(additionalProperties, "total")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSummaryData struct {
	value *SummaryData
	isSet bool
}

func (v NullableSummaryData) Get() *SummaryData {
	return v.value
}

func (v *NullableSummaryData) Set(val *SummaryData) {
	v.value = val
	v.isSet = true
}

func (v NullableSummaryData) IsSet() bool {
	return v.isSet
}

func (v *NullableSummaryData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSummaryData(val *SummaryData) *NullableSummaryData {
	return &NullableSummaryData{value: val, isSet: true}
}

func (v NullableSummaryData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSummaryData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


