/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
	"fmt"
)

// Verdict The verdict for the entry.
type Verdict string

// List of verdict
const (
	VERDICT_ALLOWED Verdict = "allowed"
	VERDICT_BLOCKED Verdict = "blocked"
)

// All allowed values of Verdict enum
var AllowedVerdictEnumValues = []Verdict{
	"allowed",
	"blocked",
}

func (v *Verdict) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Verdict(value)
	for _, existing := range AllowedVerdictEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Verdict", value)
}

// NewVerdictFromValue returns a pointer to a valid Verdict
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewVerdictFromValue(v string) (*Verdict, error) {
	ev := Verdict(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Verdict: valid values are %v", v, AllowedVerdictEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Verdict) IsValid() bool {
	for _, existing := range AllowedVerdictEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to verdict value
func (v Verdict) Ptr() *Verdict {
	return &v
}

type NullableVerdict struct {
	value *Verdict
	isSet bool
}

func (v NullableVerdict) Get() *Verdict {
	return v.value
}

func (v *NullableVerdict) Set(val *Verdict) {
	v.value = val
	v.isSet = true
}

func (v NullableVerdict) IsSet() bool {
	return v.isSet
}

func (v *NullableVerdict) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerdict(val *Verdict) *NullableVerdict {
	return &NullableVerdict{value: val, isSet: true}
}

func (v NullableVerdict) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerdict) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

