// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
)

// checks if the PrivateResourceStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateResourceStats{}

// PrivateResourceStats The properties of the private resource statistics.
type PrivateResourceStats struct {
	// The private resource ID.
	Privateresourceid *int64 `json:"privateresourceid,omitempty"`
	// The total number of identities that accessed the private resource.
	Idscount *int64 `json:"idscount,omitempty"`
	// The total number of times that an ednpoint accessed the private resource.
	Hitscount *int64 `json:"hitscount,omitempty"`
	// The last time in milliseconds since the Unix Epoch of the request for the resource.
	Lasteventat *int64 `json:"lasteventat,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PrivateResourceStats PrivateResourceStats

// NewPrivateResourceStats instantiates a new PrivateResourceStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateResourceStats() *PrivateResourceStats {
	this := PrivateResourceStats{}
	return &this
}

// NewPrivateResourceStatsWithDefaults instantiates a new PrivateResourceStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateResourceStatsWithDefaults() *PrivateResourceStats {
	this := PrivateResourceStats{}
	return &this
}

// GetPrivateresourceid returns the Privateresourceid field value if set, zero value otherwise.
func (o *PrivateResourceStats) GetPrivateresourceid() int64 {
	if o == nil || IsNil(o.Privateresourceid) {
		var ret int64
		return ret
	}
	return *o.Privateresourceid
}

// GetPrivateresourceidOk returns a tuple with the Privateresourceid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivateResourceStats) GetPrivateresourceidOk() (*int64, bool) {
	if o == nil || IsNil(o.Privateresourceid) {
		return nil, false
	}
	return o.Privateresourceid, true
}

// HasPrivateresourceid returns a boolean if a field has been set.
func (o *PrivateResourceStats) HasPrivateresourceid() bool {
	if o != nil && !IsNil(o.Privateresourceid) {
		return true
	}

	return false
}

// SetPrivateresourceid gets a reference to the given int64 and assigns it to the Privateresourceid field.
func (o *PrivateResourceStats) SetPrivateresourceid(v int64) {
	o.Privateresourceid = &v
}

// GetIdscount returns the Idscount field value if set, zero value otherwise.
func (o *PrivateResourceStats) GetIdscount() int64 {
	if o == nil || IsNil(o.Idscount) {
		var ret int64
		return ret
	}
	return *o.Idscount
}

// GetIdscountOk returns a tuple with the Idscount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivateResourceStats) GetIdscountOk() (*int64, bool) {
	if o == nil || IsNil(o.Idscount) {
		return nil, false
	}
	return o.Idscount, true
}

// HasIdscount returns a boolean if a field has been set.
func (o *PrivateResourceStats) HasIdscount() bool {
	if o != nil && !IsNil(o.Idscount) {
		return true
	}

	return false
}

// SetIdscount gets a reference to the given int64 and assigns it to the Idscount field.
func (o *PrivateResourceStats) SetIdscount(v int64) {
	o.Idscount = &v
}

// GetHitscount returns the Hitscount field value if set, zero value otherwise.
func (o *PrivateResourceStats) GetHitscount() int64 {
	if o == nil || IsNil(o.Hitscount) {
		var ret int64
		return ret
	}
	return *o.Hitscount
}

// GetHitscountOk returns a tuple with the Hitscount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivateResourceStats) GetHitscountOk() (*int64, bool) {
	if o == nil || IsNil(o.Hitscount) {
		return nil, false
	}
	return o.Hitscount, true
}

// HasHitscount returns a boolean if a field has been set.
func (o *PrivateResourceStats) HasHitscount() bool {
	if o != nil && !IsNil(o.Hitscount) {
		return true
	}

	return false
}

// SetHitscount gets a reference to the given int64 and assigns it to the Hitscount field.
func (o *PrivateResourceStats) SetHitscount(v int64) {
	o.Hitscount = &v
}

// GetLasteventat returns the Lasteventat field value if set, zero value otherwise.
func (o *PrivateResourceStats) GetLasteventat() int64 {
	if o == nil || IsNil(o.Lasteventat) {
		var ret int64
		return ret
	}
	return *o.Lasteventat
}

// GetLasteventatOk returns a tuple with the Lasteventat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivateResourceStats) GetLasteventatOk() (*int64, bool) {
	if o == nil || IsNil(o.Lasteventat) {
		return nil, false
	}
	return o.Lasteventat, true
}

// HasLasteventat returns a boolean if a field has been set.
func (o *PrivateResourceStats) HasLasteventat() bool {
	if o != nil && !IsNil(o.Lasteventat) {
		return true
	}

	return false
}

// SetLasteventat gets a reference to the given int64 and assigns it to the Lasteventat field.
func (o *PrivateResourceStats) SetLasteventat(v int64) {
	o.Lasteventat = &v
}

func (o PrivateResourceStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateResourceStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Privateresourceid) {
		toSerialize["privateresourceid"] = o.Privateresourceid
	}
	if !IsNil(o.Idscount) {
		toSerialize["idscount"] = o.Idscount
	}
	if !IsNil(o.Hitscount) {
		toSerialize["hitscount"] = o.Hitscount
	}
	if !IsNil(o.Lasteventat) {
		toSerialize["lasteventat"] = o.Lasteventat
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PrivateResourceStats) UnmarshalJSON(data []byte) (err error) {
	varPrivateResourceStats := _PrivateResourceStats{}

	err = json.Unmarshal(data, &varPrivateResourceStats)

	if err != nil {
		return err
	}

	*o = PrivateResourceStats(varPrivateResourceStats)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "privateresourceid")
		delete(additionalProperties, "idscount")
		delete(additionalProperties, "hitscount")
		delete(additionalProperties, "lasteventat")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePrivateResourceStats struct {
	value *PrivateResourceStats
	isSet bool
}

func (v NullablePrivateResourceStats) Get() *PrivateResourceStats {
	return v.value
}

func (v *NullablePrivateResourceStats) Set(val *PrivateResourceStats) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateResourceStats) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateResourceStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateResourceStats(val *PrivateResourceStats) *NullablePrivateResourceStats {
	return &NullablePrivateResourceStats{value: val, isSet: true}
}

func (v NullablePrivateResourceStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateResourceStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


