/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
	"fmt"
)

// checks if the ActivityDecryption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActivityDecryption{}

// ActivityDecryption The information about the decrypted traffic in the Activity report.
type ActivityDecryption struct {
	// The date from the timestamp based on the timezone parameter.
	Date string `json:"date"`
	// The time in 24-hour format based on the timezone parameter.
	Time string `json:"time"`
	// type of the request. Decryption
	Type string `json:"type"`
	// Type of decryption action (Decrypt Inbound, Decrypt Outbound, Do Not Decrypt, Decrypt Error).
	DecryptAction string `json:"decryptAction"`
	// The timestamp represented in milliseconds.
	Timestamp int64 `json:"timestamp"`
	// The list of identities for the entry.
	Identities []Identity `json:"identities"`
	AdditionalProperties map[string]interface{}
}

type _ActivityDecryption ActivityDecryption

// NewActivityDecryption instantiates a new ActivityDecryption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActivityDecryption(date string, time string, type_ string, decryptAction string, timestamp int64, identities []Identity) *ActivityDecryption {
	this := ActivityDecryption{}
	this.Date = date
	this.Time = time
	this.Type = type_
	this.DecryptAction = decryptAction
	this.Timestamp = timestamp
	this.Identities = identities
	return &this
}

// NewActivityDecryptionWithDefaults instantiates a new ActivityDecryption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActivityDecryptionWithDefaults() *ActivityDecryption {
	this := ActivityDecryption{}
	return &this
}

// GetDate returns the Date field value
func (o *ActivityDecryption) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *ActivityDecryption) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *ActivityDecryption) SetDate(v string) {
	o.Date = v
}

// GetTime returns the Time field value
func (o *ActivityDecryption) GetTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Time
}

// GetTimeOk returns a tuple with the Time field value
// and a boolean to check if the value has been set.
func (o *ActivityDecryption) GetTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Time, true
}

// SetTime sets field value
func (o *ActivityDecryption) SetTime(v string) {
	o.Time = v
}

// GetType returns the Type field value
func (o *ActivityDecryption) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ActivityDecryption) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ActivityDecryption) SetType(v string) {
	o.Type = v
}

// GetDecryptAction returns the DecryptAction field value
func (o *ActivityDecryption) GetDecryptAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DecryptAction
}

// GetDecryptActionOk returns a tuple with the DecryptAction field value
// and a boolean to check if the value has been set.
func (o *ActivityDecryption) GetDecryptActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DecryptAction, true
}

// SetDecryptAction sets field value
func (o *ActivityDecryption) SetDecryptAction(v string) {
	o.DecryptAction = v
}

// GetTimestamp returns the Timestamp field value
func (o *ActivityDecryption) GetTimestamp() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *ActivityDecryption) GetTimestampOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *ActivityDecryption) SetTimestamp(v int64) {
	o.Timestamp = v
}

// GetIdentities returns the Identities field value
func (o *ActivityDecryption) GetIdentities() []Identity {
	if o == nil {
		var ret []Identity
		return ret
	}

	return o.Identities
}

// GetIdentitiesOk returns a tuple with the Identities field value
// and a boolean to check if the value has been set.
func (o *ActivityDecryption) GetIdentitiesOk() ([]Identity, bool) {
	if o == nil {
		return nil, false
	}
	return o.Identities, true
}

// SetIdentities sets field value
func (o *ActivityDecryption) SetIdentities(v []Identity) {
	o.Identities = v
}

func (o ActivityDecryption) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActivityDecryption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["time"] = o.Time
	toSerialize["type"] = o.Type
	toSerialize["decryptAction"] = o.DecryptAction
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["identities"] = o.Identities

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ActivityDecryption) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
		"time",
		"type",
		"decryptAction",
		"timestamp",
		"identities",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActivityDecryption := _ActivityDecryption{}

	err = json.Unmarshal(data, &varActivityDecryption)

	if err != nil {
		return err
	}

	*o = ActivityDecryption(varActivityDecryption)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "date")
		delete(additionalProperties, "time")
		delete(additionalProperties, "type")
		delete(additionalProperties, "decryptAction")
		delete(additionalProperties, "timestamp")
		delete(additionalProperties, "identities")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableActivityDecryption struct {
	value *ActivityDecryption
	isSet bool
}

func (v NullableActivityDecryption) Get() *ActivityDecryption {
	return v.value
}

func (v *NullableActivityDecryption) Set(val *ActivityDecryption) {
	v.value = val
	v.isSet = true
}

func (v NullableActivityDecryption) IsSet() bool {
	return v.isSet
}

func (v *NullableActivityDecryption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActivityDecryption(val *ActivityDecryption) *NullableActivityDecryption {
	return &NullableActivityDecryption{value: val, isSet: true}
}

func (v NullableActivityDecryption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActivityDecryption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


