/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
	"fmt"
)

// checks if the SummaryWithDestination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SummaryWithDestination{}

// SummaryWithDestination The summary and destination information.
type SummaryWithDestination struct {
	// destination domain
	Domain string `json:"domain"`
	Summary Summary `json:"summary"`
	AdditionalProperties map[string]interface{}
}

type _SummaryWithDestination SummaryWithDestination

// NewSummaryWithDestination instantiates a new SummaryWithDestination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSummaryWithDestination(domain string, summary Summary) *SummaryWithDestination {
	this := SummaryWithDestination{}
	this.Domain = domain
	this.Summary = summary
	return &this
}

// NewSummaryWithDestinationWithDefaults instantiates a new SummaryWithDestination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSummaryWithDestinationWithDefaults() *SummaryWithDestination {
	this := SummaryWithDestination{}
	return &this
}

// GetDomain returns the Domain field value
func (o *SummaryWithDestination) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *SummaryWithDestination) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *SummaryWithDestination) SetDomain(v string) {
	o.Domain = v
}

// GetSummary returns the Summary field value
func (o *SummaryWithDestination) GetSummary() Summary {
	if o == nil {
		var ret Summary
		return ret
	}

	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
func (o *SummaryWithDestination) GetSummaryOk() (*Summary, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Summary, true
}

// SetSummary sets field value
func (o *SummaryWithDestination) SetSummary(v Summary) {
	o.Summary = v
}

func (o SummaryWithDestination) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SummaryWithDestination) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domain"] = o.Domain
	toSerialize["summary"] = o.Summary

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SummaryWithDestination) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domain",
		"summary",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSummaryWithDestination := _SummaryWithDestination{}

	err = json.Unmarshal(data, &varSummaryWithDestination)

	if err != nil {
		return err
	}

	*o = SummaryWithDestination(varSummaryWithDestination)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "domain")
		delete(additionalProperties, "summary")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSummaryWithDestination struct {
	value *SummaryWithDestination
	isSet bool
}

func (v NullableSummaryWithDestination) Get() *SummaryWithDestination {
	return v.value
}

func (v *NullableSummaryWithDestination) Set(val *SummaryWithDestination) {
	v.value = val
	v.isSet = true
}

func (v NullableSummaryWithDestination) IsSet() bool {
	return v.isSet
}

func (v *NullableSummaryWithDestination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSummaryWithDestination(val *SummaryWithDestination) *NullableSummaryWithDestination {
	return &NullableSummaryWithDestination{value: val, isSet: true}
}

func (v NullableSummaryWithDestination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSummaryWithDestination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


