// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
)

// checks if the ApplicationRisk type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationRisk{}

// ApplicationRisk The information about the application risk.
type ApplicationRisk struct {
	// The ID of app.
	Id *string `json:"id,omitempty"`
	// The name of the app.
	Name *string `json:"name,omitempty"`
	WeightedRisk *WeightedRisk `json:"weightedRisk,omitempty"`
	BusinessRisk *BusinessRisk `json:"businessRisk,omitempty"`
	UsageType *UsageType `json:"usageType,omitempty"`
	// Provides accurate conclusions about a given host by tracking a broad set of attributes and using sophisticated security modeling. Powered by Talos Security Intelligence.
	WebReputation *int64 `json:"webReputation,omitempty"`
	FinancialViability *FinancialViability `json:"financialViability,omitempty"`
	DataStorage *DataStorage `json:"dataStorage,omitempty"`
	// The vendor's compliance information.
	VendorCompliance []ApplicationRiskVendorComplianceInner `json:"vendorCompliance,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ApplicationRisk ApplicationRisk

// NewApplicationRisk instantiates a new ApplicationRisk object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationRisk() *ApplicationRisk {
	this := ApplicationRisk{}
	return &this
}

// NewApplicationRiskWithDefaults instantiates a new ApplicationRisk object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationRiskWithDefaults() *ApplicationRisk {
	this := ApplicationRisk{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApplicationRisk) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationRisk) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApplicationRisk) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApplicationRisk) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApplicationRisk) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationRisk) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApplicationRisk) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApplicationRisk) SetName(v string) {
	o.Name = &v
}

// GetWeightedRisk returns the WeightedRisk field value if set, zero value otherwise.
func (o *ApplicationRisk) GetWeightedRisk() WeightedRisk {
	if o == nil || IsNil(o.WeightedRisk) {
		var ret WeightedRisk
		return ret
	}
	return *o.WeightedRisk
}

// GetWeightedRiskOk returns a tuple with the WeightedRisk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationRisk) GetWeightedRiskOk() (*WeightedRisk, bool) {
	if o == nil || IsNil(o.WeightedRisk) {
		return nil, false
	}
	return o.WeightedRisk, true
}

// HasWeightedRisk returns a boolean if a field has been set.
func (o *ApplicationRisk) HasWeightedRisk() bool {
	if o != nil && !IsNil(o.WeightedRisk) {
		return true
	}

	return false
}

// SetWeightedRisk gets a reference to the given WeightedRisk and assigns it to the WeightedRisk field.
func (o *ApplicationRisk) SetWeightedRisk(v WeightedRisk) {
	o.WeightedRisk = &v
}

// GetBusinessRisk returns the BusinessRisk field value if set, zero value otherwise.
func (o *ApplicationRisk) GetBusinessRisk() BusinessRisk {
	if o == nil || IsNil(o.BusinessRisk) {
		var ret BusinessRisk
		return ret
	}
	return *o.BusinessRisk
}

// GetBusinessRiskOk returns a tuple with the BusinessRisk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationRisk) GetBusinessRiskOk() (*BusinessRisk, bool) {
	if o == nil || IsNil(o.BusinessRisk) {
		return nil, false
	}
	return o.BusinessRisk, true
}

// HasBusinessRisk returns a boolean if a field has been set.
func (o *ApplicationRisk) HasBusinessRisk() bool {
	if o != nil && !IsNil(o.BusinessRisk) {
		return true
	}

	return false
}

// SetBusinessRisk gets a reference to the given BusinessRisk and assigns it to the BusinessRisk field.
func (o *ApplicationRisk) SetBusinessRisk(v BusinessRisk) {
	o.BusinessRisk = &v
}

// GetUsageType returns the UsageType field value if set, zero value otherwise.
func (o *ApplicationRisk) GetUsageType() UsageType {
	if o == nil || IsNil(o.UsageType) {
		var ret UsageType
		return ret
	}
	return *o.UsageType
}

// GetUsageTypeOk returns a tuple with the UsageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationRisk) GetUsageTypeOk() (*UsageType, bool) {
	if o == nil || IsNil(o.UsageType) {
		return nil, false
	}
	return o.UsageType, true
}

// HasUsageType returns a boolean if a field has been set.
func (o *ApplicationRisk) HasUsageType() bool {
	if o != nil && !IsNil(o.UsageType) {
		return true
	}

	return false
}

// SetUsageType gets a reference to the given UsageType and assigns it to the UsageType field.
func (o *ApplicationRisk) SetUsageType(v UsageType) {
	o.UsageType = &v
}

// GetWebReputation returns the WebReputation field value if set, zero value otherwise.
func (o *ApplicationRisk) GetWebReputation() int64 {
	if o == nil || IsNil(o.WebReputation) {
		var ret int64
		return ret
	}
	return *o.WebReputation
}

// GetWebReputationOk returns a tuple with the WebReputation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationRisk) GetWebReputationOk() (*int64, bool) {
	if o == nil || IsNil(o.WebReputation) {
		return nil, false
	}
	return o.WebReputation, true
}

// HasWebReputation returns a boolean if a field has been set.
func (o *ApplicationRisk) HasWebReputation() bool {
	if o != nil && !IsNil(o.WebReputation) {
		return true
	}

	return false
}

// SetWebReputation gets a reference to the given int64 and assigns it to the WebReputation field.
func (o *ApplicationRisk) SetWebReputation(v int64) {
	o.WebReputation = &v
}

// GetFinancialViability returns the FinancialViability field value if set, zero value otherwise.
func (o *ApplicationRisk) GetFinancialViability() FinancialViability {
	if o == nil || IsNil(o.FinancialViability) {
		var ret FinancialViability
		return ret
	}
	return *o.FinancialViability
}

// GetFinancialViabilityOk returns a tuple with the FinancialViability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationRisk) GetFinancialViabilityOk() (*FinancialViability, bool) {
	if o == nil || IsNil(o.FinancialViability) {
		return nil, false
	}
	return o.FinancialViability, true
}

// HasFinancialViability returns a boolean if a field has been set.
func (o *ApplicationRisk) HasFinancialViability() bool {
	if o != nil && !IsNil(o.FinancialViability) {
		return true
	}

	return false
}

// SetFinancialViability gets a reference to the given FinancialViability and assigns it to the FinancialViability field.
func (o *ApplicationRisk) SetFinancialViability(v FinancialViability) {
	o.FinancialViability = &v
}

// GetDataStorage returns the DataStorage field value if set, zero value otherwise.
func (o *ApplicationRisk) GetDataStorage() DataStorage {
	if o == nil || IsNil(o.DataStorage) {
		var ret DataStorage
		return ret
	}
	return *o.DataStorage
}

// GetDataStorageOk returns a tuple with the DataStorage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationRisk) GetDataStorageOk() (*DataStorage, bool) {
	if o == nil || IsNil(o.DataStorage) {
		return nil, false
	}
	return o.DataStorage, true
}

// HasDataStorage returns a boolean if a field has been set.
func (o *ApplicationRisk) HasDataStorage() bool {
	if o != nil && !IsNil(o.DataStorage) {
		return true
	}

	return false
}

// SetDataStorage gets a reference to the given DataStorage and assigns it to the DataStorage field.
func (o *ApplicationRisk) SetDataStorage(v DataStorage) {
	o.DataStorage = &v
}

// GetVendorCompliance returns the VendorCompliance field value if set, zero value otherwise.
func (o *ApplicationRisk) GetVendorCompliance() []ApplicationRiskVendorComplianceInner {
	if o == nil || IsNil(o.VendorCompliance) {
		var ret []ApplicationRiskVendorComplianceInner
		return ret
	}
	return o.VendorCompliance
}

// GetVendorComplianceOk returns a tuple with the VendorCompliance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationRisk) GetVendorComplianceOk() ([]ApplicationRiskVendorComplianceInner, bool) {
	if o == nil || IsNil(o.VendorCompliance) {
		return nil, false
	}
	return o.VendorCompliance, true
}

// HasVendorCompliance returns a boolean if a field has been set.
func (o *ApplicationRisk) HasVendorCompliance() bool {
	if o != nil && !IsNil(o.VendorCompliance) {
		return true
	}

	return false
}

// SetVendorCompliance gets a reference to the given []ApplicationRiskVendorComplianceInner and assigns it to the VendorCompliance field.
func (o *ApplicationRisk) SetVendorCompliance(v []ApplicationRiskVendorComplianceInner) {
	o.VendorCompliance = v
}

func (o ApplicationRisk) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationRisk) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.WeightedRisk) {
		toSerialize["weightedRisk"] = o.WeightedRisk
	}
	if !IsNil(o.BusinessRisk) {
		toSerialize["businessRisk"] = o.BusinessRisk
	}
	if !IsNil(o.UsageType) {
		toSerialize["usageType"] = o.UsageType
	}
	if !IsNil(o.WebReputation) {
		toSerialize["webReputation"] = o.WebReputation
	}
	if !IsNil(o.FinancialViability) {
		toSerialize["financialViability"] = o.FinancialViability
	}
	if !IsNil(o.DataStorage) {
		toSerialize["dataStorage"] = o.DataStorage
	}
	if !IsNil(o.VendorCompliance) {
		toSerialize["vendorCompliance"] = o.VendorCompliance
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApplicationRisk) UnmarshalJSON(data []byte) (err error) {
	varApplicationRisk := _ApplicationRisk{}

	err = json.Unmarshal(data, &varApplicationRisk)

	if err != nil {
		return err
	}

	*o = ApplicationRisk(varApplicationRisk)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "weightedRisk")
		delete(additionalProperties, "businessRisk")
		delete(additionalProperties, "usageType")
		delete(additionalProperties, "webReputation")
		delete(additionalProperties, "financialViability")
		delete(additionalProperties, "dataStorage")
		delete(additionalProperties, "vendorCompliance")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApplicationRisk struct {
	value *ApplicationRisk
	isSet bool
}

func (v NullableApplicationRisk) Get() *ApplicationRisk {
	return v.value
}

func (v *NullableApplicationRisk) Set(val *ApplicationRisk) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationRisk) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationRisk) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationRisk(val *ApplicationRisk) *NullableApplicationRisk {
	return &NullableApplicationRisk{value: val, isSet: true}
}

func (v NullableApplicationRisk) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationRisk) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


