/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
	"fmt"
)

// checks if the ThreatType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThreatType{}

// ThreatType The properties of the threat type.
type ThreatType struct {
	// The name of the threat type.
	Name string `json:"name"`
	// The name of the threat type.
	Description string `json:"description"`
	AdditionalProperties map[string]interface{}
}

type _ThreatType ThreatType

// NewThreatType instantiates a new ThreatType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThreatType(name string, description string) *ThreatType {
	this := ThreatType{}
	this.Name = name
	this.Description = description
	return &this
}

// NewThreatTypeWithDefaults instantiates a new ThreatType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThreatTypeWithDefaults() *ThreatType {
	this := ThreatType{}
	return &this
}

// GetName returns the Name field value
func (o *ThreatType) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ThreatType) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ThreatType) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *ThreatType) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ThreatType) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ThreatType) SetDescription(v string) {
	o.Description = v
}

func (o ThreatType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThreatType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ThreatType) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varThreatType := _ThreatType{}

	err = json.Unmarshal(data, &varThreatType)

	if err != nil {
		return err
	}

	*o = ThreatType(varThreatType)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableThreatType struct {
	value *ThreatType
	isSet bool
}

func (v NullableThreatType) Get() *ThreatType {
	return v.value
}

func (v *NullableThreatType) Set(val *ThreatType) {
	v.value = val
	v.isSet = true
}

func (v NullableThreatType) IsSet() bool {
	return v.isSet
}

func (v *NullableThreatType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThreatType(val *ThreatType) *NullableThreatType {
	return &NullableThreatType{value: val, isSet: true}
}

func (v NullableThreatType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThreatType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


