/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
	"fmt"
)

// checks if the DeploymentStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentStatus{}

// DeploymentStatus The information about the deployment status.
type DeploymentStatus struct {
	Type IdentityType `json:"type"`
	// The count of the active identity type.
	Activecount int64 `json:"activecount"`
	// The total count of the identity type.
	Count int64 `json:"count"`
	AdditionalProperties map[string]interface{}
}

type _DeploymentStatus DeploymentStatus

// NewDeploymentStatus instantiates a new DeploymentStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentStatus(type_ IdentityType, activecount int64, count int64) *DeploymentStatus {
	this := DeploymentStatus{}
	this.Type = type_
	this.Activecount = activecount
	this.Count = count
	return &this
}

// NewDeploymentStatusWithDefaults instantiates a new DeploymentStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentStatusWithDefaults() *DeploymentStatus {
	this := DeploymentStatus{}
	return &this
}

// GetType returns the Type field value
func (o *DeploymentStatus) GetType() IdentityType {
	if o == nil {
		var ret IdentityType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DeploymentStatus) GetTypeOk() (*IdentityType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DeploymentStatus) SetType(v IdentityType) {
	o.Type = v
}

// GetActivecount returns the Activecount field value
func (o *DeploymentStatus) GetActivecount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Activecount
}

// GetActivecountOk returns a tuple with the Activecount field value
// and a boolean to check if the value has been set.
func (o *DeploymentStatus) GetActivecountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Activecount, true
}

// SetActivecount sets field value
func (o *DeploymentStatus) SetActivecount(v int64) {
	o.Activecount = v
}

// GetCount returns the Count field value
func (o *DeploymentStatus) GetCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *DeploymentStatus) GetCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *DeploymentStatus) SetCount(v int64) {
	o.Count = v
}

func (o DeploymentStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["activecount"] = o.Activecount
	toSerialize["count"] = o.Count

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeploymentStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"activecount",
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeploymentStatus := _DeploymentStatus{}

	err = json.Unmarshal(data, &varDeploymentStatus)

	if err != nil {
		return err
	}

	*o = DeploymentStatus(varDeploymentStatus)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "activecount")
		delete(additionalProperties, "count")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeploymentStatus struct {
	value *DeploymentStatus
	isSet bool
}

func (v NullableDeploymentStatus) Get() *DeploymentStatus {
	return v.value
}

func (v *NullableDeploymentStatus) Set(val *DeploymentStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentStatus(val *DeploymentStatus) *NullableDeploymentStatus {
	return &NullableDeploymentStatus{value: val, isSet: true}
}

func (v NullableDeploymentStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


