// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
	"fmt"
)

// checks if the TopURL type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TopURL{}

// TopURL The information about the top URLs.
type TopURL struct {
	// The total number of API requests.
	Count int64 `json:"count"`
	// The URL path.
	Path string `json:"path"`
	// The list of categories.
	Categories []Category `json:"categories"`
	// The numeric rank of the top URL.
	Rank int64 `json:"rank"`
	AdditionalProperties map[string]interface{}
}

type _TopURL TopURL

// NewTopURL instantiates a new TopURL object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTopURL(count int64, path string, categories []Category, rank int64) *TopURL {
	this := TopURL{}
	this.Count = count
	this.Path = path
	this.Categories = categories
	this.Rank = rank
	return &this
}

// NewTopURLWithDefaults instantiates a new TopURL object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTopURLWithDefaults() *TopURL {
	this := TopURL{}
	return &this
}

// GetCount returns the Count field value
func (o *TopURL) GetCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *TopURL) GetCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *TopURL) SetCount(v int64) {
	o.Count = v
}

// GetPath returns the Path field value
func (o *TopURL) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *TopURL) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *TopURL) SetPath(v string) {
	o.Path = v
}

// GetCategories returns the Categories field value
func (o *TopURL) GetCategories() []Category {
	if o == nil {
		var ret []Category
		return ret
	}

	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value
// and a boolean to check if the value has been set.
func (o *TopURL) GetCategoriesOk() ([]Category, bool) {
	if o == nil {
		return nil, false
	}
	return o.Categories, true
}

// SetCategories sets field value
func (o *TopURL) SetCategories(v []Category) {
	o.Categories = v
}

// GetRank returns the Rank field value
func (o *TopURL) GetRank() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Rank
}

// GetRankOk returns a tuple with the Rank field value
// and a boolean to check if the value has been set.
func (o *TopURL) GetRankOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rank, true
}

// SetRank sets field value
func (o *TopURL) SetRank(v int64) {
	o.Rank = v
}

func (o TopURL) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TopURL) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["path"] = o.Path
	toSerialize["categories"] = o.Categories
	toSerialize["rank"] = o.Rank

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TopURL) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"path",
		"categories",
		"rank",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTopURL := _TopURL{}

	err = json.Unmarshal(data, &varTopURL)

	if err != nil {
		return err
	}

	*o = TopURL(varTopURL)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "count")
		delete(additionalProperties, "path")
		delete(additionalProperties, "categories")
		delete(additionalProperties, "rank")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTopURL struct {
	value *TopURL
	isSet bool
}

func (v NullableTopURL) Get() *TopURL {
	return v.value
}

func (v *NullableTopURL) Set(val *TopURL) {
	v.value = val
	v.isSet = true
}

func (v NullableTopURL) IsSet() bool {
	return v.isSet
}

func (v *NullableTopURL) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTopURL(val *TopURL) *NullableTopURL {
	return &NullableTopURL{value: val, isSet: true}
}

func (v NullableTopURL) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTopURL) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


