// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
)

// checks if the GetActivities401Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetActivities401Response{}

// GetActivities401Response struct for GetActivities401Response
type GetActivities401Response struct {
	// The description of the error.
	Message *string `json:"message,omitempty"`
	// The status code of the error.
	Code *int64 `json:"code,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetActivities401Response GetActivities401Response

// NewGetActivities401Response instantiates a new GetActivities401Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetActivities401Response() *GetActivities401Response {
	this := GetActivities401Response{}
	return &this
}

// NewGetActivities401ResponseWithDefaults instantiates a new GetActivities401Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetActivities401ResponseWithDefaults() *GetActivities401Response {
	this := GetActivities401Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetActivities401Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetActivities401Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetActivities401Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetActivities401Response) SetMessage(v string) {
	o.Message = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GetActivities401Response) GetCode() int64 {
	if o == nil || IsNil(o.Code) {
		var ret int64
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetActivities401Response) GetCodeOk() (*int64, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GetActivities401Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int64 and assigns it to the Code field.
func (o *GetActivities401Response) SetCode(v int64) {
	o.Code = &v
}

func (o GetActivities401Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetActivities401Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetActivities401Response) UnmarshalJSON(data []byte) (err error) {
	varGetActivities401Response := _GetActivities401Response{}

	err = json.Unmarshal(data, &varGetActivities401Response)

	if err != nil {
		return err
	}

	*o = GetActivities401Response(varGetActivities401Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		delete(additionalProperties, "code")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetActivities401Response struct {
	value *GetActivities401Response
	isSet bool
}

func (v NullableGetActivities401Response) Get() *GetActivities401Response {
	return v.value
}

func (v *NullableGetActivities401Response) Set(val *GetActivities401Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetActivities401Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetActivities401Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetActivities401Response(val *GetActivities401Response) *NullableGetActivities401Response {
	return &NullableGetActivities401Response{value: val, isSet: true}
}

func (v NullableGetActivities401Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetActivities401Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


