// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
)

// checks if the ZtnaPolicyRulesetRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ZtnaPolicyRulesetRule{}

// ZtnaPolicyRulesetRule struct for ZtnaPolicyRulesetRule
type ZtnaPolicyRulesetRule struct {
	Id *int64 `json:"id,omitempty"`
	Label *string `json:"label,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ZtnaPolicyRulesetRule ZtnaPolicyRulesetRule

// NewZtnaPolicyRulesetRule instantiates a new ZtnaPolicyRulesetRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewZtnaPolicyRulesetRule() *ZtnaPolicyRulesetRule {
	this := ZtnaPolicyRulesetRule{}
	return &this
}

// NewZtnaPolicyRulesetRuleWithDefaults instantiates a new ZtnaPolicyRulesetRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewZtnaPolicyRulesetRuleWithDefaults() *ZtnaPolicyRulesetRule {
	this := ZtnaPolicyRulesetRule{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ZtnaPolicyRulesetRule) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ZtnaPolicyRulesetRule) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ZtnaPolicyRulesetRule) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ZtnaPolicyRulesetRule) SetId(v int64) {
	o.Id = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *ZtnaPolicyRulesetRule) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ZtnaPolicyRulesetRule) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *ZtnaPolicyRulesetRule) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *ZtnaPolicyRulesetRule) SetLabel(v string) {
	o.Label = &v
}

func (o ZtnaPolicyRulesetRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ZtnaPolicyRulesetRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ZtnaPolicyRulesetRule) UnmarshalJSON(data []byte) (err error) {
	varZtnaPolicyRulesetRule := _ZtnaPolicyRulesetRule{}

	err = json.Unmarshal(data, &varZtnaPolicyRulesetRule)

	if err != nil {
		return err
	}

	*o = ZtnaPolicyRulesetRule(varZtnaPolicyRulesetRule)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "label")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableZtnaPolicyRulesetRule struct {
	value *ZtnaPolicyRulesetRule
	isSet bool
}

func (v NullableZtnaPolicyRulesetRule) Get() *ZtnaPolicyRulesetRule {
	return v.value
}

func (v *NullableZtnaPolicyRulesetRule) Set(val *ZtnaPolicyRulesetRule) {
	v.value = val
	v.isSet = true
}

func (v NullableZtnaPolicyRulesetRule) IsSet() bool {
	return v.isSet
}

func (v *NullableZtnaPolicyRulesetRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableZtnaPolicyRulesetRule(val *ZtnaPolicyRulesetRule) *NullableZtnaPolicyRulesetRule {
	return &NullableZtnaPolicyRulesetRule{value: val, isSet: true}
}

func (v NullableZtnaPolicyRulesetRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableZtnaPolicyRulesetRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


