// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Reports

Reporting App Discovery API Usage Metering

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
	"fmt"
)

// checks if the GetIdentities200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIdentities200Response{}

// GetIdentities200Response struct for GetIdentities200Response
type GetIdentities200Response struct {
	Data []Identity `json:"data"`
	// The properties of the metadata.
	Meta map[string]interface{} `json:"meta"`
	AdditionalProperties map[string]interface{}
}

type _GetIdentities200Response GetIdentities200Response

// NewGetIdentities200Response instantiates a new GetIdentities200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIdentities200Response(data []Identity, meta map[string]interface{}) *GetIdentities200Response {
	this := GetIdentities200Response{}
	this.Data = data
	this.Meta = meta
	return &this
}

// NewGetIdentities200ResponseWithDefaults instantiates a new GetIdentities200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIdentities200ResponseWithDefaults() *GetIdentities200Response {
	this := GetIdentities200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetIdentities200Response) GetData() []Identity {
	if o == nil {
		var ret []Identity
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetIdentities200Response) GetDataOk() ([]Identity, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetIdentities200Response) SetData(v []Identity) {
	o.Data = v
}

// GetMeta returns the Meta field value
func (o *GetIdentities200Response) GetMeta() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *GetIdentities200Response) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Meta, true
}

// SetMeta sets field value
func (o *GetIdentities200Response) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

func (o GetIdentities200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIdentities200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["meta"] = o.Meta

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetIdentities200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"meta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetIdentities200Response := _GetIdentities200Response{}

	err = json.Unmarshal(data, &varGetIdentities200Response)

	if err != nil {
		return err
	}

	*o = GetIdentities200Response(varGetIdentities200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "meta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetIdentities200Response struct {
	value *GetIdentities200Response
	isSet bool
}

func (v NullableGetIdentities200Response) Get() *GetIdentities200Response {
	return v.value
}

func (v *NullableGetIdentities200Response) Set(val *GetIdentities200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIdentities200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIdentities200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIdentities200Response(val *GetIdentities200Response) *NullableGetIdentities200Response {
	return &NullableGetIdentities200Response{value: val, isSet: true}
}

func (v NullableGetIdentities200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIdentities200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


