/*
Cisco Secure Access Rules, Rule Settings, and Application Lists APIs

Testing AccessRulesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package rules

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/CiscoDevNet/go-ciscosecureaccess/rules"
)

func Test_rules_AccessRulesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AccessRulesAPIService AddRule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AccessRulesAPI.AddRule(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccessRulesAPIService DeleteRule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ruleId int64

		httpRes, err := apiClient.AccessRulesAPI.DeleteRule(context.Background(), ruleId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccessRulesAPIService GetRegionalLocations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AccessRulesAPI.GetRegionalLocations(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccessRulesAPIService GetRule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ruleId int64

		resp, httpRes, err := apiClient.AccessRulesAPI.GetRule(context.Background(), ruleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccessRulesAPIService ListRules", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AccessRulesAPI.ListRules(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccessRulesAPIService PutRule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ruleId int64

		resp, httpRes, err := apiClient.AccessRulesAPI.PutRule(context.Background(), ruleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccessRulesAPIService PutRules", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AccessRulesAPI.PutRules(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
