/*
Cisco Secure Acces Internal Networks API

Manage the internal networks in your organization.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internalnetworks

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the InternalNetworkObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InternalNetworkObject{}

// InternalNetworkObject The properties of the internal network.
type InternalNetworkObject struct {
	// The origin ID of the internal network.
	OriginId int64 `json:"originId"`
	// The name of the internal network.
	Name string `json:"name"`
	// The IP (IPv4 or IPv6) address of the internal network.
	IpAddress string `json:"ipAddress"`
	// The length of the internal network's prefix. The prefix length is between 8 and 32.
	PrefixLength int64 `json:"prefixLength"`
	// The name of the site that is associated with the internal network.
	SiteName *string `json:"siteName,omitempty"`
	// The ID of the site, which is associated with the internal network. The internal network is associated with either a `siteId`, `networkId`, or `tunnelId`.
	SiteId *int64 `json:"siteId,omitempty"`
	// The name of the network that is associated with the internal network.
	NetworkName *string `json:"networkName,omitempty"`
	// The ID of the network, which is associated with the internal network. The internal network is associated with either a `siteId`, `networkId`, or `tunnelId`.
	NetworkId *int64 `json:"networkId,omitempty"`
	// The name of the network tunnel group that is associated with the internal network.
	TunnelName *string `json:"tunnelName,omitempty"`
	// The ID of the network tunnel group ID, which is associated with the internal network. The internal network is associated with either a `siteId`, `networkId`, or `tunnelId`.
	TunnelId *int64 `json:"tunnelId,omitempty"`
	// The date and time (ISO8601 timestamp) when the internal network was created.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// The date and time (ISO8601 timestamp) when the internal network was modified.
	ModifiedAt *time.Time `json:"modifiedAt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InternalNetworkObject InternalNetworkObject

// NewInternalNetworkObject instantiates a new InternalNetworkObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalNetworkObject(originId int64, name string, ipAddress string, prefixLength int64) *InternalNetworkObject {
	this := InternalNetworkObject{}
	this.OriginId = originId
	this.Name = name
	this.IpAddress = ipAddress
	this.PrefixLength = prefixLength
	return &this
}

// NewInternalNetworkObjectWithDefaults instantiates a new InternalNetworkObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalNetworkObjectWithDefaults() *InternalNetworkObject {
	this := InternalNetworkObject{}
	return &this
}

// GetOriginId returns the OriginId field value
func (o *InternalNetworkObject) GetOriginId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.OriginId
}

// GetOriginIdOk returns a tuple with the OriginId field value
// and a boolean to check if the value has been set.
func (o *InternalNetworkObject) GetOriginIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OriginId, true
}

// SetOriginId sets field value
func (o *InternalNetworkObject) SetOriginId(v int64) {
	o.OriginId = v
}

// GetName returns the Name field value
func (o *InternalNetworkObject) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InternalNetworkObject) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InternalNetworkObject) SetName(v string) {
	o.Name = v
}

// GetIpAddress returns the IpAddress field value
func (o *InternalNetworkObject) GetIpAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IpAddress
}

// GetIpAddressOk returns a tuple with the IpAddress field value
// and a boolean to check if the value has been set.
func (o *InternalNetworkObject) GetIpAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IpAddress, true
}

// SetIpAddress sets field value
func (o *InternalNetworkObject) SetIpAddress(v string) {
	o.IpAddress = v
}

// GetPrefixLength returns the PrefixLength field value
func (o *InternalNetworkObject) GetPrefixLength() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PrefixLength
}

// GetPrefixLengthOk returns a tuple with the PrefixLength field value
// and a boolean to check if the value has been set.
func (o *InternalNetworkObject) GetPrefixLengthOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrefixLength, true
}

// SetPrefixLength sets field value
func (o *InternalNetworkObject) SetPrefixLength(v int64) {
	o.PrefixLength = v
}

// GetSiteName returns the SiteName field value if set, zero value otherwise.
func (o *InternalNetworkObject) GetSiteName() string {
	if o == nil || IsNil(o.SiteName) {
		var ret string
		return ret
	}
	return *o.SiteName
}

// GetSiteNameOk returns a tuple with the SiteName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalNetworkObject) GetSiteNameOk() (*string, bool) {
	if o == nil || IsNil(o.SiteName) {
		return nil, false
	}
	return o.SiteName, true
}

// HasSiteName returns a boolean if a field has been set.
func (o *InternalNetworkObject) HasSiteName() bool {
	if o != nil && !IsNil(o.SiteName) {
		return true
	}

	return false
}

// SetSiteName gets a reference to the given string and assigns it to the SiteName field.
func (o *InternalNetworkObject) SetSiteName(v string) {
	o.SiteName = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *InternalNetworkObject) GetSiteId() int64 {
	if o == nil || IsNil(o.SiteId) {
		var ret int64
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalNetworkObject) GetSiteIdOk() (*int64, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *InternalNetworkObject) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given int64 and assigns it to the SiteId field.
func (o *InternalNetworkObject) SetSiteId(v int64) {
	o.SiteId = &v
}

// GetNetworkName returns the NetworkName field value if set, zero value otherwise.
func (o *InternalNetworkObject) GetNetworkName() string {
	if o == nil || IsNil(o.NetworkName) {
		var ret string
		return ret
	}
	return *o.NetworkName
}

// GetNetworkNameOk returns a tuple with the NetworkName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalNetworkObject) GetNetworkNameOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkName) {
		return nil, false
	}
	return o.NetworkName, true
}

// HasNetworkName returns a boolean if a field has been set.
func (o *InternalNetworkObject) HasNetworkName() bool {
	if o != nil && !IsNil(o.NetworkName) {
		return true
	}

	return false
}

// SetNetworkName gets a reference to the given string and assigns it to the NetworkName field.
func (o *InternalNetworkObject) SetNetworkName(v string) {
	o.NetworkName = &v
}

// GetNetworkId returns the NetworkId field value if set, zero value otherwise.
func (o *InternalNetworkObject) GetNetworkId() int64 {
	if o == nil || IsNil(o.NetworkId) {
		var ret int64
		return ret
	}
	return *o.NetworkId
}

// GetNetworkIdOk returns a tuple with the NetworkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalNetworkObject) GetNetworkIdOk() (*int64, bool) {
	if o == nil || IsNil(o.NetworkId) {
		return nil, false
	}
	return o.NetworkId, true
}

// HasNetworkId returns a boolean if a field has been set.
func (o *InternalNetworkObject) HasNetworkId() bool {
	if o != nil && !IsNil(o.NetworkId) {
		return true
	}

	return false
}

// SetNetworkId gets a reference to the given int64 and assigns it to the NetworkId field.
func (o *InternalNetworkObject) SetNetworkId(v int64) {
	o.NetworkId = &v
}

// GetTunnelName returns the TunnelName field value if set, zero value otherwise.
func (o *InternalNetworkObject) GetTunnelName() string {
	if o == nil || IsNil(o.TunnelName) {
		var ret string
		return ret
	}
	return *o.TunnelName
}

// GetTunnelNameOk returns a tuple with the TunnelName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalNetworkObject) GetTunnelNameOk() (*string, bool) {
	if o == nil || IsNil(o.TunnelName) {
		return nil, false
	}
	return o.TunnelName, true
}

// HasTunnelName returns a boolean if a field has been set.
func (o *InternalNetworkObject) HasTunnelName() bool {
	if o != nil && !IsNil(o.TunnelName) {
		return true
	}

	return false
}

// SetTunnelName gets a reference to the given string and assigns it to the TunnelName field.
func (o *InternalNetworkObject) SetTunnelName(v string) {
	o.TunnelName = &v
}

// GetTunnelId returns the TunnelId field value if set, zero value otherwise.
func (o *InternalNetworkObject) GetTunnelId() int64 {
	if o == nil || IsNil(o.TunnelId) {
		var ret int64
		return ret
	}
	return *o.TunnelId
}

// GetTunnelIdOk returns a tuple with the TunnelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalNetworkObject) GetTunnelIdOk() (*int64, bool) {
	if o == nil || IsNil(o.TunnelId) {
		return nil, false
	}
	return o.TunnelId, true
}

// HasTunnelId returns a boolean if a field has been set.
func (o *InternalNetworkObject) HasTunnelId() bool {
	if o != nil && !IsNil(o.TunnelId) {
		return true
	}

	return false
}

// SetTunnelId gets a reference to the given int64 and assigns it to the TunnelId field.
func (o *InternalNetworkObject) SetTunnelId(v int64) {
	o.TunnelId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *InternalNetworkObject) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalNetworkObject) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *InternalNetworkObject) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *InternalNetworkObject) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetModifiedAt returns the ModifiedAt field value if set, zero value otherwise.
func (o *InternalNetworkObject) GetModifiedAt() time.Time {
	if o == nil || IsNil(o.ModifiedAt) {
		var ret time.Time
		return ret
	}
	return *o.ModifiedAt
}

// GetModifiedAtOk returns a tuple with the ModifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalNetworkObject) GetModifiedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ModifiedAt) {
		return nil, false
	}
	return o.ModifiedAt, true
}

// HasModifiedAt returns a boolean if a field has been set.
func (o *InternalNetworkObject) HasModifiedAt() bool {
	if o != nil && !IsNil(o.ModifiedAt) {
		return true
	}

	return false
}

// SetModifiedAt gets a reference to the given time.Time and assigns it to the ModifiedAt field.
func (o *InternalNetworkObject) SetModifiedAt(v time.Time) {
	o.ModifiedAt = &v
}

func (o InternalNetworkObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternalNetworkObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["originId"] = o.OriginId
	toSerialize["name"] = o.Name
	toSerialize["ipAddress"] = o.IpAddress
	toSerialize["prefixLength"] = o.PrefixLength
	if !IsNil(o.SiteName) {
		toSerialize["siteName"] = o.SiteName
	}
	if !IsNil(o.SiteId) {
		toSerialize["siteId"] = o.SiteId
	}
	if !IsNil(o.NetworkName) {
		toSerialize["networkName"] = o.NetworkName
	}
	if !IsNil(o.NetworkId) {
		toSerialize["networkId"] = o.NetworkId
	}
	if !IsNil(o.TunnelName) {
		toSerialize["tunnelName"] = o.TunnelName
	}
	if !IsNil(o.TunnelId) {
		toSerialize["tunnelId"] = o.TunnelId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.ModifiedAt) {
		toSerialize["modifiedAt"] = o.ModifiedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InternalNetworkObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"originId",
		"name",
		"ipAddress",
		"prefixLength",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInternalNetworkObject := _InternalNetworkObject{}

	err = json.Unmarshal(data, &varInternalNetworkObject)

	if err != nil {
		return err
	}

	*o = InternalNetworkObject(varInternalNetworkObject)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "originId")
		delete(additionalProperties, "name")
		delete(additionalProperties, "ipAddress")
		delete(additionalProperties, "prefixLength")
		delete(additionalProperties, "siteName")
		delete(additionalProperties, "siteId")
		delete(additionalProperties, "networkName")
		delete(additionalProperties, "networkId")
		delete(additionalProperties, "tunnelName")
		delete(additionalProperties, "tunnelId")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "modifiedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInternalNetworkObject struct {
	value *InternalNetworkObject
	isSet bool
}

func (v NullableInternalNetworkObject) Get() *InternalNetworkObject {
	return v.value
}

func (v *NullableInternalNetworkObject) Set(val *InternalNetworkObject) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalNetworkObject) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalNetworkObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalNetworkObject(val *InternalNetworkObject) *NullableInternalNetworkObject {
	return &NullableInternalNetworkObject{value: val, isSet: true}
}

func (v NullableInternalNetworkObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalNetworkObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


