/*
Cisco Secure Web Gateway Device Settings API

Manage the Secure Access Secure Web Gateway (SWG) settings for the devices in an organization.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swg

import (
	"encoding/json"
)

// checks if the DeleteSecureWebGatewayDeviceSettings200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteSecureWebGatewayDeviceSettings200Response{}

// DeleteSecureWebGatewayDeviceSettings200Response struct for DeleteSecureWebGatewayDeviceSettings200Response
type DeleteSecureWebGatewayDeviceSettings200Response struct {
	// Deleted SWG override setting on the devices.
	Status *string `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DeleteSecureWebGatewayDeviceSettings200Response DeleteSecureWebGatewayDeviceSettings200Response

// NewDeleteSecureWebGatewayDeviceSettings200Response instantiates a new DeleteSecureWebGatewayDeviceSettings200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteSecureWebGatewayDeviceSettings200Response() *DeleteSecureWebGatewayDeviceSettings200Response {
	this := DeleteSecureWebGatewayDeviceSettings200Response{}
	return &this
}

// NewDeleteSecureWebGatewayDeviceSettings200ResponseWithDefaults instantiates a new DeleteSecureWebGatewayDeviceSettings200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteSecureWebGatewayDeviceSettings200ResponseWithDefaults() *DeleteSecureWebGatewayDeviceSettings200Response {
	this := DeleteSecureWebGatewayDeviceSettings200Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DeleteSecureWebGatewayDeviceSettings200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteSecureWebGatewayDeviceSettings200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DeleteSecureWebGatewayDeviceSettings200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *DeleteSecureWebGatewayDeviceSettings200Response) SetStatus(v string) {
	o.Status = &v
}

func (o DeleteSecureWebGatewayDeviceSettings200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteSecureWebGatewayDeviceSettings200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeleteSecureWebGatewayDeviceSettings200Response) UnmarshalJSON(data []byte) (err error) {
	varDeleteSecureWebGatewayDeviceSettings200Response := _DeleteSecureWebGatewayDeviceSettings200Response{}

	err = json.Unmarshal(data, &varDeleteSecureWebGatewayDeviceSettings200Response)

	if err != nil {
		return err
	}

	*o = DeleteSecureWebGatewayDeviceSettings200Response(varDeleteSecureWebGatewayDeviceSettings200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeleteSecureWebGatewayDeviceSettings200Response struct {
	value *DeleteSecureWebGatewayDeviceSettings200Response
	isSet bool
}

func (v NullableDeleteSecureWebGatewayDeviceSettings200Response) Get() *DeleteSecureWebGatewayDeviceSettings200Response {
	return v.value
}

func (v *NullableDeleteSecureWebGatewayDeviceSettings200Response) Set(val *DeleteSecureWebGatewayDeviceSettings200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteSecureWebGatewayDeviceSettings200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteSecureWebGatewayDeviceSettings200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteSecureWebGatewayDeviceSettings200Response(val *DeleteSecureWebGatewayDeviceSettings200Response) *NullableDeleteSecureWebGatewayDeviceSettings200Response {
	return &NullableDeleteSecureWebGatewayDeviceSettings200Response{value: val, isSet: true}
}

func (v NullableDeleteSecureWebGatewayDeviceSettings200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteSecureWebGatewayDeviceSettings200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


