/*
Cisco Secure Web Gateway Device Settings API

Manage the Secure Access Secure Web Gateway (SWG) settings for the devices in an organization.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swg

import (
	"encoding/json"
	"fmt"
)

// checks if the ListSecureWebGatewayDeviceSettingsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListSecureWebGatewayDeviceSettingsRequest{}

// ListSecureWebGatewayDeviceSettingsRequest The `originIds` property.
type ListSecureWebGatewayDeviceSettingsRequest struct {
	// The list of origin IDs. The list can contain 1–100 origin IDs.
	OriginIds []int64 `json:"originIds"`
	AdditionalProperties map[string]interface{}
}

type _ListSecureWebGatewayDeviceSettingsRequest ListSecureWebGatewayDeviceSettingsRequest

// NewListSecureWebGatewayDeviceSettingsRequest instantiates a new ListSecureWebGatewayDeviceSettingsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListSecureWebGatewayDeviceSettingsRequest(originIds []int64) *ListSecureWebGatewayDeviceSettingsRequest {
	this := ListSecureWebGatewayDeviceSettingsRequest{}
	this.OriginIds = originIds
	return &this
}

// NewListSecureWebGatewayDeviceSettingsRequestWithDefaults instantiates a new ListSecureWebGatewayDeviceSettingsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListSecureWebGatewayDeviceSettingsRequestWithDefaults() *ListSecureWebGatewayDeviceSettingsRequest {
	this := ListSecureWebGatewayDeviceSettingsRequest{}
	return &this
}

// GetOriginIds returns the OriginIds field value
func (o *ListSecureWebGatewayDeviceSettingsRequest) GetOriginIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.OriginIds
}

// GetOriginIdsOk returns a tuple with the OriginIds field value
// and a boolean to check if the value has been set.
func (o *ListSecureWebGatewayDeviceSettingsRequest) GetOriginIdsOk() ([]int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.OriginIds, true
}

// SetOriginIds sets field value
func (o *ListSecureWebGatewayDeviceSettingsRequest) SetOriginIds(v []int64) {
	o.OriginIds = v
}

func (o ListSecureWebGatewayDeviceSettingsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListSecureWebGatewayDeviceSettingsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["originIds"] = o.OriginIds

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListSecureWebGatewayDeviceSettingsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"originIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListSecureWebGatewayDeviceSettingsRequest := _ListSecureWebGatewayDeviceSettingsRequest{}

	err = json.Unmarshal(data, &varListSecureWebGatewayDeviceSettingsRequest)

	if err != nil {
		return err
	}

	*o = ListSecureWebGatewayDeviceSettingsRequest(varListSecureWebGatewayDeviceSettingsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "originIds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListSecureWebGatewayDeviceSettingsRequest struct {
	value *ListSecureWebGatewayDeviceSettingsRequest
	isSet bool
}

func (v NullableListSecureWebGatewayDeviceSettingsRequest) Get() *ListSecureWebGatewayDeviceSettingsRequest {
	return v.value
}

func (v *NullableListSecureWebGatewayDeviceSettingsRequest) Set(val *ListSecureWebGatewayDeviceSettingsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableListSecureWebGatewayDeviceSettingsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableListSecureWebGatewayDeviceSettingsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSecureWebGatewayDeviceSettingsRequest(val *ListSecureWebGatewayDeviceSettingsRequest) *NullableListSecureWebGatewayDeviceSettingsRequest {
	return &NullableListSecureWebGatewayDeviceSettingsRequest{value: val, isSet: true}
}

func (v NullableListSecureWebGatewayDeviceSettingsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSecureWebGatewayDeviceSettingsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


