/*
Cisco Secure Web Gateway Device Settings API

Manage the Secure Access Secure Web Gateway (SWG) settings for the devices in an organization.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swg

import (
	"encoding/json"
	"fmt"
)

// checks if the ListSWGDeviceSettingsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListSWGDeviceSettingsInner{}

// ListSWGDeviceSettingsInner The properties of the secure web gateway settings for the device.
type ListSWGDeviceSettingsInner struct {
	// The origin ID of the device.
	OriginId int64 `json:"originId"`
	// The name of the device setting.
	Name string `json:"name"`
	Value Value `json:"value"`
	// The date and time when the settings on the device were modified. The timestamp is in the ISO 8601 date format.
	ModifiedAt string `json:"modifiedAt"`
	AdditionalProperties map[string]interface{}
}

type _ListSWGDeviceSettingsInner ListSWGDeviceSettingsInner

// NewListSWGDeviceSettingsInner instantiates a new ListSWGDeviceSettingsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListSWGDeviceSettingsInner(originId int64, name string, value Value, modifiedAt string) *ListSWGDeviceSettingsInner {
	this := ListSWGDeviceSettingsInner{}
	this.OriginId = originId
	this.Name = name
	this.Value = value
	this.ModifiedAt = modifiedAt
	return &this
}

// NewListSWGDeviceSettingsInnerWithDefaults instantiates a new ListSWGDeviceSettingsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListSWGDeviceSettingsInnerWithDefaults() *ListSWGDeviceSettingsInner {
	this := ListSWGDeviceSettingsInner{}
	return &this
}

// GetOriginId returns the OriginId field value
func (o *ListSWGDeviceSettingsInner) GetOriginId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.OriginId
}

// GetOriginIdOk returns a tuple with the OriginId field value
// and a boolean to check if the value has been set.
func (o *ListSWGDeviceSettingsInner) GetOriginIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OriginId, true
}

// SetOriginId sets field value
func (o *ListSWGDeviceSettingsInner) SetOriginId(v int64) {
	o.OriginId = v
}

// GetName returns the Name field value
func (o *ListSWGDeviceSettingsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ListSWGDeviceSettingsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ListSWGDeviceSettingsInner) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *ListSWGDeviceSettingsInner) GetValue() Value {
	if o == nil {
		var ret Value
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ListSWGDeviceSettingsInner) GetValueOk() (*Value, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ListSWGDeviceSettingsInner) SetValue(v Value) {
	o.Value = v
}

// GetModifiedAt returns the ModifiedAt field value
func (o *ListSWGDeviceSettingsInner) GetModifiedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModifiedAt
}

// GetModifiedAtOk returns a tuple with the ModifiedAt field value
// and a boolean to check if the value has been set.
func (o *ListSWGDeviceSettingsInner) GetModifiedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModifiedAt, true
}

// SetModifiedAt sets field value
func (o *ListSWGDeviceSettingsInner) SetModifiedAt(v string) {
	o.ModifiedAt = v
}

func (o ListSWGDeviceSettingsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListSWGDeviceSettingsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["originId"] = o.OriginId
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value
	toSerialize["modifiedAt"] = o.ModifiedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListSWGDeviceSettingsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"originId",
		"name",
		"value",
		"modifiedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListSWGDeviceSettingsInner := _ListSWGDeviceSettingsInner{}

	err = json.Unmarshal(data, &varListSWGDeviceSettingsInner)

	if err != nil {
		return err
	}

	*o = ListSWGDeviceSettingsInner(varListSWGDeviceSettingsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "originId")
		delete(additionalProperties, "name")
		delete(additionalProperties, "value")
		delete(additionalProperties, "modifiedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListSWGDeviceSettingsInner struct {
	value *ListSWGDeviceSettingsInner
	isSet bool
}

func (v NullableListSWGDeviceSettingsInner) Get() *ListSWGDeviceSettingsInner {
	return v.value
}

func (v *NullableListSWGDeviceSettingsInner) Set(val *ListSWGDeviceSettingsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListSWGDeviceSettingsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListSWGDeviceSettingsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSWGDeviceSettingsInner(val *ListSWGDeviceSettingsInner) *NullableListSWGDeviceSettingsInner {
	return &NullableListSWGDeviceSettingsInner{value: val, isSet: true}
}

func (v NullableListSWGDeviceSettingsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSWGDeviceSettingsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


