openapi: 3.0.1
info:
  contact:
    name: Cloud Security Developer Community
  description: |
    Manage the properties of the Resource Connector Groups and Resource Connectors in the organization.
  title: Cisco Secure Access Resource Connector Groups and Resource Connectors API
  version: 1.0.0
servers:
- url: "https://api.sse.cisco.com/{basePath}"
  variables:
    basePath:
      default: deployments/v2
security:
- oauthFlow: []
tags:
- description: Manage the Resource Connector Groups.
  name: Connector Groups
- description: Manage the Resource Connectors.
  name: Connectors
paths:
  /connectorGroups:
    get:
      description: |-
        List the Resource Connector Groups in the organization.
        If you include query filters on the request, the response is a subset of the Resource Connector Groups in the organization.
      operationId: listConnectorGroups
      security:
      - oauthFlow:
        - deployments.resourceconnectors:read
      summary: List Resource Connector Groups
      tags:
      - Connector Groups
    post:
      description: Create a Resource Connector Group in the organization.
      operationId: createConnectorGroup
      security:
      - oauthFlow:
        - deployments.resourceconnectors:write
      summary: Create Resource Connector Group
      tags:
      - Connector Groups
  /connectorGroups/{id}:
    delete:
      description: "Delete the Resouce Connector Group, including the Connectors in\
        \ the Resource Connector Group."
      operationId: deleteConnectorGroup
      security:
      - oauthFlow:
        - deployments.resourceconnectors:write
      summary: Delete Resource Connector Group
      tags:
      - Connector Groups
    get:
      description: Get the details about a Resource Connector Group.
      operationId: getConnectorGroup
      security:
      - oauthFlow:
        - deployments.resourceconnectors:read
      summary: Get Resource Connector Group
      tags:
      - Connector Groups
    patch:
      description: "Update the `name` or `location` properties on the Resource Connector\
        \ Group, or refresh the Resource Connector Group's provisioning key."
      operationId: patchConnectorGroup
      security:
      - oauthFlow:
        - deployments.resourceconnectors:write
      summary: Patch Resource Connector Group
      tags:
      - Connector Groups
    put:
      description: Update the `name` and `location` properties on the Resource Connector
        Group.
      operationId: putConnectorGroup
      security:
      - oauthFlow:
        - deployments.resourceconnectors:write
      summary: Update Resource Connector Group
      tags:
      - Connector Groups
  /connectorGroups/counts:
    get:
      description: Get the counts of the state information for the Resource Connector
        Groups.
      operationId: getConnectorGroupCount
      security:
      - oauthFlow:
        - deployments.resourceconnectors:read
      summary: Get Counts Resource Connector Groups States
      tags:
      - Connector Groups
  /connectorAgents:
    get:
      description: |-
        List the Connectors for the Resouce Connector Groups in the organization.
        If you include query filters on the request, the response is a subset of the Connectors in the organization.
      operationId: listConnectors
      security:
      - oauthFlow:
        - deployments.resourceconnectors:read
      summary: List Connectors
      tags:
      - Connectors
  /connectorAgents/{id}:
    delete:
      description: Remove the Connector from the Resource Connector Group in the organization.
      operationId: deleteConnector
      security:
      - oauthFlow:
        - deployments.resourceconnectors:write
      summary: Delete Connector
      tags:
      - Connectors
    get:
      description: Get the details about a Connector.
      operationId: getConnector
      security:
      - oauthFlow:
        - deployments.resourceconnectors:read
      summary: Get Connector
      tags:
      - Connectors
    patch:
      description: Update the properties on the Connector.
      operationId: patchConnector
      security:
      - oauthFlow:
        - deployments.resourceconnectors:write
      summary: Patch Connector
      tags:
      - Connectors
  /connectorAgents/counts:
    get:
      description: Get the counts of the state information for the Connectors.
      operationId: getConnectorAgentCount
      security:
      - oauthFlow:
        - deployments.resourceconnectors:read
      summary: Get Counts Connectors States
      tags:
      - Connectors
components:
  securitySchemes:
    oauthFlow:
      description: Client credential flow
      flows:
        clientCredentials:
          scopes:
            deployments.resourceconnectors:read: Read the Resource Connector Group
              or Connector resources
            deployments.resourceconnectors:write: Write the Resource Connector Group
              or Connector resources
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
