openapi: 3.0.1
info:
  title: Cisco Secure Access Reports
  description: |-
    Reporting
    App Discovery
    API Usage
    Metering
  version: 1.0.0
  contact:
    name: Cloud Security Developer Community
servers:
  - url: https://api.sse.cisco.com
security:
  - oauthFlow: []
tags:
  - name: Identities
paths:
  /reports/v2/activity:
    get:
      tags:
        - Activity

      summary: Get Activities (all)
      description: |-
        List all activities (dns/proxy/firewall/ip/intrusion/ztna/decryption) within the timeframe.
        **Note:** The IP activity report is not available.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getActivities
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/activity/dns:
    get:
      tags:
        - Activity

      summary: Get Activity DNS
      description: |-
        List all DNS entries within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getActivityDns
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/activity/proxy:
    get:
      tags:
        - Activity

      summary: Get Activity Proxy
      description: |-
        List all proxy entries within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getActivityProxy
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/activity/firewall:
    get:
      tags:
        - Activity

      summary: Get Activity Firewall
      description: |-
        List all firewall activity within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getActivityFirewall
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/activity/intrusion:
    get:
      tags:
        - Activity

      summary: Get Activity Intrusion
      description: |-
        List all Intrusion Prevention System (IPS) activity within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getActivityIntrusion
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/activity/ip:
    get:
      tags:
        - Activity

      summary: Get Activity IP
      description: |-
        (Deprecated) List all IP activity within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getActivityIP
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/activity/amp-retrospective:
    get:
      tags:
        - Activity

      summary: Get Activity AMP Retrospective
      description: |-
        List all AMP retrospective activity within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getActivityAmpRetrospective
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/activity/ztna:
    get:
      tags:
        - Activity

      summary: Activity ZTNA
      description: |-
        List all Zero Trust Network Access (ZTNA) entries within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getActivityZTNA
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/activity/decryption:
    get:
      tags:
        - Activity

      summary: Activity Decryption
      description: |-
        List all decryption entries within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getActivityDecryption
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/top-identities:
    get:
      tags:
        - Top Identities

      summary: Get Top Identities (All)
      description: |-
        List the identities by the number of requests made, sorted in descending order.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopIdentities
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/top-identities/{type}:
    get:
      tags:
        - Top Identities

      summary: Get Top Identities
      description: |-
        List the identities for the specific traffic type by the number of requests.
        Sort the results in descending order.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopIdentitiesType
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/identity-distribution:
    get:
      tags:
        - Identity Distribution

      summary: Get Identity Distribution (All)
      description: |-
        List the number of requests by identity types.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getIdentityDistribution
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/identity-distribution/{type}:
    get:
      tags:
        - Identity Distribution

      summary: Get Identity Distribution By Type
      description: |-
        List the number of requests by identity for the type of traffic.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getIdentityDistributionType
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/top-resources:
    get:
      tags:
        - Top Resources

      summary: Top Resources (all)
      description: |-
        List all resources in descending order. Order the collection by the number of requests to get the resources.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getTopResources
      security:
        - oauthFlow:
            - reports.privateResources:read
  /reports/v2/top-resources/{type}:
    get:
      tags:
        - Top Resources

      summary: Top Resources by Type
      description: |-
        List the resources for the type of activity in descending order.
        Order the collection by the number of requests to get the resources.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getTopResourcesType
      security:
        - oauthFlow:
            - reports.privateResources:read
  /reports/v2/top-destinations:
    get:
      tags:
        - Top Destinations

      summary: Get Top Destinations
      description: |-
        List the destinations by the number of requests made to this destination.
        Return the results in descending order.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopDestinations
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/top-destinations/{type}:
    get:
      tags:
        - Top Destinations

      summary: Get Top Destinations By Type
      description: |-
        List the destinations by type of destination and the number of requests made
        to this destination. Return the collection in descending order.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopDestinationsType
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/top-urls:
    get:
      tags:
        - Top Destinations

      summary: Get Top URLs
      description: |-
        List the top number of URLs that are requested for a certain domain.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopUrls
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/top-categories:
    get:
      tags:
        - Top Categories

      summary: Get Top Categories (All)
      description: |-
        List the categories that received the greatest number of requests.
        Order the number of requests in descending order.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopCategories
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/top-categories/{type}:
    get:
      tags:
        - Top Categories

      summary: Get Top Categories By Type
      description: |-
        List the categories for the type of traffic that received the greatest number of requests.
        Order the number of requests in descending order.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopCategoriesType
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/top-eventtypes:
    get:
      tags:
        - Top Event Types

      summary: Get Top Event Types (All)
      description: |-
        List the top event types by the number of requests made for each type of event.
        Order the number of requests in descending order.
        The valid event types are: `domain_security`, `domain_integration`,
        `url_security`, `url_integration`, `cisco_amp`, and `antivirus`.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopEventTypes
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/top-dns-query-types:
    get:
      tags:
        - Top DNS Query Types

      summary: Get Top DNS Query Types
      operationId: getTopDNSQueryTypes
      description: |-
        List the top types of DNS query.

        **Access Scope:** Reports > Aggregations > Read-Only
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/requests-by-hour:
    get:
      tags:
        - Organization Requests by Hour

      summary: Get Requests by Hour (All)
      description: |-
        List the activity volume within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getRequestsByHour
      security:
        - oauthFlow:
            - reports.granularEvents:read
  /reports/v2/requests-by-hour/{type}:
    get:
      tags:
        - Organization Requests by Hour

      summary: Get Requests by Hour
      description: |-
        List the activity volume within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getOrganizationRequestsByHour
      security:
        - oauthFlow:
            - reports.granularEvents:read
  /reports/v2/requests-by-timerange:
    get:
      tags:
        - Organization Requests by Timerange

      summary: Get Requests by Timerange (All)
      description: |-
        List the activity volume within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getRequestsByTimerange
      security:
        - oauthFlow:
            - reports.granularEvents:read
  /reports/v2/requests-by-timerange/{type}:
    get:
      tags:
        - Organization Requests by Timerange

      summary: Get Requests by Timerange
      description: |-
        List the activity volume within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getRequestsByTimerangeType
      security:
        - oauthFlow:
            - reports.granularEvents:read
  /reports/v2/categories-by-hour:
    get:
      tags:
        - Organization Requests by Hour and Category

      summary: Get Requests by Hour and Category (All)
      description: |-
        List the activity volume within the timeframe by type of category.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getRequestsByHourAndCategory
      security:
        - oauthFlow:
            - reports.granularEvents:read
  /reports/v2/categories-by-hour/{type}:
    get:
      tags:
        - Organization Requests by Hour and Category

      summary: Get Requests by Hour and Category
      description: |-
        List the activity volume for the type of category within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getRequestsByHourAndCategoryAndType
      security:
        - oauthFlow:
            - reports.granularEvents:read
  /reports/v2/categories-by-timerange:
    get:
      tags:
        - Organization Requests by Timerange and Category

      summary: Get Requests by Timerange and Category (All)
      description: |-
        List the activity volume within the timeframe by category.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getRequestsByTimerangeAndCategory
      security:
        - oauthFlow:
            - reports.granularEvents:read
  /reports/v2/categories-by-timerange/{type}:
    get:
      tags:
        - Organization Requests by Timerange and Category

      summary: Get Requests by Timerange and Category
      description: |-
        List the activity volume within the timeframe by category.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getRequestsByTimerangeAndCategoryType
      security:
        - oauthFlow:
            - reports.granularEvents:read
  /reports/v2/deployment-status:
    get:
      tags:
        - Deployment Status

      summary: Get Deployment Status
      description: |-
        List the deployment status within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getDeploymentStatus
      security:
        - oauthFlow:
            - reports.granularEvents:read
  /reports/v2/bandwidth-by-hour:
    get:
      tags:
        - Bandwidth by Hour

      summary: Get Bandwidth by Hour (All)
      description: |-
        List the bandwidth in bytes within the timeframe. Only returns proxy data.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getBandwidthByHour
      security:
        - oauthFlow:
            - reports.granularEvents:read
  /reports/v2/bandwidth-by-timerange:
    get:
      tags:
        - Bandwidth by Timerange

      summary: Get Bandwidth by Timerange (All)
      description: |-
        List the bandwidth in bytes within the timeframe. Only returns proxy data.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getBandwidthByTimerange
      security:
        - oauthFlow:
            - reports.granularEvents:read
  /reports/v2/top-files:
    get:
      tags:
        - Top Files

      summary: Get Top Files (Proxy)
      description: |-
        List the top files within the timeframe. Only returns proxy data.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopFilesProxy
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/total-requests:
    get:
      tags:
        - Total Requests

      summary: Get Total Requests (All)
      description: |-
        Get the count of the total requests.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTotalRequests
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/total-requests/{type}:
    get:
      tags:
        - Total Requests

      summary: Get Total Requests (By Type)
      description: |-
        Get the count of the total requests for the request type.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTotalRequestsByType
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/requests-summary/appconnector-groups:
    get:
      tags:
        - Requests Summary Resource Connector Groups

      summary: Get Requests Summary for Resource Connector Groups
      description: |-
        Get the summary of the request counts for the Resource Connector Groups in the organization.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getRequestsSummaryForAppConnectorGroups
      security:
        - oauthFlow:
            - reports.privateResources:read
  /reports/v2/requests-by-appconnector:
    get:
      tags:
        - Requests Resource Connector

      summary: Get Total Requests by Resource Connector
      description: |-
        Get the count of the total requests for each Resource Connector.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getTotalRequestsForAppConnector
      security:
        - oauthFlow:
            - reports.privateResources:read
  /reports/v2/requests-by-appconnector-group:
    get:
      tags:
        - Requests Resource Connector

      summary: Get Total Requests by Resource Connector Group
      description: |-
        Get the count of the total requests for the Resource Connector Group.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getTotalRequestsForAppConnectorGroup
      security:
        - oauthFlow:
            - reports.privateResources:read
  /reports/v2/top-threats:
    get:
      tags:
        - Top Threats

      summary: Get Top Threats (All)
      description: |-
        Get the top threats within the timeframe. Returns both DNS and proxy data.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopThreats
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/top-threats/{type}:
    get:
      tags:
        - Top Threats

      summary: Get Top Threats (By Type)
      description: |-
        Get the top threats within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopThreatsByType
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/top-threat-types:
    get:
      tags:
        - Top Threat Types

      summary: Get Top Threat Types (All)
      description: |-
        List the top types of threat within the timeframe. Returns both DNS and proxy data.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopThreatTypes
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/top-threat-types/{type}:
    get:
      tags:
        - Top Threat Types

      summary: Get Top Threat Types By Type
      description: |-
        List the top threat-types within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopThreatTypesByType
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/applications:
    get:
      summary: Get Applications
      operationId: getApplications
      description: |-
        List the applications.

        **Access Scope:** Reports > Utilities > Read-Only
      security:
        - oauthFlow:
            - reports.utilities:read
  /reports/v2/categories:
    get:
      tags:
        - Utility

      summary: Get Categories
      description: |-
        List the categories.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: getCategories
      security:
        - oauthFlow:
            - reports.utilities:read
  /reports/v2/identities:
    get:
      tags:
        - Utility

      summary: Get Identities
      operationId: getIdentities
      description: |-
        List the identities.

        **Access Scope:** Reports > Utilities > Read-Only
      security:
        - oauthFlow:
            - reports.utilities:read
    post:
      tags:
        - Utility

      summary: Get Identities By IDs
      description: |-
        Get the identities information by providing a list of identity IDs in the request body.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: postIdentities
      security:
        - oauthFlow:
            - reports.utilities:read
  /reports/v2/identities/{identityid}:
    get:
      tags:
        - Utility

      summary: Get Identity
      description: |-
        Get identity by identity ID.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: getIdentity
      security:
        - oauthFlow:
            - reports.utilities:read
  /reports/v2/threat-types:
    get:
      tags:
        - Utility

      summary: Get Threat Types
      description: |-
        List the threat types.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: getThreatTypes
      security:
        - oauthFlow:
            - reports.utilities:read
  /reports/v2/threat-types/{threattypeid}:
    get:
      tags:
        - Utility

      summary: Get Threat Type By Threat ID
      description: |-
        List the threat types by threat ID.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: getThreatType
      security:
        - oauthFlow:
            - reports.utilities:read
  /reports/v2/threat-names:
    get:
      tags:
        - Utility

      summary: Get Threat Names
      description: |-
        List the threat names.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: getThreatNames
      security:
        - oauthFlow:
            - reports.utilities:read
  /reports/v2/threat-names/{threatnameid}:
    get:
      tags:
        - Utility

      summary: Get Threat Name By Threat ID
      description: |-
        Get the threat name by threat ID.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: getThreatName
      security:
        - oauthFlow:
            - reports.utilities:read
  /reports/v2/top-ips:
    get:
      tags:
        - Top IPs

      summary: Get Top IPs
      description: |-
        List the top IP addresses.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopIps
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/top-ips/internal:
    get:
      tags:
        - Top IPs

      summary: Get Top IPs Internal
      description: |-
        List the top internal IP addresses.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopIpsInternal
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/summary:
    get:
      tags:
        - Summary

      summary: Get Summary (All)
      description: |-
        Get the summary report.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getSummary
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/summary/{type}:
    get:
      tags:
        - Summary

      summary: Get Summary By Type
      description: |-
        Get the summary of requests by the traffic type.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getSummaryByType
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/summaries-by-category:
    get:
      tags:
        - Summaries by Category

      summary: Get Summaries by Category (All)
      description: |-
        List the summaries of requests by category.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getSummariesByCategory
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/summaries-by-category/{type}:
    get:
      tags:
        - Summaries by Category

      summary: Get Summaries by Category For Type
      description: |-
        List the summaries by category for the type of request.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getSummariesByCategoryType
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/summaries-by-destination:
    get:
      tags:
        - Summaries by Destination

      summary: Get Summaries by Destination (All)
      description: |-
        List the summaries by destination.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getSummariesByDestination
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/summaries-by-destination/{type}:
    get:
      tags:
        - Summaries by Destination

      summary: Get Summaries by Destination For Type
      description: |-
        List the summaries by destination for the type of traffic.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getSummariesByDestinationType
      security:
        - oauthFlow:
            - reports.aggregations:read
  /reports/v2/summaries-by-rule/firewall-hitcount:
    get:
      tags:
        - Summaries by Rule

      summary: Get Summaries by Rule for Policy Rule Firewall Hit Count
      description: |-
        List the summaries by rule for the policy rule firewall hit count.

        **Access Scope:** Reports > Summaries by rule > Read-Only
      operationId: getSummariesByRuleFirewallHitcount
      security:
        - oauthFlow:
            - reports.summariesByRule:read
  /reports/v2/summaries-by-rule/hitcount:
    get:
      tags:
        - Summaries by Rule

      summary: Get Summaries by Rule for Policy Rule Hit Count
      description: |-
        List the summaries by rule for the policy rule hit count.

        **Access Scope:** Reports > Summaries by rule > Read-Only
      operationId: getSummariesByRuleHitcount
      security:
        - oauthFlow:
            - reports.summariesByRule:read
  /reports/v2/summaries-by-rule/intrusion:
    get:
      tags:
        - Summaries by Rule

      summary: Get Summaries by Rule
      description: |-
        List the summaries by rule for the intrusion type.

        **Access Scope:** Reports > Summaries by rule > Read-Only
      operationId: getSummariesByRuleIntrusion
      security:
        - oauthFlow:
            - reports.summariesByRule:read
  /reports/v2/remote-access-events:
    get:
      tags:
        - Remote Access

      summary: Get Remote Access Events
      description: |-
        List the events logged by remote access VPN.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getRemoteAccessEvents
      security:
        - oauthFlow:
            - reports.granularEvents:read
  /reports/v2/private-resources/detailed-stats-timerange:
    get:
      tags:
        - Private Resource

      summary: Get Private Resource Access Statistics in Details Report
      description: |-
        Get the detailed access statistics for a private resource, including total hits count and success or blocked count in a series of time ranges.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getPrivateResourceDetailedStatsTimerange
      security:
        - oauthFlow:
            - reports.privateResources:read
  /reports/v2/private-resources/detailed-stats-identities:
    get:
      tags:
        - Private Resource

      summary: Get Private Resource Access Statistics in Identity Report
      description: |-
        Get detailed identity access statistics for a private resource, including a list of identities, total hits count,
        and success or blocked count.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getPrivateResourceDetailedStatsIdentities
      security:
        - oauthFlow:
            - reports.privateResources:read
  /reports/v2/private-resources/summary-stats:
    get:
      tags:
        - Private Resource

      summary: Get Private Resource Access Statistics in Summary Report
      description: |-
        Get summary statistics of the hits count, the number of identities that accessed the resources,
        and the last access time for a list of private resource IDs.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getPrivateResourceStats
      security:
        - oauthFlow:
            - reports.privateResources:read
  /reports/v2/unique-resources:
    get:
      tags:
        - Unique Resources

      summary: Get Unique Resources (All)
      description: |-
        Get a count of the number of unique resources.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getUniqueResources
      security:
        - oauthFlow:
            - reports.privateResources:read
  /reports/v2/app-connectors/groups/detailed-stats-timerange:
    get:
      tags:
        - Resource Connectors

      summary: Get Detailed Resource Connector Group Statistics
      description: |-
        Get detailed Resource Connector Group statistics for either group IDs (`groupIds`) or CPU Threshold (`cputhreshold`) parameters,
        The response includes the average CPU utilization and timestamp for every group in a series of time ranges.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getDetailedStatsForAppConnectorGroups
      security:
        - oauthFlow:
            - reports.privateResources:read
  /reports/v2/app-connectors/groups/overloaded-count:
    get:
      tags:
        - Resource Connectors

      summary: Get Count of Overloaded Groups
      description: |-
        Get the count of the overloaded groups that have a CPU Threshold greater than the CPU Threshold (`cputhreshold`) value.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getOverloadedGroupsCount
      security:
        - oauthFlow:
            - reports.privateResources:read
  /reports/v2/app-connectors/detailed-stats-timerange:
    get:
      tags:
        - Resource Connectors

      summary: Get Detailed Resource Connector Statistics
      description: |-
        Get detailed Resource Connector statistics for the connector IDs, includes average CPU utilization, total request,
        group ID, and timestamp for every connector ID.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getDetailedStatsForAppConnector
      security:
        - oauthFlow:
            - reports.privateResources:read
  /reports/v2/rules-activity:
    get:
      tags:
        - Rules Activity

      summary: Get the Rules for the Event Activity
      description: |-
        Get details about events related to the organization's rules including verdict and resource.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: rulesActivity
      security:
        - oauthFlow:
            - reports.privateResources:read
  /reports/v2/appDiscovery/applications:
    get:
      summary: List Applications
      description: List all discovered applications.
      operationId: getApplicationsAppDiscovery
      security:
        - oauthFlow:
            - reports.appDiscovery:read
    patch:
      tags:
        - Applications

      summary: Update Applications
      description: Update the labels for the applications.
      operationId: patchApplications
      security:
        - oauthFlow:
            - reports.appDiscovery:write
  /reports/v2/appDiscovery/applications/{applicationId}:
    get:
      tags:
        - Applications

      summary: Get Application
      description: Get an application by ID.
      operationId: getApplication
      security:
        - oauthFlow:
            - reports.appDiscovery:read
    patch:
      tags:
        - Applications

      summary: Update Application
      description: Update the label for the application. Provide an application label in the request body.
      operationId: updateApplication
      security:
        - oauthFlow:
            - reports.appDiscovery:write
  /reports/v2/appDiscovery/applications/{applicationId}/risk:
    get:
      tags:
        - Applications

      summary: Get Application Risk
      description: Get the risk for the application.
      operationId: getApplicationRisk
      security:
        - oauthFlow:
            - reports.appDiscovery:read
  /reports/v2/appDiscovery/applications/{applicationId}/identities:
    get:
      tags:
        - Applications

      summary: List Application Identities
      description: List all identities for the application.
      operationId: getApplicationIdentities
      security:
        - oauthFlow:
            - reports.appDiscovery:read
  /reports/v2/appDiscovery/applications/{applicationId}/attributes:
    get:
      tags:
        - Applications

      summary: List Application Attributes
      description: List all attributes for the application.
      operationId: getApplicationAttributes
      security:
        - oauthFlow:
            - reports.appDiscovery:read
  /reports/v2/appDiscovery/protocols:
    get:
      tags:
        - Protocols

      summary: List Protocols
      description: List all protocols.
      operationId: getProtocols
      security:
        - oauthFlow:
            - reports.appDiscovery:read
  /reports/v2/appDiscovery/protocols/{protocolId}:
    get:
      tags:
        - Protocols

      summary: Get Protocol
      description: Get protocol by ID.
      operationId: getProtocol
      security:
        - oauthFlow:
            - reports.appDiscovery:read
  /reports/v2/appDiscovery/protocols/{protocolId}/identities:
    get:
      tags:
        - Identities

      summary: List Protocol Identities
      description: List identities for a specific protocol.
      operationId: getProtocolIdentities
      security:
        - oauthFlow:
            - reports.appDiscovery:read
  /reports/v2/appDiscovery/applicationCategories:
    get:
      tags:
        - Application Categories

      summary: List Application Categories
      description: List all application categories.
      operationId: getApplicationCategories
      security:
        - oauthFlow:
            - reports.appDiscovery:read
  /reports/v2/usage/metrics:
    get:
      summary: List Usage Metrics
      description: List the usage metrics for the organization.
      tags:
        - Usage Metrics

      operationId: getUsageMetrics
      security:
        - oauthFlow:
            - reports.usage.metrics:read
  /reports/v2/apiUsage/requests:
    get:
      operationId: getAPIUsageRequests
      summary: Get Requests
      description: |-
        Get the information about the API requests for the organization within a specific time period, including
        the total number of API requests for the type of client program.
      tags:
        - API Usage Report
      security:
        - oauthFlow:
            - reports.apiusage:read
  /reports/v2/apiUsage/responses:
    get:
      operationId: getAPIUsageResponses
      summary: Get Responses
      description: |-
        Get the information about the API responses for the organization within a specific time period, including
        the total number of API responses and the HTTP status codes.
      tags:
        - API Usage Report
      security:
        - oauthFlow:
            - reports.apiusage:read
  /reports/v2/apiUsage/keys:
    get:
      operationId: getAPIUsageKeys
      summary: Get Keys
      description: Get the API key usage information, including the total number of API requests within a specific time period.
      tags:
        - API Usage Report
      security:
        - oauthFlow:
            - reports.apiusage:read
  /reports/v2/apiUsage/summary:
    get:
      operationId: getAPIUsageSummary
      summary: Get Summary
      description: Get the total number API requests, and the counts of the successful and failed API requests within a specific time period.
      tags:
        - API Usage Report
      security:
        - oauthFlow:
            - reports.apiusage:read
components:
  securitySchemes:
    oauthFlow:
      type: oauth2
      description: client credential flow
      flows:
        clientCredentials:
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
          scopes:
            reports.granularEvents:read: Read reports granular events
            reports.utilities:read: Read reports utilities
            reports.aggregations:read: Read reports aggregations
            reports.summariesByRule:read: Read reports for the summaries of the rule
            reports.privateResources:read: Read reports for the private resources
            reports.appDiscovery:write: Write reports app discovery
            reports.appDiscovery:read: Read reports app discovery
            reports.usage.metrics:read: Get usage data
            reports.apiusage:read: Read the API Usage reports