// Copyright 2026 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Private Resources and Resource Groups API

Manage the Private Resources and Resource Groups in the organization.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package privateapps

import (
	"encoding/json"
	"fmt"
)

// ProtocolProxyToResource The protocol for the communication between the proxy and the Private Resource. Only applicable for browser-based Zero Trust Network Access.
type ProtocolProxyToResource string

// List of protocolProxyToResource
const (
	HTTPS ProtocolProxyToResource = "HTTPS"
	HTTP ProtocolProxyToResource = "HTTP"
)

// All allowed values of ProtocolProxyToResource enum
var AllowedProtocolProxyToResourceEnumValues = []ProtocolProxyToResource{
	"HTTPS",
	"HTTP",
}

func (v *ProtocolProxyToResource) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ProtocolProxyToResource(value)
	for _, existing := range AllowedProtocolProxyToResourceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ProtocolProxyToResource", value)
}

// NewProtocolProxyToResourceFromValue returns a pointer to a valid ProtocolProxyToResource
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewProtocolProxyToResourceFromValue(v string) (*ProtocolProxyToResource, error) {
	ev := ProtocolProxyToResource(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ProtocolProxyToResource: valid values are %v", v, AllowedProtocolProxyToResourceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ProtocolProxyToResource) IsValid() bool {
	for _, existing := range AllowedProtocolProxyToResourceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to protocolProxyToResource value
func (v ProtocolProxyToResource) Ptr() *ProtocolProxyToResource {
	return &v
}

type NullableProtocolProxyToResource struct {
	value *ProtocolProxyToResource
	isSet bool
}

func (v NullableProtocolProxyToResource) Get() *ProtocolProxyToResource {
	return v.value
}

func (v *NullableProtocolProxyToResource) Set(val *ProtocolProxyToResource) {
	v.value = val
	v.isSet = true
}

func (v NullableProtocolProxyToResource) IsSet() bool {
	return v.isSet
}

func (v *NullableProtocolProxyToResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProtocolProxyToResource(val *ProtocolProxyToResource) *NullableProtocolProxyToResource {
	return &NullableProtocolProxyToResource{value: val, isSet: true}
}

func (v NullableProtocolProxyToResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProtocolProxyToResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

