// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Rules, Rule Settings, and Application Lists APIs

Create and manage the access rules, rule settings, and application lists.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rules

import (
	"encoding/json"
	"fmt"
)

// checks if the PutRulesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutRulesRequest{}

// PutRulesRequest Set the `ruleIsEnabled` property on the rules.
type PutRulesRequest struct {
	// The list of rule IDs for the rules. Set the `rulesIsEnabled` property on these rules.
	RuleIds []int64 `json:"ruleIds"`
	// The list of the `ruleIsEnabled` setting for the rules.
	Properties []PutRulesRequestPropertiesInner `json:"properties"`
	AdditionalProperties map[string]interface{}
}

type _PutRulesRequest PutRulesRequest

// NewPutRulesRequest instantiates a new PutRulesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutRulesRequest(ruleIds []int64, properties []PutRulesRequestPropertiesInner) *PutRulesRequest {
	this := PutRulesRequest{}
	this.RuleIds = ruleIds
	this.Properties = properties
	return &this
}

// NewPutRulesRequestWithDefaults instantiates a new PutRulesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutRulesRequestWithDefaults() *PutRulesRequest {
	this := PutRulesRequest{}
	return &this
}

// GetRuleIds returns the RuleIds field value
func (o *PutRulesRequest) GetRuleIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.RuleIds
}

// GetRuleIdsOk returns a tuple with the RuleIds field value
// and a boolean to check if the value has been set.
func (o *PutRulesRequest) GetRuleIdsOk() ([]int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.RuleIds, true
}

// SetRuleIds sets field value
func (o *PutRulesRequest) SetRuleIds(v []int64) {
	o.RuleIds = v
}

// GetProperties returns the Properties field value
func (o *PutRulesRequest) GetProperties() []PutRulesRequestPropertiesInner {
	if o == nil {
		var ret []PutRulesRequestPropertiesInner
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *PutRulesRequest) GetPropertiesOk() ([]PutRulesRequestPropertiesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Properties, true
}

// SetProperties sets field value
func (o *PutRulesRequest) SetProperties(v []PutRulesRequestPropertiesInner) {
	o.Properties = v
}

func (o PutRulesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutRulesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ruleIds"] = o.RuleIds
	toSerialize["properties"] = o.Properties

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PutRulesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ruleIds",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPutRulesRequest := _PutRulesRequest{}

	err = json.Unmarshal(data, &varPutRulesRequest)

	if err != nil {
		return err
	}

	*o = PutRulesRequest(varPutRulesRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ruleIds")
		delete(additionalProperties, "properties")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePutRulesRequest struct {
	value *PutRulesRequest
	isSet bool
}

func (v NullablePutRulesRequest) Get() *PutRulesRequest {
	return v.value
}

func (v *NullablePutRulesRequest) Set(val *PutRulesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutRulesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutRulesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutRulesRequest(val *PutRulesRequest) *NullablePutRulesRequest {
	return &NullablePutRulesRequest{value: val, isSet: true}
}

func (v NullablePutRulesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutRulesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


