/*
Cisco Secure Access Rules, Rule Settings, and Application Lists APIs

Create and manage the access rules, rule settings, and application lists.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rules

import (
	"encoding/json"
	"fmt"
)

// checks if the SettingsResponseObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingsResponseObject{}

// SettingsResponseObject The properties of the rule setting.
type SettingsResponseObject struct {
	SettingName SettingName `json:"settingName"`
	SettingValue SettingValue `json:"settingValue"`
	// The date and time that the rule setting was created.
	CreatedAt string `json:"createdAt"`
	// The date and time that the rule setting was modified.
	ModifiedAt string `json:"modifiedAt"`
	AdditionalProperties map[string]interface{}
}

type _SettingsResponseObject SettingsResponseObject

// NewSettingsResponseObject instantiates a new SettingsResponseObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsResponseObject(settingName SettingName, settingValue SettingValue, createdAt string, modifiedAt string) *SettingsResponseObject {
	this := SettingsResponseObject{}
	this.SettingName = settingName
	this.SettingValue = settingValue
	this.CreatedAt = createdAt
	this.ModifiedAt = modifiedAt
	return &this
}

// NewSettingsResponseObjectWithDefaults instantiates a new SettingsResponseObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsResponseObjectWithDefaults() *SettingsResponseObject {
	this := SettingsResponseObject{}
	return &this
}

// GetSettingName returns the SettingName field value
func (o *SettingsResponseObject) GetSettingName() SettingName {
	if o == nil {
		var ret SettingName
		return ret
	}

	return o.SettingName
}

// GetSettingNameOk returns a tuple with the SettingName field value
// and a boolean to check if the value has been set.
func (o *SettingsResponseObject) GetSettingNameOk() (*SettingName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SettingName, true
}

// SetSettingName sets field value
func (o *SettingsResponseObject) SetSettingName(v SettingName) {
	o.SettingName = v
}

// GetSettingValue returns the SettingValue field value
func (o *SettingsResponseObject) GetSettingValue() SettingValue {
	if o == nil {
		var ret SettingValue
		return ret
	}

	return o.SettingValue
}

// GetSettingValueOk returns a tuple with the SettingValue field value
// and a boolean to check if the value has been set.
func (o *SettingsResponseObject) GetSettingValueOk() (*SettingValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SettingValue, true
}

// SetSettingValue sets field value
func (o *SettingsResponseObject) SetSettingValue(v SettingValue) {
	o.SettingValue = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *SettingsResponseObject) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SettingsResponseObject) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SettingsResponseObject) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetModifiedAt returns the ModifiedAt field value
func (o *SettingsResponseObject) GetModifiedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModifiedAt
}

// GetModifiedAtOk returns a tuple with the ModifiedAt field value
// and a boolean to check if the value has been set.
func (o *SettingsResponseObject) GetModifiedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModifiedAt, true
}

// SetModifiedAt sets field value
func (o *SettingsResponseObject) SetModifiedAt(v string) {
	o.ModifiedAt = v
}

func (o SettingsResponseObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingsResponseObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["settingName"] = o.SettingName
	toSerialize["settingValue"] = o.SettingValue
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["modifiedAt"] = o.ModifiedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SettingsResponseObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"settingName",
		"settingValue",
		"createdAt",
		"modifiedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSettingsResponseObject := _SettingsResponseObject{}

	err = json.Unmarshal(data, &varSettingsResponseObject)

	if err != nil {
		return err
	}

	*o = SettingsResponseObject(varSettingsResponseObject)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "settingName")
		delete(additionalProperties, "settingValue")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "modifiedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSettingsResponseObject struct {
	value *SettingsResponseObject
	isSet bool
}

func (v NullableSettingsResponseObject) Get() *SettingsResponseObject {
	return v.value
}

func (v *NullableSettingsResponseObject) Set(val *SettingsResponseObject) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsResponseObject) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsResponseObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsResponseObject(val *SettingsResponseObject) *NullableSettingsResponseObject {
	return &NullableSettingsResponseObject{value: val, isSet: true}
}

func (v NullableSettingsResponseObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsResponseObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


