// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Rules, Rule Settings, and Application Lists APIs

Create and manage the access rules, rule settings, and application lists.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rules

import (
	"encoding/json"
)

// checks if the RuleFilters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RuleFilters{}

// RuleFilters Filter the rules by the rule properties. **Note:** You can filter on either `ruleConditions` or the set of `sources` and `destinations` properties, but not both sets of properties.
type RuleFilters struct {
	// The name of the rule. The name must be unique across all rules for the organization's policy. The name can have no more than 256 characters.
	RuleName *string `json:"ruleName,omitempty"`
	// The meaningful information about the rule. The description can have no more than 256 characters.
	RuleDescription *string `json:"ruleDescription,omitempty"`
	// Specifies whether the rule is enabled.
	RuleIsEnabled *bool `json:"ruleIsEnabled,omitempty"`
	// Specifies whether the rule is the default rule.
	RuleIsDefault *bool `json:"ruleIsDefault,omitempty"`
	RuleAction *RuleAction `json:"ruleAction,omitempty"`
	AttributeName *AttributeName `json:"attributeName,omitempty"`
	AttributeValue *AttributeValue `json:"attributeValue,omitempty"`
	SettingName *SettingName `json:"settingName,omitempty"`
	SettingValue *SettingValue `json:"settingValue,omitempty"`
	// Filter on the priorities of the rules. Provide a comma-separated string of integers that correspond to the priorities of your rules.
	RulePriority *string `json:"rulePriority,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RuleFilters RuleFilters

// NewRuleFilters instantiates a new RuleFilters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRuleFilters() *RuleFilters {
	this := RuleFilters{}
	return &this
}

// NewRuleFiltersWithDefaults instantiates a new RuleFilters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRuleFiltersWithDefaults() *RuleFilters {
	this := RuleFilters{}
	return &this
}

// GetRuleName returns the RuleName field value if set, zero value otherwise.
func (o *RuleFilters) GetRuleName() string {
	if o == nil || IsNil(o.RuleName) {
		var ret string
		return ret
	}
	return *o.RuleName
}

// GetRuleNameOk returns a tuple with the RuleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleFilters) GetRuleNameOk() (*string, bool) {
	if o == nil || IsNil(o.RuleName) {
		return nil, false
	}
	return o.RuleName, true
}

// HasRuleName returns a boolean if a field has been set.
func (o *RuleFilters) HasRuleName() bool {
	if o != nil && !IsNil(o.RuleName) {
		return true
	}

	return false
}

// SetRuleName gets a reference to the given string and assigns it to the RuleName field.
func (o *RuleFilters) SetRuleName(v string) {
	o.RuleName = &v
}

// GetRuleDescription returns the RuleDescription field value if set, zero value otherwise.
func (o *RuleFilters) GetRuleDescription() string {
	if o == nil || IsNil(o.RuleDescription) {
		var ret string
		return ret
	}
	return *o.RuleDescription
}

// GetRuleDescriptionOk returns a tuple with the RuleDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleFilters) GetRuleDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.RuleDescription) {
		return nil, false
	}
	return o.RuleDescription, true
}

// HasRuleDescription returns a boolean if a field has been set.
func (o *RuleFilters) HasRuleDescription() bool {
	if o != nil && !IsNil(o.RuleDescription) {
		return true
	}

	return false
}

// SetRuleDescription gets a reference to the given string and assigns it to the RuleDescription field.
func (o *RuleFilters) SetRuleDescription(v string) {
	o.RuleDescription = &v
}

// GetRuleIsEnabled returns the RuleIsEnabled field value if set, zero value otherwise.
func (o *RuleFilters) GetRuleIsEnabled() bool {
	if o == nil || IsNil(o.RuleIsEnabled) {
		var ret bool
		return ret
	}
	return *o.RuleIsEnabled
}

// GetRuleIsEnabledOk returns a tuple with the RuleIsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleFilters) GetRuleIsEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.RuleIsEnabled) {
		return nil, false
	}
	return o.RuleIsEnabled, true
}

// HasRuleIsEnabled returns a boolean if a field has been set.
func (o *RuleFilters) HasRuleIsEnabled() bool {
	if o != nil && !IsNil(o.RuleIsEnabled) {
		return true
	}

	return false
}

// SetRuleIsEnabled gets a reference to the given bool and assigns it to the RuleIsEnabled field.
func (o *RuleFilters) SetRuleIsEnabled(v bool) {
	o.RuleIsEnabled = &v
}

// GetRuleIsDefault returns the RuleIsDefault field value if set, zero value otherwise.
func (o *RuleFilters) GetRuleIsDefault() bool {
	if o == nil || IsNil(o.RuleIsDefault) {
		var ret bool
		return ret
	}
	return *o.RuleIsDefault
}

// GetRuleIsDefaultOk returns a tuple with the RuleIsDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleFilters) GetRuleIsDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.RuleIsDefault) {
		return nil, false
	}
	return o.RuleIsDefault, true
}

// HasRuleIsDefault returns a boolean if a field has been set.
func (o *RuleFilters) HasRuleIsDefault() bool {
	if o != nil && !IsNil(o.RuleIsDefault) {
		return true
	}

	return false
}

// SetRuleIsDefault gets a reference to the given bool and assigns it to the RuleIsDefault field.
func (o *RuleFilters) SetRuleIsDefault(v bool) {
	o.RuleIsDefault = &v
}

// GetRuleAction returns the RuleAction field value if set, zero value otherwise.
func (o *RuleFilters) GetRuleAction() RuleAction {
	if o == nil || IsNil(o.RuleAction) {
		var ret RuleAction
		return ret
	}
	return *o.RuleAction
}

// GetRuleActionOk returns a tuple with the RuleAction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleFilters) GetRuleActionOk() (*RuleAction, bool) {
	if o == nil || IsNil(o.RuleAction) {
		return nil, false
	}
	return o.RuleAction, true
}

// HasRuleAction returns a boolean if a field has been set.
func (o *RuleFilters) HasRuleAction() bool {
	if o != nil && !IsNil(o.RuleAction) {
		return true
	}

	return false
}

// SetRuleAction gets a reference to the given RuleAction and assigns it to the RuleAction field.
func (o *RuleFilters) SetRuleAction(v RuleAction) {
	o.RuleAction = &v
}

// GetAttributeName returns the AttributeName field value if set, zero value otherwise.
func (o *RuleFilters) GetAttributeName() AttributeName {
	if o == nil || IsNil(o.AttributeName) {
		var ret AttributeName
		return ret
	}
	return *o.AttributeName
}

// GetAttributeNameOk returns a tuple with the AttributeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleFilters) GetAttributeNameOk() (*AttributeName, bool) {
	if o == nil || IsNil(o.AttributeName) {
		return nil, false
	}
	return o.AttributeName, true
}

// HasAttributeName returns a boolean if a field has been set.
func (o *RuleFilters) HasAttributeName() bool {
	if o != nil && !IsNil(o.AttributeName) {
		return true
	}

	return false
}

// SetAttributeName gets a reference to the given AttributeName and assigns it to the AttributeName field.
func (o *RuleFilters) SetAttributeName(v AttributeName) {
	o.AttributeName = &v
}

// GetAttributeValue returns the AttributeValue field value if set, zero value otherwise.
func (o *RuleFilters) GetAttributeValue() AttributeValue {
	if o == nil || IsNil(o.AttributeValue) {
		var ret AttributeValue
		return ret
	}
	return *o.AttributeValue
}

// GetAttributeValueOk returns a tuple with the AttributeValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleFilters) GetAttributeValueOk() (*AttributeValue, bool) {
	if o == nil || IsNil(o.AttributeValue) {
		return nil, false
	}
	return o.AttributeValue, true
}

// HasAttributeValue returns a boolean if a field has been set.
func (o *RuleFilters) HasAttributeValue() bool {
	if o != nil && !IsNil(o.AttributeValue) {
		return true
	}

	return false
}

// SetAttributeValue gets a reference to the given AttributeValue and assigns it to the AttributeValue field.
func (o *RuleFilters) SetAttributeValue(v AttributeValue) {
	o.AttributeValue = &v
}

// GetSettingName returns the SettingName field value if set, zero value otherwise.
func (o *RuleFilters) GetSettingName() SettingName {
	if o == nil || IsNil(o.SettingName) {
		var ret SettingName
		return ret
	}
	return *o.SettingName
}

// GetSettingNameOk returns a tuple with the SettingName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleFilters) GetSettingNameOk() (*SettingName, bool) {
	if o == nil || IsNil(o.SettingName) {
		return nil, false
	}
	return o.SettingName, true
}

// HasSettingName returns a boolean if a field has been set.
func (o *RuleFilters) HasSettingName() bool {
	if o != nil && !IsNil(o.SettingName) {
		return true
	}

	return false
}

// SetSettingName gets a reference to the given SettingName and assigns it to the SettingName field.
func (o *RuleFilters) SetSettingName(v SettingName) {
	o.SettingName = &v
}

// GetSettingValue returns the SettingValue field value if set, zero value otherwise.
func (o *RuleFilters) GetSettingValue() SettingValue {
	if o == nil || IsNil(o.SettingValue) {
		var ret SettingValue
		return ret
	}
	return *o.SettingValue
}

// GetSettingValueOk returns a tuple with the SettingValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleFilters) GetSettingValueOk() (*SettingValue, bool) {
	if o == nil || IsNil(o.SettingValue) {
		return nil, false
	}
	return o.SettingValue, true
}

// HasSettingValue returns a boolean if a field has been set.
func (o *RuleFilters) HasSettingValue() bool {
	if o != nil && !IsNil(o.SettingValue) {
		return true
	}

	return false
}

// SetSettingValue gets a reference to the given SettingValue and assigns it to the SettingValue field.
func (o *RuleFilters) SetSettingValue(v SettingValue) {
	o.SettingValue = &v
}

// GetRulePriority returns the RulePriority field value if set, zero value otherwise.
func (o *RuleFilters) GetRulePriority() string {
	if o == nil || IsNil(o.RulePriority) {
		var ret string
		return ret
	}
	return *o.RulePriority
}

// GetRulePriorityOk returns a tuple with the RulePriority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleFilters) GetRulePriorityOk() (*string, bool) {
	if o == nil || IsNil(o.RulePriority) {
		return nil, false
	}
	return o.RulePriority, true
}

// HasRulePriority returns a boolean if a field has been set.
func (o *RuleFilters) HasRulePriority() bool {
	if o != nil && !IsNil(o.RulePriority) {
		return true
	}

	return false
}

// SetRulePriority gets a reference to the given string and assigns it to the RulePriority field.
func (o *RuleFilters) SetRulePriority(v string) {
	o.RulePriority = &v
}

func (o RuleFilters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RuleFilters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RuleName) {
		toSerialize["ruleName"] = o.RuleName
	}
	if !IsNil(o.RuleDescription) {
		toSerialize["ruleDescription"] = o.RuleDescription
	}
	if !IsNil(o.RuleIsEnabled) {
		toSerialize["ruleIsEnabled"] = o.RuleIsEnabled
	}
	if !IsNil(o.RuleIsDefault) {
		toSerialize["ruleIsDefault"] = o.RuleIsDefault
	}
	if !IsNil(o.RuleAction) {
		toSerialize["ruleAction"] = o.RuleAction
	}
	if !IsNil(o.AttributeName) {
		toSerialize["attributeName"] = o.AttributeName
	}
	if !IsNil(o.AttributeValue) {
		toSerialize["attributeValue"] = o.AttributeValue
	}
	if !IsNil(o.SettingName) {
		toSerialize["settingName"] = o.SettingName
	}
	if !IsNil(o.SettingValue) {
		toSerialize["settingValue"] = o.SettingValue
	}
	if !IsNil(o.RulePriority) {
		toSerialize["rulePriority"] = o.RulePriority
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RuleFilters) UnmarshalJSON(data []byte) (err error) {
	varRuleFilters := _RuleFilters{}

	err = json.Unmarshal(data, &varRuleFilters)

	if err != nil {
		return err
	}

	*o = RuleFilters(varRuleFilters)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ruleName")
		delete(additionalProperties, "ruleDescription")
		delete(additionalProperties, "ruleIsEnabled")
		delete(additionalProperties, "ruleIsDefault")
		delete(additionalProperties, "ruleAction")
		delete(additionalProperties, "attributeName")
		delete(additionalProperties, "attributeValue")
		delete(additionalProperties, "settingName")
		delete(additionalProperties, "settingValue")
		delete(additionalProperties, "rulePriority")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRuleFilters struct {
	value *RuleFilters
	isSet bool
}

func (v NullableRuleFilters) Get() *RuleFilters {
	return v.value
}

func (v *NullableRuleFilters) Set(val *RuleFilters) {
	v.value = val
	v.isSet = true
}

func (v NullableRuleFilters) IsSet() bool {
	return v.isSet
}

func (v *NullableRuleFilters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRuleFilters(val *RuleFilters) *NullableRuleFilters {
	return &NullableRuleFilters{value: val, isSet: true}
}

func (v NullableRuleFilters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRuleFilters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


