/*
Cisco Secure Access Rules, Rule Settings, and Application Lists APIs

Create and manage the access rules, rule settings, and application lists.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rules

import (
	"encoding/json"
)

// checks if the SettingTypesResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingTypesResponseInner{}

// SettingTypesResponseInner struct for SettingTypesResponseInner
type SettingTypesResponseInner struct {
	// The list of services that are related to the policy setting type.
	ServiceScopes []string `json:"serviceScopes,omitempty"`
	// Specify whether the setting is for the rulesets.
	SettingForRulesets *bool `json:"settingForRulesets,omitempty"`
	// The ID of the setting.
	SettingId *int64 `json:"settingId,omitempty"`
	SettingName *SettingName `json:"settingName,omitempty"`
	// The type of the setting description.
	TypeDescription *string `json:"typeDescription,omitempty"`
	// The type of the setting name.
	TypeName *string `json:"typeName,omitempty"`
	// Specifiy whether the setting has the default value.
	TypeDefaultValue *bool `json:"typeDefaultValue,omitempty"`
	// The description of the access rule setting.
	SettingDescription *string `json:"settingDescription,omitempty"`
	// The regex pattern for validating the type.
	TypeValidationRegex *string `json:"typeValidationRegex,omitempty"`
	// Specify whether the setting is for the rules.
	SettingForRules *bool `json:"settingForRules,omitempty"`
	// Specify whether the setting is for the organization.
	SettingForOrganizations *bool `json:"settingForOrganizations,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SettingTypesResponseInner SettingTypesResponseInner

// NewSettingTypesResponseInner instantiates a new SettingTypesResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingTypesResponseInner() *SettingTypesResponseInner {
	this := SettingTypesResponseInner{}
	return &this
}

// NewSettingTypesResponseInnerWithDefaults instantiates a new SettingTypesResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingTypesResponseInnerWithDefaults() *SettingTypesResponseInner {
	this := SettingTypesResponseInner{}
	return &this
}

// GetServiceScopes returns the ServiceScopes field value if set, zero value otherwise.
func (o *SettingTypesResponseInner) GetServiceScopes() []string {
	if o == nil || IsNil(o.ServiceScopes) {
		var ret []string
		return ret
	}
	return o.ServiceScopes
}

// GetServiceScopesOk returns a tuple with the ServiceScopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingTypesResponseInner) GetServiceScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.ServiceScopes) {
		return nil, false
	}
	return o.ServiceScopes, true
}

// HasServiceScopes returns a boolean if a field has been set.
func (o *SettingTypesResponseInner) HasServiceScopes() bool {
	if o != nil && !IsNil(o.ServiceScopes) {
		return true
	}

	return false
}

// SetServiceScopes gets a reference to the given []string and assigns it to the ServiceScopes field.
func (o *SettingTypesResponseInner) SetServiceScopes(v []string) {
	o.ServiceScopes = v
}

// GetSettingForRulesets returns the SettingForRulesets field value if set, zero value otherwise.
func (o *SettingTypesResponseInner) GetSettingForRulesets() bool {
	if o == nil || IsNil(o.SettingForRulesets) {
		var ret bool
		return ret
	}
	return *o.SettingForRulesets
}

// GetSettingForRulesetsOk returns a tuple with the SettingForRulesets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingTypesResponseInner) GetSettingForRulesetsOk() (*bool, bool) {
	if o == nil || IsNil(o.SettingForRulesets) {
		return nil, false
	}
	return o.SettingForRulesets, true
}

// HasSettingForRulesets returns a boolean if a field has been set.
func (o *SettingTypesResponseInner) HasSettingForRulesets() bool {
	if o != nil && !IsNil(o.SettingForRulesets) {
		return true
	}

	return false
}

// SetSettingForRulesets gets a reference to the given bool and assigns it to the SettingForRulesets field.
func (o *SettingTypesResponseInner) SetSettingForRulesets(v bool) {
	o.SettingForRulesets = &v
}

// GetSettingId returns the SettingId field value if set, zero value otherwise.
func (o *SettingTypesResponseInner) GetSettingId() int64 {
	if o == nil || IsNil(o.SettingId) {
		var ret int64
		return ret
	}
	return *o.SettingId
}

// GetSettingIdOk returns a tuple with the SettingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingTypesResponseInner) GetSettingIdOk() (*int64, bool) {
	if o == nil || IsNil(o.SettingId) {
		return nil, false
	}
	return o.SettingId, true
}

// HasSettingId returns a boolean if a field has been set.
func (o *SettingTypesResponseInner) HasSettingId() bool {
	if o != nil && !IsNil(o.SettingId) {
		return true
	}

	return false
}

// SetSettingId gets a reference to the given int64 and assigns it to the SettingId field.
func (o *SettingTypesResponseInner) SetSettingId(v int64) {
	o.SettingId = &v
}

// GetSettingName returns the SettingName field value if set, zero value otherwise.
func (o *SettingTypesResponseInner) GetSettingName() SettingName {
	if o == nil || IsNil(o.SettingName) {
		var ret SettingName
		return ret
	}
	return *o.SettingName
}

// GetSettingNameOk returns a tuple with the SettingName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingTypesResponseInner) GetSettingNameOk() (*SettingName, bool) {
	if o == nil || IsNil(o.SettingName) {
		return nil, false
	}
	return o.SettingName, true
}

// HasSettingName returns a boolean if a field has been set.
func (o *SettingTypesResponseInner) HasSettingName() bool {
	if o != nil && !IsNil(o.SettingName) {
		return true
	}

	return false
}

// SetSettingName gets a reference to the given SettingName and assigns it to the SettingName field.
func (o *SettingTypesResponseInner) SetSettingName(v SettingName) {
	o.SettingName = &v
}

// GetTypeDescription returns the TypeDescription field value if set, zero value otherwise.
func (o *SettingTypesResponseInner) GetTypeDescription() string {
	if o == nil || IsNil(o.TypeDescription) {
		var ret string
		return ret
	}
	return *o.TypeDescription
}

// GetTypeDescriptionOk returns a tuple with the TypeDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingTypesResponseInner) GetTypeDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.TypeDescription) {
		return nil, false
	}
	return o.TypeDescription, true
}

// HasTypeDescription returns a boolean if a field has been set.
func (o *SettingTypesResponseInner) HasTypeDescription() bool {
	if o != nil && !IsNil(o.TypeDescription) {
		return true
	}

	return false
}

// SetTypeDescription gets a reference to the given string and assigns it to the TypeDescription field.
func (o *SettingTypesResponseInner) SetTypeDescription(v string) {
	o.TypeDescription = &v
}

// GetTypeName returns the TypeName field value if set, zero value otherwise.
func (o *SettingTypesResponseInner) GetTypeName() string {
	if o == nil || IsNil(o.TypeName) {
		var ret string
		return ret
	}
	return *o.TypeName
}

// GetTypeNameOk returns a tuple with the TypeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingTypesResponseInner) GetTypeNameOk() (*string, bool) {
	if o == nil || IsNil(o.TypeName) {
		return nil, false
	}
	return o.TypeName, true
}

// HasTypeName returns a boolean if a field has been set.
func (o *SettingTypesResponseInner) HasTypeName() bool {
	if o != nil && !IsNil(o.TypeName) {
		return true
	}

	return false
}

// SetTypeName gets a reference to the given string and assigns it to the TypeName field.
func (o *SettingTypesResponseInner) SetTypeName(v string) {
	o.TypeName = &v
}

// GetTypeDefaultValue returns the TypeDefaultValue field value if set, zero value otherwise.
func (o *SettingTypesResponseInner) GetTypeDefaultValue() bool {
	if o == nil || IsNil(o.TypeDefaultValue) {
		var ret bool
		return ret
	}
	return *o.TypeDefaultValue
}

// GetTypeDefaultValueOk returns a tuple with the TypeDefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingTypesResponseInner) GetTypeDefaultValueOk() (*bool, bool) {
	if o == nil || IsNil(o.TypeDefaultValue) {
		return nil, false
	}
	return o.TypeDefaultValue, true
}

// HasTypeDefaultValue returns a boolean if a field has been set.
func (o *SettingTypesResponseInner) HasTypeDefaultValue() bool {
	if o != nil && !IsNil(o.TypeDefaultValue) {
		return true
	}

	return false
}

// SetTypeDefaultValue gets a reference to the given bool and assigns it to the TypeDefaultValue field.
func (o *SettingTypesResponseInner) SetTypeDefaultValue(v bool) {
	o.TypeDefaultValue = &v
}

// GetSettingDescription returns the SettingDescription field value if set, zero value otherwise.
func (o *SettingTypesResponseInner) GetSettingDescription() string {
	if o == nil || IsNil(o.SettingDescription) {
		var ret string
		return ret
	}
	return *o.SettingDescription
}

// GetSettingDescriptionOk returns a tuple with the SettingDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingTypesResponseInner) GetSettingDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.SettingDescription) {
		return nil, false
	}
	return o.SettingDescription, true
}

// HasSettingDescription returns a boolean if a field has been set.
func (o *SettingTypesResponseInner) HasSettingDescription() bool {
	if o != nil && !IsNil(o.SettingDescription) {
		return true
	}

	return false
}

// SetSettingDescription gets a reference to the given string and assigns it to the SettingDescription field.
func (o *SettingTypesResponseInner) SetSettingDescription(v string) {
	o.SettingDescription = &v
}

// GetTypeValidationRegex returns the TypeValidationRegex field value if set, zero value otherwise.
func (o *SettingTypesResponseInner) GetTypeValidationRegex() string {
	if o == nil || IsNil(o.TypeValidationRegex) {
		var ret string
		return ret
	}
	return *o.TypeValidationRegex
}

// GetTypeValidationRegexOk returns a tuple with the TypeValidationRegex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingTypesResponseInner) GetTypeValidationRegexOk() (*string, bool) {
	if o == nil || IsNil(o.TypeValidationRegex) {
		return nil, false
	}
	return o.TypeValidationRegex, true
}

// HasTypeValidationRegex returns a boolean if a field has been set.
func (o *SettingTypesResponseInner) HasTypeValidationRegex() bool {
	if o != nil && !IsNil(o.TypeValidationRegex) {
		return true
	}

	return false
}

// SetTypeValidationRegex gets a reference to the given string and assigns it to the TypeValidationRegex field.
func (o *SettingTypesResponseInner) SetTypeValidationRegex(v string) {
	o.TypeValidationRegex = &v
}

// GetSettingForRules returns the SettingForRules field value if set, zero value otherwise.
func (o *SettingTypesResponseInner) GetSettingForRules() bool {
	if o == nil || IsNil(o.SettingForRules) {
		var ret bool
		return ret
	}
	return *o.SettingForRules
}

// GetSettingForRulesOk returns a tuple with the SettingForRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingTypesResponseInner) GetSettingForRulesOk() (*bool, bool) {
	if o == nil || IsNil(o.SettingForRules) {
		return nil, false
	}
	return o.SettingForRules, true
}

// HasSettingForRules returns a boolean if a field has been set.
func (o *SettingTypesResponseInner) HasSettingForRules() bool {
	if o != nil && !IsNil(o.SettingForRules) {
		return true
	}

	return false
}

// SetSettingForRules gets a reference to the given bool and assigns it to the SettingForRules field.
func (o *SettingTypesResponseInner) SetSettingForRules(v bool) {
	o.SettingForRules = &v
}

// GetSettingForOrganizations returns the SettingForOrganizations field value if set, zero value otherwise.
func (o *SettingTypesResponseInner) GetSettingForOrganizations() bool {
	if o == nil || IsNil(o.SettingForOrganizations) {
		var ret bool
		return ret
	}
	return *o.SettingForOrganizations
}

// GetSettingForOrganizationsOk returns a tuple with the SettingForOrganizations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingTypesResponseInner) GetSettingForOrganizationsOk() (*bool, bool) {
	if o == nil || IsNil(o.SettingForOrganizations) {
		return nil, false
	}
	return o.SettingForOrganizations, true
}

// HasSettingForOrganizations returns a boolean if a field has been set.
func (o *SettingTypesResponseInner) HasSettingForOrganizations() bool {
	if o != nil && !IsNil(o.SettingForOrganizations) {
		return true
	}

	return false
}

// SetSettingForOrganizations gets a reference to the given bool and assigns it to the SettingForOrganizations field.
func (o *SettingTypesResponseInner) SetSettingForOrganizations(v bool) {
	o.SettingForOrganizations = &v
}

func (o SettingTypesResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingTypesResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServiceScopes) {
		toSerialize["serviceScopes"] = o.ServiceScopes
	}
	if !IsNil(o.SettingForRulesets) {
		toSerialize["settingForRulesets"] = o.SettingForRulesets
	}
	if !IsNil(o.SettingId) {
		toSerialize["settingId"] = o.SettingId
	}
	if !IsNil(o.SettingName) {
		toSerialize["settingName"] = o.SettingName
	}
	if !IsNil(o.TypeDescription) {
		toSerialize["typeDescription"] = o.TypeDescription
	}
	if !IsNil(o.TypeName) {
		toSerialize["typeName"] = o.TypeName
	}
	if !IsNil(o.TypeDefaultValue) {
		toSerialize["typeDefaultValue"] = o.TypeDefaultValue
	}
	if !IsNil(o.SettingDescription) {
		toSerialize["settingDescription"] = o.SettingDescription
	}
	if !IsNil(o.TypeValidationRegex) {
		toSerialize["typeValidationRegex"] = o.TypeValidationRegex
	}
	if !IsNil(o.SettingForRules) {
		toSerialize["settingForRules"] = o.SettingForRules
	}
	if !IsNil(o.SettingForOrganizations) {
		toSerialize["settingForOrganizations"] = o.SettingForOrganizations
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SettingTypesResponseInner) UnmarshalJSON(data []byte) (err error) {
	varSettingTypesResponseInner := _SettingTypesResponseInner{}

	err = json.Unmarshal(data, &varSettingTypesResponseInner)

	if err != nil {
		return err
	}

	*o = SettingTypesResponseInner(varSettingTypesResponseInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "serviceScopes")
		delete(additionalProperties, "settingForRulesets")
		delete(additionalProperties, "settingId")
		delete(additionalProperties, "settingName")
		delete(additionalProperties, "typeDescription")
		delete(additionalProperties, "typeName")
		delete(additionalProperties, "typeDefaultValue")
		delete(additionalProperties, "settingDescription")
		delete(additionalProperties, "typeValidationRegex")
		delete(additionalProperties, "settingForRules")
		delete(additionalProperties, "settingForOrganizations")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSettingTypesResponseInner struct {
	value *SettingTypesResponseInner
	isSet bool
}

func (v NullableSettingTypesResponseInner) Get() *SettingTypesResponseInner {
	return v.value
}

func (v *NullableSettingTypesResponseInner) Set(val *SettingTypesResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingTypesResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingTypesResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingTypesResponseInner(val *SettingTypesResponseInner) *NullableSettingTypesResponseInner {
	return &NullableSettingTypesResponseInner{value: val, isSet: true}
}

func (v NullableSettingTypesResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingTypesResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


