/*
Cisco Secure Access Rules, Rule Settings, and Application Lists APIs

Create and manage the access rules, rule settings, and application lists.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rules

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// RuleFiltersValue - struct for RuleFiltersValue
type RuleFiltersValue struct {
	RuleSourceDestFilters *RuleSourceDestFilters
	ArrayOfRuleConditionsInner *[]RuleConditionsInner
}

// RuleSourceDestFiltersAsRuleFiltersValue is a convenience function that returns RuleSourceDestFilters wrapped in RuleFiltersValue
func RuleSourceDestFiltersAsRuleFiltersValue(v *RuleSourceDestFilters) RuleFiltersValue {
	return RuleFiltersValue{
		RuleSourceDestFilters: v,
	}
}

// []RuleConditionsInnerAsRuleFiltersValue is a convenience function that returns []RuleConditionsInner wrapped in RuleFiltersValue
func ArrayOfRuleConditionsInnerAsRuleFiltersValue(v *[]RuleConditionsInner) RuleFiltersValue {
	return RuleFiltersValue{
		ArrayOfRuleConditionsInner: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *RuleFiltersValue) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into RuleSourceDestFilters
	err = newStrictDecoder(data).Decode(&dst.RuleSourceDestFilters)
	if err == nil {
		jsonRuleSourceDestFilters, _ := json.Marshal(dst.RuleSourceDestFilters)
		if string(jsonRuleSourceDestFilters) == "{}" { // empty struct
			dst.RuleSourceDestFilters = nil
		} else {
			if err = validator.Validate(dst.RuleSourceDestFilters); err != nil {
				dst.RuleSourceDestFilters = nil
			} else {
				match++
			}
		}
	} else {
		dst.RuleSourceDestFilters = nil
	}

	// try to unmarshal data into ArrayOfRuleConditionsInner
	err = newStrictDecoder(data).Decode(&dst.ArrayOfRuleConditionsInner)
	if err == nil {
		jsonArrayOfRuleConditionsInner, _ := json.Marshal(dst.ArrayOfRuleConditionsInner)
		if string(jsonArrayOfRuleConditionsInner) == "{}" { // empty struct
			dst.ArrayOfRuleConditionsInner = nil
		} else {
			if err = validator.Validate(dst.ArrayOfRuleConditionsInner); err != nil {
				dst.ArrayOfRuleConditionsInner = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfRuleConditionsInner = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.RuleSourceDestFilters = nil
		dst.ArrayOfRuleConditionsInner = nil

		return fmt.Errorf("data matches more than one schema in oneOf(RuleFiltersValue)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(RuleFiltersValue)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RuleFiltersValue) MarshalJSON() ([]byte, error) {
	if src.RuleSourceDestFilters != nil {
		return json.Marshal(&src.RuleSourceDestFilters)
	}

	if src.ArrayOfRuleConditionsInner != nil {
		return json.Marshal(&src.ArrayOfRuleConditionsInner)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *RuleFiltersValue) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.RuleSourceDestFilters != nil {
		return obj.RuleSourceDestFilters
	}

	if obj.ArrayOfRuleConditionsInner != nil {
		return obj.ArrayOfRuleConditionsInner
	}

	// all schemas are nil
	return nil
}

type NullableRuleFiltersValue struct {
	value *RuleFiltersValue
	isSet bool
}

func (v NullableRuleFiltersValue) Get() *RuleFiltersValue {
	return v.value
}

func (v *NullableRuleFiltersValue) Set(val *RuleFiltersValue) {
	v.value = val
	v.isSet = true
}

func (v NullableRuleFiltersValue) IsSet() bool {
	return v.isSet
}

func (v *NullableRuleFiltersValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRuleFiltersValue(val *RuleFiltersValue) *NullableRuleFiltersValue {
	return &NullableRuleFiltersValue{value: val, isSet: true}
}

func (v NullableRuleFiltersValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRuleFiltersValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


