// Copyright 2025 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/*
Cisco Secure Access Rules, Rule Settings, and Application Lists APIs

Create and manage the access rules, rule settings, and application lists.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rules

import (
	"encoding/json"
	"fmt"
)

// checks if the SettingsResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingsResponseInner{}

// SettingsResponseInner struct for SettingsResponseInner
type SettingsResponseInner struct {
	SettingName SettingName `json:"settingName"`
	SettingValue SettingValue `json:"settingValue"`
	// The date and time that the rule was created.
	CreatedAt string `json:"createdAt"`
	// The date and time that the rule was modified.
	ModifiedAt string `json:"modifiedAt"`
	SettingId int64 `json:"settingId"`
	IsGlobal bool `json:"isGlobal"`
	AdditionalProperties map[string]interface{}
}

type _SettingsResponseInner SettingsResponseInner

// NewSettingsResponseInner instantiates a new SettingsResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsResponseInner(settingName SettingName, settingValue SettingValue, createdAt string, modifiedAt string, settingId int64, isGlobal bool) *SettingsResponseInner {
	this := SettingsResponseInner{}
	this.SettingName = settingName
	this.SettingValue = settingValue
	this.CreatedAt = createdAt
	this.ModifiedAt = modifiedAt
	this.SettingId = settingId
	this.IsGlobal = isGlobal
	return &this
}

// NewSettingsResponseInnerWithDefaults instantiates a new SettingsResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsResponseInnerWithDefaults() *SettingsResponseInner {
	this := SettingsResponseInner{}
	return &this
}

// GetSettingName returns the SettingName field value
func (o *SettingsResponseInner) GetSettingName() SettingName {
	if o == nil {
		var ret SettingName
		return ret
	}

	return o.SettingName
}

// GetSettingNameOk returns a tuple with the SettingName field value
// and a boolean to check if the value has been set.
func (o *SettingsResponseInner) GetSettingNameOk() (*SettingName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SettingName, true
}

// SetSettingName sets field value
func (o *SettingsResponseInner) SetSettingName(v SettingName) {
	o.SettingName = v
}

// GetSettingValue returns the SettingValue field value
func (o *SettingsResponseInner) GetSettingValue() SettingValue {
	if o == nil {
		var ret SettingValue
		return ret
	}

	return o.SettingValue
}

// GetSettingValueOk returns a tuple with the SettingValue field value
// and a boolean to check if the value has been set.
func (o *SettingsResponseInner) GetSettingValueOk() (*SettingValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SettingValue, true
}

// SetSettingValue sets field value
func (o *SettingsResponseInner) SetSettingValue(v SettingValue) {
	o.SettingValue = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *SettingsResponseInner) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SettingsResponseInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SettingsResponseInner) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetModifiedAt returns the ModifiedAt field value
func (o *SettingsResponseInner) GetModifiedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModifiedAt
}

// GetModifiedAtOk returns a tuple with the ModifiedAt field value
// and a boolean to check if the value has been set.
func (o *SettingsResponseInner) GetModifiedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModifiedAt, true
}

// SetModifiedAt sets field value
func (o *SettingsResponseInner) SetModifiedAt(v string) {
	o.ModifiedAt = v
}

// GetSettingId returns the SettingId field value
func (o *SettingsResponseInner) GetSettingId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SettingId
}

// GetSettingIdOk returns a tuple with the SettingId field value
// and a boolean to check if the value has been set.
func (o *SettingsResponseInner) GetSettingIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SettingId, true
}

// SetSettingId sets field value
func (o *SettingsResponseInner) SetSettingId(v int64) {
	o.SettingId = v
}

// GetIsGlobal returns the IsGlobal field value
func (o *SettingsResponseInner) GetIsGlobal() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsGlobal
}

// GetIsGlobalOk returns a tuple with the IsGlobal field value
// and a boolean to check if the value has been set.
func (o *SettingsResponseInner) GetIsGlobalOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsGlobal, true
}

// SetIsGlobal sets field value
func (o *SettingsResponseInner) SetIsGlobal(v bool) {
	o.IsGlobal = v
}

func (o SettingsResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingsResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["settingName"] = o.SettingName
	toSerialize["settingValue"] = o.SettingValue
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["modifiedAt"] = o.ModifiedAt
	toSerialize["settingId"] = o.SettingId
	toSerialize["isGlobal"] = o.IsGlobal

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SettingsResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"settingName",
		"settingValue",
		"createdAt",
		"modifiedAt",
		"settingId",
		"isGlobal",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSettingsResponseInner := _SettingsResponseInner{}

	err = json.Unmarshal(data, &varSettingsResponseInner)

	if err != nil {
		return err
	}

	*o = SettingsResponseInner(varSettingsResponseInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "settingName")
		delete(additionalProperties, "settingValue")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "modifiedAt")
		delete(additionalProperties, "settingId")
		delete(additionalProperties, "isGlobal")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSettingsResponseInner struct {
	value *SettingsResponseInner
	isSet bool
}

func (v NullableSettingsResponseInner) Get() *SettingsResponseInner {
	return v.value
}

func (v *NullableSettingsResponseInner) Set(val *SettingsResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsResponseInner(val *SettingsResponseInner) *NullableSettingsResponseInner {
	return &NullableSettingsResponseInner{value: val, isSet: true}
}

func (v NullableSettingsResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


