/*
Cisco Secure Access Rules, Rule Settings, and Application Lists APIs

Create and manage the access rules, rule settings, and application lists.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rules

import (
	"encoding/json"
	"fmt"
)

// AttributeNameDestinationComposite The name of the attribute for the source components.
type AttributeNameDestinationComposite string

// List of attributeNameDestinationComposite
const (
	ATTRIBUTENAMEDESTINATIONCOMPOSITE_UMBRELLA_DESTINATION_IP_ADDRESS AttributeNameDestinationComposite = "umbrella.destination.ip_address"
	ATTRIBUTENAMEDESTINATIONCOMPOSITE_UMBRELLA_DESTINATION_PORT AttributeNameDestinationComposite = "umbrella.destination.port"
	ATTRIBUTENAMEDESTINATIONCOMPOSITE_UMBRELLA_DESTINATION_NETWORK_PROTOCOL AttributeNameDestinationComposite = "umbrella.destination.network_protocol"
)

// All allowed values of AttributeNameDestinationComposite enum
var AllowedAttributeNameDestinationCompositeEnumValues = []AttributeNameDestinationComposite{
	"umbrella.destination.ip_address",
	"umbrella.destination.port",
	"umbrella.destination.network_protocol",
}

func (v *AttributeNameDestinationComposite) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AttributeNameDestinationComposite(value)
	for _, existing := range AllowedAttributeNameDestinationCompositeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AttributeNameDestinationComposite", value)
}

// NewAttributeNameDestinationCompositeFromValue returns a pointer to a valid AttributeNameDestinationComposite
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAttributeNameDestinationCompositeFromValue(v string) (*AttributeNameDestinationComposite, error) {
	ev := AttributeNameDestinationComposite(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AttributeNameDestinationComposite: valid values are %v", v, AllowedAttributeNameDestinationCompositeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AttributeNameDestinationComposite) IsValid() bool {
	for _, existing := range AllowedAttributeNameDestinationCompositeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to attributeNameDestinationComposite value
func (v AttributeNameDestinationComposite) Ptr() *AttributeNameDestinationComposite {
	return &v
}

type NullableAttributeNameDestinationComposite struct {
	value *AttributeNameDestinationComposite
	isSet bool
}

func (v NullableAttributeNameDestinationComposite) Get() *AttributeNameDestinationComposite {
	return v.value
}

func (v *NullableAttributeNameDestinationComposite) Set(val *AttributeNameDestinationComposite) {
	v.value = val
	v.isSet = true
}

func (v NullableAttributeNameDestinationComposite) IsSet() bool {
	return v.isSet
}

func (v *NullableAttributeNameDestinationComposite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttributeNameDestinationComposite(val *AttributeNameDestinationComposite) *NullableAttributeNameDestinationComposite {
	return &NullableAttributeNameDestinationComposite{value: val, isSet: true}
}

func (v NullableAttributeNameDestinationComposite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttributeNameDestinationComposite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

