/*
Cisco Secure Access Rules, Rule Settings, and Application Lists APIs

Create and manage the access rules, rule settings, and application lists.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rules

import (
	"encoding/json"
)

// checks if the GetApplicationLists404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetApplicationLists404Response{}

// GetApplicationLists404Response struct for GetApplicationLists404Response
type GetApplicationLists404Response struct {
	// Error message explaining the reason for failure.
	Error *string `json:"error,omitempty"`
	// The ID of the request.
	RequestId *string `json:"requestId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetApplicationLists404Response GetApplicationLists404Response

// NewGetApplicationLists404Response instantiates a new GetApplicationLists404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetApplicationLists404Response() *GetApplicationLists404Response {
	this := GetApplicationLists404Response{}
	return &this
}

// NewGetApplicationLists404ResponseWithDefaults instantiates a new GetApplicationLists404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetApplicationLists404ResponseWithDefaults() *GetApplicationLists404Response {
	this := GetApplicationLists404Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GetApplicationLists404Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApplicationLists404Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GetApplicationLists404Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *GetApplicationLists404Response) SetError(v string) {
	o.Error = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *GetApplicationLists404Response) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApplicationLists404Response) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *GetApplicationLists404Response) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *GetApplicationLists404Response) SetRequestId(v string) {
	o.RequestId = &v
}

func (o GetApplicationLists404Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetApplicationLists404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetApplicationLists404Response) UnmarshalJSON(data []byte) (err error) {
	varGetApplicationLists404Response := _GetApplicationLists404Response{}

	err = json.Unmarshal(data, &varGetApplicationLists404Response)

	if err != nil {
		return err
	}

	*o = GetApplicationLists404Response(varGetApplicationLists404Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "error")
		delete(additionalProperties, "requestId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetApplicationLists404Response struct {
	value *GetApplicationLists404Response
	isSet bool
}

func (v NullableGetApplicationLists404Response) Get() *GetApplicationLists404Response {
	return v.value
}

func (v *NullableGetApplicationLists404Response) Set(val *GetApplicationLists404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetApplicationLists404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetApplicationLists404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetApplicationLists404Response(val *GetApplicationLists404Response) *NullableGetApplicationLists404Response {
	return &NullableGetApplicationLists404Response{value: val, isSet: true}
}

func (v NullableGetApplicationLists404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetApplicationLists404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


