openapi: 3.0.3
info:
  contact:
    name: Cloud Security Developer Community
  description: Manage the Secure Access Network Tunnel Groups.
  title: Cisco Secure Access Network Tunnel Groups and Regions API
  version: 1.0.0
servers:
- url: "https://api.sse.cisco.com/{basePath}"
  variables:
    basePath:
      default: deployments/v2
security:
- oauthFlow: []
tags:
- description: Network Tunnel Groups API endpoints
  name: Network Tunnel Groups
- description: Network Tunnel Groups Regions API endpoints
  name: Network Tunnel Groups Regions
- description: Network Tunnel Groups State API endpoints
  name: Network Tunnel Groups State
- description: Network Tunnel Groups Peer State API endpoints
  name: Network Tunnel Groups Peer State
- name: Secure Access
paths:
  /networktunnelgroups:
    get:
      description: |-
        List the Network Tunnel Groups in the organization.
        If you enable the `includeStatuses` query parameter on your API request,
        then the `tunnelsStatus` field is included in the response.
        The maximum number of items in a hub's list of tunnel states (`tunnelsStatus`) is 10.
      operationId: listNetworkTunnelGroups
      security:
      - oauthFlow:
        - deployments.networktunnelgroups:read
      summary: List Network Tunnel Groups
      tags:
      - Network Tunnel Groups
    post:
      description: Create a Network Tunnel Group in the organization.
      operationId: addNetworkTunnelGroup
      security:
      - oauthFlow:
        - deployments.networktunnelgroups:write
      summary: Create Network Tunnel Group
      tags:
      - Network Tunnel Groups
  /networktunnelgroups/{id}:
    delete:
      description: Delete a Network Tunnel Group in the organization.
      operationId: deleteNetworkTunnelGroup
      security:
      - oauthFlow:
        - deployments.networktunnelgroups:write
      summary: Delete Network Tunnel Group
      tags:
      - Network Tunnel Groups
    get:
      description: Get a Network Tunnel Group in the organization.
      operationId: getNetworkTunnelGroup
      security:
      - oauthFlow:
        - deployments.networktunnelgroups:read
      summary: Get Network Tunnel Group
      tags:
      - Network Tunnel Groups
    patch:
      description: Update a Network Tunnel Group in the organization.
      operationId: patchNetworkTunnelGroup
      security:
      - oauthFlow:
        - deployments.networktunnelgroups:write
      summary: Update Network Tunnel Group
      tags:
      - Network Tunnel Groups
  /networktunnelgroups/{id}/state:
    get:
      description: |-
        Get the status information for the Network Tunnel Group in the organization.
        The maximum number of items in a hub's list of tunnel states (`tunnelsStatus`) is 10.
      operationId: getNetworkTunnelGroupState
      security:
      - oauthFlow:
        - deployments.networktunnelgroups:read
      summary: Get State of Network Tunnel Group
      tags:
      - Network Tunnel Groups State
  /networktunnelgroups/{id}/peers:
    get:
      description: Get the state of all peers (tunnels) within an organization's Network
        Tunnel Group and Hub.
      operationId: getPeersState
      security:
      - oauthFlow:
        - deployments.networktunnelgroups:read
      summary: Get Peers States for Network Tunnel Group and Hub
      tags:
      - Network Tunnel Groups Peer State
  /networktunnelgroups/{id}/networktunnelhubs/{hub_id}/peers/{peer_id}/state:
    get:
      description: Get the state of a peer (tunnel) within an organization's Network
        Tunnel Group and Hub.
      operationId: getPeerState
      security:
      - oauthFlow:
        - deployments.networktunnelgroups:read
      summary: Get Tunnel State for Network Tunnel Group and Hub
      tags:
      - Network Tunnel Groups Peer State
  /networktunnelgroupsstate:
    get:
      description: |-
        Get the state for each Network Tunnel Group in the organization.
        The maximum number of items in a hub's list of tunnel states (`tunnelsStatus`) is 10.
      operationId: getNetworkTunnelGroupBulkState
      security:
      - oauthFlow:
        - deployments.networktunnelgroups:read
      summary: List State of Network Tunnel Groups
      tags:
      - Network Tunnel Groups State
  /regions:
    get:
      description: List the available regions for the Network Tunnel Groups.
      operationId: listNetworkTunnelGroupRegions
      security:
      - oauthFlow:
        - deployments.regions:read
      summary: List Regions for Network Tunnel Groups
      tags:
      - Network Tunnel Groups Regions
components:
  securitySchemes:
    oauthFlow:
      description: client credential flow
      flows:
        clientCredentials:
          scopes:
            deployments.networktunnelgroups:read: Read network tunnel groups deployments
            deployments.networktunnelgroups:write: Write network tunnel groups deployments
            deployments.regions:read: Read regions for network tunnel groups deployments
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
