/*
Cisco Secure Access Internal Domains API

Manage the internal domains in your organization.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internaldomains

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateInternalDomainRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateInternalDomainRequest{}

// CreateInternalDomainRequest struct for CreateInternalDomainRequest
type CreateInternalDomainRequest struct {
	// The internal domain.
	Domain string `json:"domain"`
	// The description of the internal domain. The description is a sequence of characters with a length from 1 through 50.
	Description *string `json:"description,omitempty"`
	// Specifies whether to apply the internal domain to all virtual appliances.
	IncludeAllVAs *bool `json:"includeAllVAs,omitempty"`
	// Specifies whether to apply the internal domain to all mobile devices.
	IncludeAllMobileDevices *bool `json:"includeAllMobileDevices,omitempty"`
	// The list of site IDs associated with the domain.
	SiteIds []int64 `json:"siteIds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateInternalDomainRequest CreateInternalDomainRequest

// NewCreateInternalDomainRequest instantiates a new CreateInternalDomainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateInternalDomainRequest(domain string) *CreateInternalDomainRequest {
	this := CreateInternalDomainRequest{}
	this.Domain = domain
	return &this
}

// NewCreateInternalDomainRequestWithDefaults instantiates a new CreateInternalDomainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateInternalDomainRequestWithDefaults() *CreateInternalDomainRequest {
	this := CreateInternalDomainRequest{}
	return &this
}

// GetDomain returns the Domain field value
func (o *CreateInternalDomainRequest) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *CreateInternalDomainRequest) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *CreateInternalDomainRequest) SetDomain(v string) {
	o.Domain = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateInternalDomainRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInternalDomainRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateInternalDomainRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateInternalDomainRequest) SetDescription(v string) {
	o.Description = &v
}

// GetIncludeAllVAs returns the IncludeAllVAs field value if set, zero value otherwise.
func (o *CreateInternalDomainRequest) GetIncludeAllVAs() bool {
	if o == nil || IsNil(o.IncludeAllVAs) {
		var ret bool
		return ret
	}
	return *o.IncludeAllVAs
}

// GetIncludeAllVAsOk returns a tuple with the IncludeAllVAs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInternalDomainRequest) GetIncludeAllVAsOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeAllVAs) {
		return nil, false
	}
	return o.IncludeAllVAs, true
}

// HasIncludeAllVAs returns a boolean if a field has been set.
func (o *CreateInternalDomainRequest) HasIncludeAllVAs() bool {
	if o != nil && !IsNil(o.IncludeAllVAs) {
		return true
	}

	return false
}

// SetIncludeAllVAs gets a reference to the given bool and assigns it to the IncludeAllVAs field.
func (o *CreateInternalDomainRequest) SetIncludeAllVAs(v bool) {
	o.IncludeAllVAs = &v
}

// GetIncludeAllMobileDevices returns the IncludeAllMobileDevices field value if set, zero value otherwise.
func (o *CreateInternalDomainRequest) GetIncludeAllMobileDevices() bool {
	if o == nil || IsNil(o.IncludeAllMobileDevices) {
		var ret bool
		return ret
	}
	return *o.IncludeAllMobileDevices
}

// GetIncludeAllMobileDevicesOk returns a tuple with the IncludeAllMobileDevices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInternalDomainRequest) GetIncludeAllMobileDevicesOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeAllMobileDevices) {
		return nil, false
	}
	return o.IncludeAllMobileDevices, true
}

// HasIncludeAllMobileDevices returns a boolean if a field has been set.
func (o *CreateInternalDomainRequest) HasIncludeAllMobileDevices() bool {
	if o != nil && !IsNil(o.IncludeAllMobileDevices) {
		return true
	}

	return false
}

// SetIncludeAllMobileDevices gets a reference to the given bool and assigns it to the IncludeAllMobileDevices field.
func (o *CreateInternalDomainRequest) SetIncludeAllMobileDevices(v bool) {
	o.IncludeAllMobileDevices = &v
}

// GetSiteIds returns the SiteIds field value if set, zero value otherwise.
func (o *CreateInternalDomainRequest) GetSiteIds() []int64 {
	if o == nil || IsNil(o.SiteIds) {
		var ret []int64
		return ret
	}
	return o.SiteIds
}

// GetSiteIdsOk returns a tuple with the SiteIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInternalDomainRequest) GetSiteIdsOk() ([]int64, bool) {
	if o == nil || IsNil(o.SiteIds) {
		return nil, false
	}
	return o.SiteIds, true
}

// HasSiteIds returns a boolean if a field has been set.
func (o *CreateInternalDomainRequest) HasSiteIds() bool {
	if o != nil && !IsNil(o.SiteIds) {
		return true
	}

	return false
}

// SetSiteIds gets a reference to the given []int64 and assigns it to the SiteIds field.
func (o *CreateInternalDomainRequest) SetSiteIds(v []int64) {
	o.SiteIds = v
}

func (o CreateInternalDomainRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateInternalDomainRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domain"] = o.Domain
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.IncludeAllVAs) {
		toSerialize["includeAllVAs"] = o.IncludeAllVAs
	}
	if !IsNil(o.IncludeAllMobileDevices) {
		toSerialize["includeAllMobileDevices"] = o.IncludeAllMobileDevices
	}
	if !IsNil(o.SiteIds) {
		toSerialize["siteIds"] = o.SiteIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateInternalDomainRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateInternalDomainRequest := _CreateInternalDomainRequest{}

	err = json.Unmarshal(data, &varCreateInternalDomainRequest)

	if err != nil {
		return err
	}

	*o = CreateInternalDomainRequest(varCreateInternalDomainRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "domain")
		delete(additionalProperties, "description")
		delete(additionalProperties, "includeAllVAs")
		delete(additionalProperties, "includeAllMobileDevices")
		delete(additionalProperties, "siteIds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateInternalDomainRequest struct {
	value *CreateInternalDomainRequest
	isSet bool
}

func (v NullableCreateInternalDomainRequest) Get() *CreateInternalDomainRequest {
	return v.value
}

func (v *NullableCreateInternalDomainRequest) Set(val *CreateInternalDomainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateInternalDomainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateInternalDomainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateInternalDomainRequest(val *CreateInternalDomainRequest) *NullableCreateInternalDomainRequest {
	return &NullableCreateInternalDomainRequest{value: val, isSet: true}
}

func (v NullableCreateInternalDomainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateInternalDomainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


